/* exported timelineTest */

const colors = {
	d: '#33F', // Democratic
	dr: '#008000', // Democratic-Republican
	federalist: '#EA9978',
	nr: '#FFE6B0', // National Republican
	nu: '#B22222', // National Union
	r: '#E81B23',
	whig: '#F0C862',
};

const timelineTest = [
	// presidents
	{
		name: 'George Washington',
		start: '30 Apr 1789',
		end: '4 Mar 1797',
		href: true,
		forceY: 1,
	},
	{
		name: 'John Adams',
		start: '4 Mar 1797',
		end: '4 Mar 1801',
		color: colors.federalist,
		href: true,
		forceY: 1,
	},
	{
		name: 'Thomas Jefferson',
		start: '4 Mar 1801',
		end: '4 Mar 1809',
		color: colors.dr,
		href: true,
		forceY: 1,
	},
	{
		name: 'James Madison',
		start: '4 Mar 1809',
		end: '4 Mar 1817',
		color: colors.dr,
		href: true,
		forceY: 1,
	},
	{
		name: 'James Monroe',
		start: '4 Mar 1817',
		end: '4 Mar 1825',
		color: colors.dr,
		href: true,
		forceY: 1,
	},
	{
		name: 'John Quincy Adams',
		start: '4 Mar 1825',
		end: '4 Mar 1829',
		color: colors.dr,
		href: true,
		forceY: 1,
		insets: [
			{
				start: '1828',
				end: '4 Mar 1829',
				color: colors.nr,
			},
		],
	},
	{
		name: 'Andrew Jackson',
		start: '4 Mar 1829',
		end: '4 Mar 1837',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Martin Van Buren',
		start: '4 Mar 1837',
		end: '4 Mar 1841',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'William Henry Harrison',
		start: '4 Mar 1841',
		end: '4 Apr 1841',
		color: colors.whig,
		href: true,
		forceY: 1,
	},
	{
		name: 'John Tyler',
		start: '4 Apr 1841',
		end: '4 Mar 1845',
		href: true,
		forceY: 1,
	},
	{
		name: 'James K. Polk',
		start: '4 Mar 1845',
		end: '4 Mar 1849',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Zachary Taylor',
		start: '4 Mar 1849',
		end: '9 Jul 1850',
		color: colors.whig,
		href: true,
		forceY: 1,
	},
	{
		name: 'Millard Fillmore',
		start: '9 Jul 1850',
		end: '4 Mar 1853',
		color: colors.whig,
		href: true,
		forceY: 1,
	},
	{
		name: 'Franklin Pierce',
		start: '4 Mar 1853',
		end: '4 Mar 1857',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'James Buchanan',
		start: '4 Mar 1857',
		end: '4 Mar 1861',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Abraham Lincoln',
		start: '4 Mar 1857',
		end: '15 Apr 1865',
		color: colors.r,
		href: true,
		forceY: 1,
		insets: [
			{
				start: '1864',
				end: '15 Apr 1865',
				color: colors.nu,
			},
		],
	},
	{
		name: 'Andrew Johnson',
		start: '15 Apr 1865',
		end: '4 Mar 1869',
		color: colors.nu,
		href: true,
		forceY: 1,
		insets: [
			{
				start: '1868',
				end: '4 Mar 1869',
				color: colors.d,
			},
		],
	},
	{
		name: 'Ulysses S. Grant',
		start: '4 Mar 1869',
		end: '4 Mar 1877',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Rutherford B. Hayes',
		start: '4 Mar 1877',
		end: '4 Mar 1881',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'James A. Garfield',
		start: '4 Mar 1881',
		end: '19 Sep 1881',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Chester A. Arthur',
		start: '19 Sep 1881',
		end: '4 Mar 1885',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Grover Cleveland',
		start: '4 Mar 1885',
		end: '4 Mar 1889',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Benjamin Harrison',
		start: '4 Mar 1889',
		end: '4 Mar 1893',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Grover Cleveland',
		start: '4 Mar 1893',
		end: '4 Mar 1897',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Wiliam McKinley',
		start: '4 Mar 1897',
		end: '14 Sep 1901',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Theodore Roosevelt',
		start: '14 Sep 1901',
		end: '4 Mar 1909',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'William Howard Taft',
		start: '4 Mar 1909',
		end: '4 Mar 1913',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Woodrow Wilson',
		start: '4 Mar 1913',
		end: '4 Mar 1921',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Warren G. Harding',
		start: '4 Mar 1921',
		end: '2 Aug 1923',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Calvin Coolidge',
		start: '2 Aug 1923',
		end: '4 Mar 1929',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Herbert Hoover',
		start: '4 Mar 1929',
		end: '4 Mar 1933',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Franklin D. Roosevelt',
		start: '4 Mar 1933',
		end: '12 Apr 1945',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Harry S. Truman',
		start: '12 Apr 1945',
		end: '20 Jan 1953',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Dwight D. Eisenhower',
		start: '20 Jan 1953',
		end: '20 Jan 1961',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'John F. Kennedy',
		start: '20 Jan 1961',
		end: '22 Nov 1963',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Lyndon B. Johnson',
		start: '22 Nov 1963',
		end: '20 Jan 1969',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Richard Nixon',
		start: '20 Jan 1969',
		end: '9 Aug 1974',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Gerald Ford',
		start: '9 Aug 1974',
		end: '20 Jan 1977',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Jimmy Carter',
		start: '20 Jan 1977',
		end: '20 Jan 1981',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Ronald Reagan',
		start: '20 Jan 1981',
		end: '20 Jan 1989',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'George H. W. Bush',
		start: '20 Jan 1989',
		end: '20 Jan 1993',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Bill Clinton',
		start: '20 Jan 1993',
		end: '20 Jan 2001',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'George W. Bush',
		start: '20 Jan 2001',
		end: '20 Jan 2009',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Barack Obama',
		start: '20 Jan 2009',
		end: '20 Jan 2017',
		color: colors.d,
		href: true,
		forceY: 1,
	},
	{
		name: 'Donald Trump',
		start: '20 Jan 2017',
		end: '20 Jan 2021',
		color: colors.r,
		href: true,
		forceY: 1,
	},
	{
		name: 'Joe Biden',
		start: '20 Jan 2021',
		end: '20 Jan 2025',
		color: colors.d,
		href: true,
		forceY: 1,
	},
];