/* exported lifeData */
'use strict';
const lifeData = [
	{
		'name': 'example',
		'rank': 'rank',
		'parent': '*',
		'important': true,
		'extinct': true,
		'range': 'ww',
		'age': 800,
		'desc': 'This is an example of the format used on this page. The dagger indicates this clade is extinct. The two letters beside the name indicate the approximate native range. You can hover your cursor over the abbreviation to see a more detailed description. This clade diversified 800 mya.',
	},
	// BEGIN ALPHABETICAL ORDERING
	// A
	{
		'name': 'abies',
		'rank': 'genus',
		'parent': 'abietoideae',
		'range': 'nh',
		'desc': 'Fir',
	},
	{
		'name': 'abietoideae',
		'rank': 'subfamily',
		'parent': 'pinaceae',
		'range': 'nh',
	},
	{
		'name': 'acanthomorpha',
		'rank': 'clade',
		'parent': 'teleostei',
		'range': 'ww',
	},
	{
		'name': 'actinobacteria',
		'rank': 'phylum',
		'parent': 'terrabacteria',
		'range': 'ww',
	},
	{
		'name': 'actinomycetales',
		'rank': 'order',
		'parent': 'actinobacteria',
		'range': 'ww',
	},
	{
		'name': 'actinopterygii',
		'rank': 'class',
		'parent': 'osteichthyes',
		'range': 'ww',
		'age': 420,
	},
	{
		'name': 'allium',
		'rank': 'genus',
		'parent': 'amaryllidaceae',
		'range': 'ww',
	},
	{
		'name': 'allium cepa',
		'rank': 'species',
		'parent': 'allium',
		'range': 'as',
		'desc': 'Onion',
	},
	{
		'name': 'allium sativum',
		'rank': 'species',
		'parent': 'allium',
		'range': 'ow',
		'desc': 'Garlic',
	},
	{
		'name': 'amaryllidaceae',
		'rank': 'family',
		'parent': 'asparagales',
		'range': 'ww',
	},
	{
		'name': 'ammonoidea',
		'rank': 'subclass',
		'parent': 'cephalopoda',
		'extinct': true,
		'range': 'ww',
		'age': 409,
		'desc': 'Ammonite',
	},
	{
		'name': 'amniota',
		'rank': 'clade',
		'parent': 'tetrapoda',
		'range': 'ww',
		'age': 320,
		'desc': 'Amniotes lay their eggs on land or retain the fertilized egg within the mother, and are distinguished from anamniotes, which typically lay their eggs in water.',
	},
	{
		'name': 'amphibia',
		'rank': 'class',
		'parent': 'tetrapoda',
		'range': 'ww',
		'age': 370,
	},
	{
		'name': 'ananas',
		'rank': 'genus',
		'parent': 'bromeliaceae',
		'range': 'sa',
	},
	{
		'name': 'ananas comosus',
		'rank': 'species',
		'parent': 'ananas',
		'range': 'sa',
		'desc': 'Pineapple',
	},
	{
		'name': 'anatidae',
		'rank': 'family',
		'parent': 'anseriformes',
		'range': 'ww',
		'desc': 'Waterfowl',
	},
	{
		'name': 'anas',
		'rank': 'genus',
		'range': 'ww',
		'parent': 'anatidae',
	},
	{
		'name': 'anas platyrhynchos',
		'rank': 'species',
		'parent': 'anas',
		'range': 'nh',
		'desc': 'Mallard',
	},
	{
		'name': 'angiosperms',
		'rank': 'clade',
		'parent': 'plantae',
		'range': 'ww',
		'age': 130,
	},
	{
		'name': 'animalia',
		'rank': 'kingdom',
		'parent': 'opisthokonta',
		'range': 'ww',
		'age': 760,
		'desc': 'Animals consume organic material, breathe oxygen, are able to move, can reproduce sexually, and grow from a blastula during embryonic development.',
	},
	{
		'name': 'ankylosauridae',
		'rank': 'family',
		'parent': 'ornithischia',
		'extinct': true,
		'range': 'nh',
	},
	{
		'name': 'ankylosaurus',
		'rank': 'genus',
		'parent': 'ankylosauridae',
		'extinct': true,
		'range': 'na',
	},
	{
		'name': 'anseriformes',
		'rank': 'order',
		'parent': 'galloanserae',
		'range': 'ww',
	},
	{
		'name': 'anthozoa',
		'rank': 'class',
		'parent': 'cnidaria',
		'range': 'ww',
		'age': 570,
	},
	{
		'name': 'anura',
		'rank': 'order',
		'parent': 'amphibia',
		'range': 'ww',
		'desc': 'Frog',
	},
	{
		'name': 'apiaceae',
		'rank': 'family',
		'parent': 'apiales',
		'range': 'ww',
	},
	{
		'name': 'apiales',
		'rank': 'order',
		'parent': 'campanulids',
		'range': 'ww',
	},
	{
		'name': 'apidae',
		'rank': 'family',
		'parent': 'hymenoptera',
		'range': 'ww',
	},
	{
		'name': 'apis',
		'rank': 'genus',
		'parent': 'apidae',
		// 'important': true,
		'range': 'ea',
		'desc': 'Honey Bee',
	},
	{
		'name': 'apium',
		'rank': 'genus',
		'parent': 'apiaceae',
		'range': 'ww',
	},
	{
		'name': 'apium graveolens',
		'rank': 'species',
		'parent': 'apium',
		'desc': 'Celery',
	},
	{
		'name': 'arachis',
		'rank': 'genus',
		'parent': 'fabaceae',
		'range': 'sa',
	},
	{
		'name': 'arachis hypogaea',
		'rank': 'species',
		'parent': 'arachis',
		'range': 'sa',
		'desc': 'Peanut',
	},
	{
		'name': 'arachnida',
		'rank': 'class',
		'parent': 'arthropoda',
		'range': 'ww',
		'age': 430,
	},
	{
		'name': 'araneae',
		'rank': 'order',
		'parent': 'arachnida',
		'range': 'ww',
		'age': 319,
		'desc': 'Spider',
	},
	{
		'name': 'archaeopterygidae',
		'rank': 'family',
		'parent': 'avialae',
		'extinct': true,
		'range': 'eu',
	},
	{
		'name': 'archaeopteryx',
		'rank': 'genus',
		'parent': 'archaeopterygidae',
		'extinct': true,
		'range': 'eu',
	},
	{
		'name': 'archosauria',
		'rank': 'clade',
		'parent': 'sauria',
		'range': 'ww',
	},
	{
		'name': 'ardipithecus',
		'rank': 'genus',
		'parent': 'australopithecina',
		'extinct': true,
		'range': 'af',
	},
	{
		'name': 'ardipithecus ramidus',
		'rank': 'species',
		'parent': 'ardipithecus',
		'extinct': true,
		'range': 'af',
		'desc': 'Extinct hominid very close to Human-Chimpanzee LCA.',
	},
	{
		'name': 'arecaceae',
		'rank': 'family',
		'parent': 'arecales',
		'range': 'eq',
	},
	{
		'name': 'arecales',
		'rank': 'order',
		'parent': 'commelinids',
		'range': 'eq',
	},
	{
		'name': 'armadillidiidae',
		'rank': 'family',
		'parent': 'isopoda',
		'range': 'ow',
		'desc': 'Rolly Polly',
	},
	{
		'name': 'arthropoda',
		'rank': 'phylum',
		'parent': 'protostomia',
		'range': 'ww',
		'age': 540,
	},
	{
		'name': 'artiodactyla',
		'rank': 'order',
		'parent': 'ungulata',
		'range': 'ww',
	},
	{
		'name': 'artiofabula',
		'rank': 'clade',
		'parent': 'artiodactyla',
		'range': 'ww',
	},
	{
		'name': 'ascomycota',
		'rank': 'division',
		'parent': 'fungi',
		'range': 'ww',
	},
	{
		'name': 'asparagales',
		'rank': 'order',
		'parent': 'monocots',
		'range': 'ww',
	},
	{
		'name': 'astacoidea',
		'rank': 'superfamily',
		'parent': 'decapoda',
		'range': 'ww',
		'desc': 'Crayfish',
	},
	{
		'name': 'asteraceae',
		'rank': 'family',
		'parent': 'asterales',
		'range': 'ww',
	},
	{
		'name': 'asterales',
		'rank': 'order',
		'parent': 'campanulids',
		'range': 'ww',
	},
	{
		'name': 'asterids',
		'rank': 'clade',
		'parent': 'eudicots',
		'range': 'ww',
	},
	{
		'name': 'asteroidea',
		'rank': 'class',
		'parent': 'echinodermata',
		'range': 'ww',
		'desc': 'Starfish',
	},
	{
		'name': 'australopithecina',
		'rank': 'subtribe',
		'parent': 'hominini',
		'extinct': true,
		'range': 'af',
		'age': 5.6,
	},
	{
		'name': 'australopithecus',
		'rank': 'genus',
		'parent': 'australopithecina',
		'extinct': true,
		'range': 'af',
	},
	{
		'name': 'australopithecus afarensis',
		'rank': 'species',
		'parent': 'australopithecus',
		'extinct': true,
		'range': 'af',
		'desc': 'Ancestor of H. Habilis.',
	},
	{
		'name': 'aves',
		'rank': 'class',
		'parent': 'avialae',
		'range': 'ww',
		'desc': 'Bird',
	},
	{
		'name': 'avialae',
		'rank': 'clade',
		'parent': 'paraves',
		'range': 'ww',
	},
	// B
	{
		'name': 'bacillaceae',
		'rank': 'family',
		'parent': 'bacillales',
		'range': 'ww',
	},
	{
		'name': 'bacillales',
		'rank': 'order',
		'parent': 'bacilli',
		'range': 'ww',
	},
	{
		'name': 'bacilli',
		'rank': 'class',
		'parent': 'firmicutes',
		'range': 'ww',
	},
	{
		'name': 'bacillus',
		'rank': 'genus',
		'parent': 'bacillaceae',
		'range': 'ww',
	},
	{
		'name': 'bacillus anthracis',
		'rank': 'species',
		'parent': 'bacillus',
		'range': 'ww',
		'desc': 'Anthrax',
	},
	{
		'name': 'bacteria',
		'rank': 'domain',
		'parent': 'life',
		'range': 'ww',
		'age': 3800,
	},
	{
		'name': 'balaenoptera',
		'rank': 'genus',
		'parent': 'balaenopteridae',
		'range': 'ww',
	},
	{
		'name': 'balaenoptera musculus',
		'rank': 'species',
		'parent': 'balaenoptera',
		'range': 'ww',
		'desc': 'Blue Whale',
	},
	{
		'name': 'balaenopteridae',
		'rank': 'family',
		'parent': 'cetacea',
		'range': 'ww',
	},
	{
		'name': 'bambusoideae',
		'rank': 'subfamily',
		'parent': 'bop clade',
		'range': 'eq',
		'desc': 'Bamboo',
	},
	{
		'name': 'bangiaceae',
		'rank': 'family',
		'parent': 'bangiales',
		'range': 'ww',
	},
	{
		'name': 'bangiales',
		'rank': 'order',
		'parent': 'bangiophyceae',
		'range': 'ww',
	},
	{
		'name': 'bangiophyceae',
		'rank': 'class',
		'parent': 'rhodophyta',
		'range': 'ww',
	},
	{
		'name': 'batoidea',
		'rank': 'superorder',
		'parent': 'chondrichthyes',
		'range': 'ww',
		'desc': 'Ray',
	},
	{
		'name': 'betula',
		'rank': 'genus',
		'parent': 'betulaceae',
		'range': 'nh',
		'desc': 'Birch',
	},
	{
		'name': 'betulaceae',
		'rank': 'family',
		'parent': 'fagales',
		'range': 'ww',
	},
	{
		'name': 'bilateria',
		'rank': 'clade',
		'parent': 'parahoxozoa',
		'range': 'ww',
		'age': 560,
		'desc': 'Bilaterians are animals with bilateral symmetry as an embryo.',
	},
	{
		'name': 'bop clade',
		'rank': 'clade',
		'range': 'ww',
		'parent': 'poaceae',
	},
	{
		'name': 'bos',
		'rank': 'genus',
		'range': 'ww',
		'parent': 'bovidae',
	},
	{
		'name': 'bos grunniens',
		'rank': 'species',
		'parent': 'bos',
		'range': 'as',
		'desc': 'Yak',
	},
	{
		'name': 'bos taurus',
		'rank': 'species',
		'parent': 'bos',
		'range': 'ww',
		'desc': 'Cattle',
	},
	{
		'name': 'bovidae',
		'rank': 'family',
		'parent': 'cetruminantia',
		'range': 'ww',
	},
	{
		'name': 'brachiosauridae',
		'rank': 'family',
		'parent': 'saurischia',
		'extinct': true,
		'range': 'ww',
	},
	{
		'name': 'brachiosaurus',
		'rank': 'genus',
		'parent': 'brachiosauridae',
		'extinct': true,
		'range': 'na',
	},
	{
		'name': 'brachyura',
		'rank': 'infraorder',
		'parent': 'decapoda',
		'range': 'ww',
		'desc': 'Crab',
	},
	{
		'name': 'brassica',
		'rank': 'genus',
		'range': 'ww',
		'parent': 'brassicaceae',
	},
	{
		'name': 'brassica oleracea',
		'rank': 'species',
		'parent': 'brassica',
		'range': 'eu',
		'desc': 'Broccoli, Brussel Sprout, Cabbage, Cauliflower, Collard Greens, Kale, among others',
	},
	{
		'name': 'brassica rapa',
		'rank': 'species',
		'parent': 'brassica',
		'range': 'ea',
		'desc': 'Turnip',
	},
	{
		'name': 'brassicaceae',
		'rank': 'family',
		'parent': 'brassicales',
		'range': 'ww',
	},
	{
		'name': 'brassicales',
		'rank': 'order',
		'parent': 'malvids',
		'range': 'ww',
	},
	{
		'name': 'bromeliaceae',
		'rank': 'family',
		'parent': 'poales',
		'range': 'nw',
	},
	// C
	{
		'name': 'camelidae',
		'rank': 'family',
		'parent': 'tylopoda',
		'range': 'ww',
	},
	{
		'name': 'campanulids',
		'rank': 'clade',
		'parent': 'asterids',
		'range': 'ww',
	},
	{
		'name': 'canidae',
		'rank': 'family',
		'range': 'ww',
		'age': 39.75,
		'parent': 'carnivora',
	},
	{
		'name': 'canis',
		'rank': 'genus',
		'parent': 'canidae',
		'range': 'ww',
	},
	{
		'name': 'canis lupus',
		'rank': 'species',
		'parent': 'canis',
		'range': 'nh',
		'desc': 'Wolf',
	},
	{
		'name': 'canis lupus familiaris',
		'rank': 'subspecies',
		'parent': 'canis lupus',
		// 'important': true,
		'desc': 'Dog',
	},
	{
		'name': 'capra',
		'rank': 'genus',
		'parent': 'caprinae',
		'range': 'ow',
		'desc': 'Goat',
	},
	{
		'name': 'caprinae',
		'rank': 'subfamily',
		'parent': 'bovidae',
		'range': 'nh',
	},
	{
		'name': 'capsicum',
		'rank': 'genus',
		'parent': 'solanaceae',
		'range': 'nw',
	},
	{
		'name': 'capsicum annuum',
		'rank': 'species',
		'parent': 'capsicum',
		'range': 'nw',
		'desc': 'Peppers, incl. Bell and Jalape&ntilde;os',
	},
	{
		'name': 'carcharhiniformes',
		'rank': 'order',
		'parent': 'selachimorpha',
		'range': 'ww',
		'desc': 'Ground Shark',
	},
	{
		'name': 'cardinalidae',
		'rank': 'family',
		'parent': 'passeriformes',
		'range': 'nw',
	},
	{
		'name': 'cardinalis',
		'rank': 'genus',
		'parent': 'cardinalidae',
		'range': 'nw',
	},
	{
		'name': 'cardinalis cardinalis',
		'rank': 'species',
		'parent': 'cardinalis',
		'range': 'na',
		'desc': 'Cardinal',
	},
	{
		'name': 'caridea',
		'rank': 'infraorder',
		'parent': 'decapoda',
		'range': 'ww',
		'desc': 'Shrimp',
	},
	{
		'name': 'carnivora',
		'rank': 'order',
		'parent': 'ferae',
		'range': 'ww',
		'age': 42,
	},
	{
		'name': 'carya',
		'rank': 'genus',
		'parent': 'juglandaceae',
		'range': 'nh',
	},
	{
		'name': 'carya illinoinensis',
		'rank': 'species',
		'parent': 'carya',
		'range': 'na',
		'desc': 'Pecan',
	},
	{
		'name': 'castor',
		'rank': 'genus',
		'parent': 'castoridae',
		'range': 'nh',
		'desc': 'Beaver',
	},
	{
		'name': 'castoridae',
		'rank': 'family',
		'parent': 'rodentia',
		'range': 'nh',
	},
	{
		'name': 'cavia',
		'rank': 'genus',
		'parent': 'caviidae',
		'range': 'sa',
	},
	{
		'name': 'cavia porcellus',
		'rank': 'species',
		'parent': 'cavia',
		'range': 'sa',
		'desc': 'Guinea Pig',
	},
	{
		'name': 'caviidae',
		'rank': 'family',
		'parent': 'rodentia',
		'range': 'sa',
	},
	{
		'name': 'cedrus',
		'rank': 'genus',
		'parent': 'abietoideae',
		'range': 'ea',
		'desc': 'Cedar',
	},
	{
		'name': 'cephalopoda',
		'rank': 'class',
		'parent': 'mollusca',
		'range': 'ww',
		'age': 500,
	},
	{
		'name': 'cerasus',
		'rank': 'subgenus',
		'parent': 'prunus',
		'range': 'ea',
		'desc': 'Cherry',
	},
	{
		'name': 'ceratopsidae',
		'rank': 'family',
		'parent': 'ornithischia',
		'extinct': true,
		'range': 'na',
	},
	{
		'name': 'cervidae',
		'rank': 'family',
		'parent': 'cetruminantia',
		'range': 'ww',
		'desc': 'Deer',
	},
	{
		'name': 'cetacea',
		'rank': 'infraorder',
		'parent': 'cetruminantia',
		'range': 'ww',
	},
	{
		'name': 'cetruminantia',
		'rank': 'clade',
		'parent': 'artiofabula',
		'range': 'ww',
	},
	{
		'name': 'chondrichthyes',
		'rank': 'class',
		'parent': 'chordata',
		'range': 'ww',
		'age': 430,
	},
	{
		'name': 'chordata',
		'rank': 'phylum',
		'parent': 'deuterostomia',
		'range': 'ww',
		'age': 535,
		'desc': 'During some period of their life cycle, chordates possess a notochord, a dorsal nerve cord, pharyngeal slits, an endostyle, and a post-anal tail. These five anatomical features define this phylum.',
	},
	{
		'name': 'chromista',
		'rank': 'kingdom',
		'parent': 'diaphoretickes',
		'range': 'ww',
	},
	{
		'name': 'cinnamomum',
		'rank': 'genus',
		'parent': 'lauraceae',
		'range': 'as',
		'desc': 'Cinnamon',
	},
	{
		'name': 'citrullus',
		'rank': 'genus',
		'parent': 'cucurbitaceae',
		'range': 'ow',
	},
	{
		'name': 'citrullus lanatus',
		'rank': 'species',
		'parent': 'citrullus',
		'range': 'af',
		'desc': 'Watermelon',
	},
	{
		'name': 'citrus',
		'rank': 'genus',
		'parent': 'rutaceae',
		'range': 'as',
	},
	{
		'name': 'citrus latifola',
		'rank': 'species',
		'parent': 'citrus',
		'range': 'as',
		'desc': 'Persian Lime',
	},
	{
		'name': 'citrus limon',
		'rank': 'species',
		'parent': 'citrus',
		'range': 'as',
		'desc': 'Lemon',
	},
	{
		'name': 'citrus paradisi',
		'rank': 'species',
		'parent': 'citrus',
		'desc': 'Grapefruit',
	},
	{
		'name': 'citrus sinensis',
		'rank': 'species',
		'parent': 'citrus',
		'range': 'as',
		'desc': 'Orange',
	},
	{
		'name': 'citrus tangerina',
		'rank': 'species',
		'parent': 'citrus',
		'desc': 'Tangerine',
	},
	{
		'name': 'cnidaria',
		'rank': 'phylum',
		'parent': 'parahoxozoa',
		'range': 'ww',
		'age': 580,
	},
	{
		'name': 'coccinellidae',
		'rank': 'family',
		'parent': 'coleoptera',
		'range': 'ww',
		'desc': 'Ladybug',
	},
	{
		'name': 'cocos',
		'rank': 'genus',
		'parent': 'arecaceae',
		'range': 'eq',
	},
	{
		'name': 'cocos nucifera',
		'rank': 'species',
		'parent': 'cocos',
		'range': 'eq',
		'desc': 'Coconut',
	},
	{
		'name': 'coleoptera',
		'rank': 'order',
		'parent': 'insecta',
		'range': 'ww',
		'desc': 'Beetle',
	},
	{
		'name': 'columbiformes',
		'rank': 'order',
		'parent': 'neoaves',
		'range': 'ww',
		'desc': 'Pigeon',
	},
	{
		'name': 'commelinids',
		'rank': 'clade',
		'parent': 'monocots',
		'range': 'ww',
	},
	{
		'name': 'corvidae',
		'rank': 'family',
		'parent': 'passeriformes',
		'range': 'ww',
	},
	{
		'name': 'corvus',
		'rank': 'genus',
		'parent': 'corvidae',
		'range': 'nh',
		'desc': 'Crow',
	},
	{
		'name': 'cricetidae',
		'rank': 'family',
		'parent': 'muroidea',
		'range': 'ww',
	},
	{
		'name': 'cricetinae',
		'rank': 'subfamily',
		'parent': 'cricetidae',
		'range': 'ea',
		'desc': 'Hamster',
	},
	{
		'name': 'crustacea',
		'rank': 'subphylum',
		'parent': 'pancrustacea',
		'range': 'ww',
		'age': 511,
	},
	{
		'name': 'ctenophora',
		'rank': 'phylum',
		'parent': 'eumetazoa',
		'range': 'ww',
		'age': 540,
		'desc': 'Comb Jellies',
	},
	{
		'name': 'cucumis',
		'rank': 'genus',
		'parent': 'cucurbitaceae',
		'range': 'ow',
	},
	{
		'name': 'cucumis sativus',
		'rank': 'species',
		'parent': 'cucumis',
		'range': 'as',
		'desc': 'Cucumber',
	},
	{
		'name': 'cucurbita',
		'rank': 'genus',
		'parent': 'cucurbitaceae',
		'range': 'nw',
	},
	{
		'name': 'cucurbita pepo',
		'rank': 'species',
		'parent': 'cucurbita',
		'range': 'nw',
		'desc': 'Pumpkin, Winter Squash',
	},
	{
		'name': 'cucurbitaceae',
		'rank': 'family',
		'parent': 'cucurbitales',
		'range': 'ww',
	},
	{
		'name': 'cucurbitales',
		'rank': 'order',
		'parent': 'fabids',
		'range': 'ww',
	},
	{
		'name': 'cuminum',
		'rank': 'genus',
		'parent': 'apiaceae',
		'range': 'as',
	},
	{
		'name': 'cuminum cyminum',
		'rank': 'species',
		'parent': 'cuminum',
		'range': 'as',
		'desc': 'Cumin',
	},
	{
		'name': 'curcuma',
		'rank': 'genus',
		'parent': 'zingiberaceae',
		'range': 'as',
	},
	{
		'name': 'curcuma longa',
		'rank': 'species',
		'parent': 'curcuma',
		'range': 'as',
		'desc': 'Turmeric',
	},
	{
		'name': 'cyanobacteria',
		'rank': 'phylum',
		'parent': 'terrabacteria',
		'range': 'ww',
		'age': 2100,
	},
	{
		'name': 'cyanocitta',
		'rank': 'genus',
		'parent': 'corvidae',
		'range': 'na',
	},
	{
		'name': 'cyanocitta crisata',
		'rank': 'species',
		'parent': 'cyanocitta',
		'range': 'na',
		'desc': 'Blue Jay',
	},
	{
		'name': 'cygnus',
		'rank': 'genus',
		'parent': 'anatidae',
		'range': 'ww',
		'desc': 'Swan',
	},
	{
		'name': 'daucus',
		'rank': 'genus',
		'parent': 'apiaceae',
		'range': 'ww',
	},
	{
		'name': 'daucus carota',
		'rank': 'species',
		'range': 'ea',
		'parent': 'daucus',
	},
	{
		'name': 'daucus carota sativus',
		'rank': 'subspecies',
		'parent': 'daucus carota',
		'range': 'ea',
		'desc': 'Carrot',
	},
	{
		'name': 'decapoda',
		'rank': 'order',
		'parent': 'malacostraca',
		'range': 'ww',
	},
	{
		'name': 'deinonychus',
		'rank': 'genus',
		'parent': 'dromaeosauridae',
		'extinct': true,
		'range': 'na',
	},
	{
		'name': 'delphinidae',
		'rank': 'family',
		'parent': 'cetacea',
		'range': 'ww',
	},
	{
		'name': 'deuterostomia',
		'rank': 'superphylum',
		'parent': 'bilateria',
		'range': 'ww',
		'age': 540,
		'desc': 'In deuterostomes, the first opening, the blastopore, becomes the anus, while in protostomes, it becomes the mouth.',
	},
	{
		'name': 'diaphoretickes',
		'rank': 'clade',
		'parent': 'eukaryota',
		'range': 'ww',
	},
	{
		'name': 'diplodocidae',
		'rank': 'family',
		'parent': 'saurischia',
		'extinct': true,
		'range': 'ww',
	},
	{
		'name': 'diplodocus',
		'rank': 'genus',
		'parent': 'diplodocidae',
		'extinct': true,
		'range': 'na',
	},
	{
		'name': 'dromaeosauridae',
		'rank': 'family',
		'parent': 'paraves',
		'extinct': true,
		'range': 'ww',
	},
	// E
	{
		'name': 'echinodermata',
		'rank': 'phylum',
		'parent': 'deuterostomia',
		'range': 'ww',
		'age': 540,
	},
	{
		'name': 'enterobacteriaceae',
		'rank': 'family',
		'parent': 'enterobacteriales',
		'range': 'ww',
	},
	{
		'name': 'enterobacteriales',
		'rank': 'order',
		'parent': 'gammaproteobacteria',
		'range': 'ww',
	},
	{
		'name': 'equidae',
		'rank': 'family',
		'range': 'ow',
		'parent': 'perissodactyla',
	},
	{
		'name': 'equus',
		'rank': 'genus',
		'range': 'ow',
		'parent': 'equidae',
	},
	{
		'name': 'equus africanus',
		'rank': 'species',
		'range': 'af',
		'parent': 'equus',
	},
	{
		'name': 'equus africanus asinus',
		'rank': 'subspecies',
		'parent': 'equus africanus',
		'range': 'af',
		'desc': 'Donkey',
	},
	{
		'name': 'equus ferus',
		'rank': 'species',
		'range': 'ea',
		'parent': 'equus',
	},
	{
		'name': 'equus ferus caballus',
		'rank': 'subspecies',
		'parent': 'equus ferus',
		'range': 'ea',
		'desc': 'Horse',
	},
	{
		'name': 'erinaceidae',
		'rank': 'family',
		'parent': 'eulipotyphla',
		'range': 'ow',
	},
	{
		'name': 'erinaceinae',
		'rank': 'subfamily',
		'parent': 'erinaceidae',
		'range': 'ow',
		'desc': 'Hedgehog',
	},
	{
		'name': 'escherichia',
		'rank': 'genus',
		'parent': 'enterobacteriaceae',
		'range': 'ww',
	},
	{
		'name': 'escherichia coli',
		'rank': 'species',
		'parent': 'escherichia',
		'range': 'ww',
		'desc': 'E. Coli',
	},
	{
		'name': 'euarchontoglires',
		'rank': 'superorder',
		'parent': 'mammalia',
		'range': 'ww',
		'age': 65,
	},
	{
		'name': 'eudicots',
		'rank': 'clade',
		'parent': 'angiosperms',
		'range': 'ww',
	},
	{
		'name': 'eukaryota',
		'rank': 'domain',
		'parent': 'life',
		'range': 'ww',
		'age': 1850,
		'desc': 'Eukaryotes are organisms which have cells with a nucleus enclosed within membranes, unlike prokaryotes, which have no membrane-bound organelles.',
	},
	{
		'name': 'eulipotyphla',
		'rank': 'order',
		'parent': 'laurasiatheria',
		'range': 'ww',
	},
	{
		'name': 'eumetazoa',
		'rank': 'subkingdom',
		'parent': 'animalia',
		'range': 'ww',
		'age': 635,
		'desc': 'Characteristics of eumetazoans include true tissues organized into germ layers, neurons, and an embryo that goes through a gastrula stage.',
	},
	{
		'name': 'euphausiacea',
		'rank': 'order',
		'parent': 'malacostraca',
		'range': 'ww',
		'desc': 'Krill',
	},
	{
		'name': 'eurotiales',
		'rank': 'order',
		'parent': 'eurotiomycetes',
		'range': 'ww',
	},
	{
		'name': 'eurotiomycetes',
		'rank': 'class',
		'parent': 'ascomycota',
		'range': 'ww',
	},
	// F
	{
		'name': 'fabaceae',
		'rank': 'family',
		'parent': 'fabales',
		'range': 'ww',
	},
	{
		'name': 'fabales',
		'rank': 'order',
		'parent': 'fabids',
		'range': 'ww',
	},
	{
		'name': 'fabids',
		'rank': 'clade',
		'parent': 'rosids',
		'range': 'ww',
	},
	{
		'name': 'fagaceae',
		'rank': 'family',
		'parent': 'fagales',
		'range': 'nh',
	},
	{
		'name': 'fagales',
		'rank': 'order',
		'parent': 'fabids',
		'range': 'ww',
	},
	{
		'name': 'fagus',
		'rank': 'genus',
		'parent': 'fagaceae',
		'range': 'nh',
		'desc': 'Beech',
	},
	{
		'name': 'felidae',
		'rank': 'family',
		'range': 'ww',
		'age': 25,
		'parent': 'feliformia',
	},
	{
		'name': 'feliformia',
		'rank': 'suborder',
		'range': 'ww',
		'age': 40,
		'parent': 'carnivora',
	},
	{
		'name': 'felis',
		'rank': 'genus',
		'range': 'ow',
		'age': 6.2,
		'parent': 'felidae',
	},
	{
		'name': 'felis catus',
		'rank': 'species',
		'parent': 'felis',
		// 'important': true,
		'range': 'af',
		'desc': 'Cat',
	},
	{
		'name': 'ferae',
		'rank': 'clade',
		'parent': 'laurasiatheria',
		'range': 'ww',
		'age': 78.9,
	},
	{
		'name': 'firmicutes',
		'rank': 'phylum',
		'parent': 'terrabacteria',
		'range': 'ww',
	},
	{
		'name': 'formicidae',
		'rank': 'family',
		'parent': 'hymenoptera',
		'range': 'ww',
		'desc': 'Ant',
	},
	{
		'name': 'fungi',
		'rank': 'kingdom',
		'parent': 'opisthokonta',
		'range': 'ww',
		'age': 410,
	},
	// G
	{
		'name': 'gadidae',
		'rank': 'family',
		'parent': 'gadiformes',
		'range': 'ww',
	},
	{
		'name': 'gadiformes',
		'rank': 'order',
		'parent': 'acanthomorpha',
		'range': 'ww',
	},
	{
		'name': 'gadus',
		'rank': 'genus',
		'parent': 'gadidae',
		'range': 'nh',
		'desc': 'Cod',
	},
	{
		'name': 'galliformes',
		'rank': 'order',
		'parent': 'galloanserae',
		'range': 'ww',
	},
	{
		'name': 'galloanserae',
		'rank': 'superorder',
		'parent': 'aves',
		'range': 'ww',
		'desc': 'Fowl',
	},
	{
		'name': 'gallus',
		'rank': 'genus',
		'range': 'as',
		'parent': 'phasianinae',
	},
	{
		'name': 'gallus gallus',
		'rank': 'species',
		'parent': 'gallus',
		'range': 'as',
		'desc': 'Red Junglefowl',
	},
	{
		'name': 'gallus gallus domesticus',
		'rank': 'subspecies',
		'parent': 'gallus gallus',
		'range': 'as',
		'desc': 'Chicken',
	},
	{
		'name': 'gammaproteobacteria',
		'rank': 'class',
		'parent': 'proteobacteria',
		'range': 'ww',
	},
	{
		'name': 'glires',
		'rank': 'clade',
		'parent': 'euarchontoglires',
		'range': 'ww',
		'age': 60,
	},
	{
		'name': 'gorilla',
		'rank': 'genus',
		'parent': 'homininae',
		'range': 'af',
		'desc': 'Gorilla',
	},
	{
		'name': 'gossypium',
		'rank': 'genus',
		'parent': 'malvaceae',
		'range': 'eq',
		'desc': 'Cotton',
	},
	{
		'name': 'gracilicutes',
		'rank': 'clade',
		'parent': 'bacteria',
		'range': 'ww',
	},
	// H
	{
		'name': 'hexapoda',
		'rank': 'subphylum',
		'parent': 'pancrustacea',
		'range': 'ww',
		'age': 411,
	},
	{
		'name': 'hippotigris',
		'rank': 'subgenus',
		'parent': 'equus',
		'range': 'af',
		'desc': 'Zebra',
	},
	{
		'name': 'hominidae',
		'rank': 'family',
		'parent': 'hominoidea',
		'range': 'ow',
		'age': 15.7,
		'desc': 'Great Apes',
	},
	{
		'name': 'homininae',
		'rank': 'subfamily',
		'parent': 'hominidae',
		'range': 'af',
		'age': 8.8,
		'desc': 'African Apes',
	},
	{
		'name': 'hominini',
		'rank': 'tribe',
		'parent': 'homininae',
		'range': 'af',
		'age': 6.3,
	},
	{
		'name': 'hominoidea',
		'rank': 'superfamily',
		'parent': 'primates',
		'range': 'ow',
		'age': 20.4,
		'desc': 'Ape',
	},
	{
		'name': 'homo',
		'rank': 'genus',
		'range': 'af',
		'parent': 'hominini',
		'age': 2.8,
	},
	{
		'name': 'homo erectus',
		'rank': 'species',
		'parent': 'homo',
		'extinct': true,
		'range': 'ow',
		'age': 2,
		'desc': 'Ancestor of H. Heidelbergensis, descended from H. Habilis.',
	},
	{
		'name': 'homo habilis',
		'rank': 'species',
		'parent': 'homo',
		'extinct': true,
		'range': 'af',
		'age': 2.3,
		'desc': 'Ancestor of H. Erectus, descended from A. Afarensis.',
	},
	{
		'name': 'homo heidelbergensis',
		'rank': 'species',
		'parent': 'homo',
		'extinct': true,
		'range': 'ow',
		'age': 0.7,
		'desc': 'Ancestor of H. Sapiens, descended from H. Erectus.',
	},
	{
		'name': 'homo sapiens',
		'rank': 'species',
		'parent': 'homo',
		'important': true,
		'range': 'af',
		'age': 0.35,
		'desc': 'Human',
	},
	{
		'name': 'hyaenidae',
		'rank': 'family',
		'parent': 'feliformia',
		'range': 'ow',
		'age': 26,
		'desc': 'Hyena',
	},
	{
		'name': 'hylobatidae',
		'rank': 'family',
		'parent': 'hominoidea',
		'range': 'as',
		'age': 8,
		'desc': 'Gibbon',
	},
	{
		'name': 'hymenoptera',
		'rank': 'order',
		'parent': 'insecta',
		'range': 'ww',
	},
	{
		'name': 'hyracodontidae',
		'rank': 'family',
		'parent': 'perissodactyla',
		'extinct': true,
		'range': 'nh',
	},
	// I
	{
		'name': 'ichthyosauria',
		'rank': 'order',
		'parent': 'reptilia',
		'extinct': true,
		'range': 'ww',
		'desc': 'Ichthyosaur',
	},
	{
		'name': 'iguanodon',
		'rank': 'genus',
		'parent': 'iguanodontidae',
		'extinct': true,
		'range': 'eu',
	},
	{
		'name': 'iguanodontidae',
		'rank': 'family',
		'parent': 'ornithischia',
		'extinct': true,
		'range': 'ow',
	},
	{
		'name': 'insecta',
		'rank': 'class',
		'parent': 'hexapoda',
		'range': 'ww',
		'age': 396,
		'desc': 'Insects have a chitinous exoskeleton, a three-part body (head, thorax and abdomen), three pairs of jointed legs, compound eyes, and one pair of antennae.',
	},
	{
		'name': 'isopoda',
		'rank': 'order',
		'parent': 'malacostraca',
		'range': 'ww',
	},
	// J
	{
		'name': 'juglandaceae',
		'rank': 'family',
		'parent': 'fagales',
		'range': 'ww',
	},
	{
		'name': 'juglans',
		'rank': 'genus',
		'parent': 'juglandaceae',
		'range': 'ww',
		'desc': 'Walnut',
	},
	// L
	{
		'name': 'lactuca',
		'rank': 'genus',
		'parent': 'asteraceae',
		'range': 'ww',
	},
	{
		'name': 'lactuca sativa',
		'rank': 'species',
		'parent': 'lactuca',
		'range': 'ow',
		'desc': 'Lettuce',
	},
	{
		'name': 'lagomorpha',
		'rank': 'order',
		'parent': 'glires',
		'range': 'ww',
	},
	{
		'name': 'lama',
		'rank': 'genus',
		'parent': 'camelidae',
		'range': 'sa',
	},
	{
		'name': 'lama glama',
		'rank': 'species',
		'parent': 'lama',
		'range': 'sa',
		'desc': 'Llama',
	},
	{
		'name': 'lamiaceae',
		'rank': 'family',
		'parent': 'lamiales',
		'range': 'ww',
	},
	{
		'name': 'lamiales',
		'rank': 'order',
		'parent': 'lamiids',
		'range': 'ww',
	},
	{
		'name': 'lamiids',
		'rank': 'clade',
		'parent': 'asterids',
		'range': 'ww',
	},
	{
		'name': 'laminariales',
		'rank': 'order',
		'parent': 'phaeophyceae',
		'range': 'ww',
		'age': 45,
		'desc': 'Kelp',
	},
	{
		'name': 'lauraceae',
		'rank': 'family',
		'parent': 'laurales',
		'range': 'ww',
	},
	{
		'name': 'laurales',
		'rank': 'order',
		'parent': 'magnoliids',
		'range': 'ww',
	},
	{
		'name': 'laurasiatheria',
		'rank': 'superorder',
		'parent': 'mammalia',
		'range': 'ww',
		'age': 91,
	},
	{
		'name': 'laurus',
		'rank': 'genus',
		'parent': 'lauraceae',
		'range': 'ow',
	},
	{
		'name': 'laurus nobilis',
		'rank': 'species',
		'parent': 'laurus',
		'range': 'ow',
		'desc': 'Bay Laurel',
	},
	{
		'name': 'lepidoptera',
		'rank': 'order',
		'parent': 'insecta',
		'range': 'ww',
	},
	{
		'name': 'leporidae',
		'rank': 'family',
		'parent': 'lagomorpha',
		'range': 'ww',
		'desc': 'Rabbit, Hare',
	},
	{
		'name': 'life',
		'rank': 'life',
		'parent': '*',
		'range': 'ww',
		'age': 4280,
	},
	// M
	{
		'name': 'magnoliales',
		'rank': 'order',
		'parent': 'magnoliids',
		'range': 'ww',
	},
	{
		'name': 'magnoliids',
		'rank': 'clade',
		'parent': 'angiosperms',
		'range': 'ww',
	},
	{
		'name': 'malacostraca',
		'rank': 'class',
		'parent': 'crustacea',
		'range': 'ww',
	},
	{
		'name': 'malus',
		'rank': 'genus',
		'parent': 'rosaceae',
		'range': 'nh',
	},
	{
		'name': 'malus domestica',
		'rank': 'species',
		'parent': 'malus',
		'range': 'as',
		// 'important': true,
		'desc': 'Apple',
	},
	{
		'name': 'malvaceae',
		'rank': 'family',
		'parent': 'malvales',
		'range': 'eq',
		'desc': 'Mallow',
	},
	{
		'name': 'malvales',
		'rank': 'order',
		'parent': 'malvids',
		'range': 'eq',
	},
	{
		'name': 'malvids',
		'rank': 'clade',
		'parent': 'rosids',
		'range': 'ww',
	},
	{
		'name': 'mammalia',
		'rank': 'class',
		'parent': 'amniota',
		'range': 'ww',
		'age': 225,
		'desc': 'Mammals are characterized by the presence of mammary glands, a neocortex, fur or hair, and three middle ear bones.',
	},
	{
		'name': 'medusozoa',
		'rank': 'subphylum',
		'parent': 'cnidaria',
		'range': 'ww',
		'age': 540,
		'desc': 'Jellyfish',
	},
	{
		'name': 'mollusca',
		'rank': 'phylum',
		'parent': 'protostomia',
		'range': 'ww',
		'age': 555,
		'desc': 'Mollusk',
	},
	{
		'name': 'monocots',
		'rank': 'clade',
		'parent': 'angiosperms',
		'range': 'ww',
	},
	{
		'name': 'mosasauroidea',
		'rank': 'superfamily',
		'parent': 'squamata',
		'extinct': true,
		'range': 'ww',
		'desc': 'Mosasaur',
	},
	{
		'name': 'muridae',
		'rank': 'family',
		'parent': 'muroidea',
	},
	{
		'name': 'muroidea',
		'rank': 'superfamily',
		'parent': 'rodentia',
		'range': 'ww',
	},
	{
		'name': 'mus',
		'rank': 'genus',
		'parent': 'muridae',
		'range': 'ow',
	},
	{
		'name': 'mus musculus',
		'rank': 'species',
		'parent': 'mus',
		'range': 'ow',
		'desc': 'House Mouse',
	},
	{
		'name': 'musa',
		'rank': 'genus',
		'parent': 'musaceae',
		'range': 'as',
		'desc': 'Banana',
	},
	{
		'name': 'musaceae',
		'rank': 'family',
		'parent': 'zingiberales',
		'range': 'ow',
	},
	{
		'name': 'mycobacteriaceae',
		'rank': 'family',
		'parent': 'actinomycetales',
		'range': 'ww',
	},
	{
		'name': 'mycobacterium',
		'rank': 'genus',
		'parent': 'mycobacteriaceae',
		'range': 'ww',
	},
	{
		'name': 'mycobacterium tuberculosis',
		'rank': 'species',
		'parent': 'mycobacterium',
		'range': 'ww',
		'desc': 'Tuberculosis',
	},
	{
		'name': 'myristica',
		'rank': 'genus',
		'parent': 'myristicaceae',
		'range': 'as',
	},
	{
		'name': 'myristica fragrans',
		'rank': 'species',
		'parent': 'myristica',
		'range': 'as',
		'desc': 'Nutmeg',
	},
	{
		'name': 'myristicaceae',
		'rank': 'family',
		'parent': 'magnoliales',
		'range': 'ww',
	},
	// N
	{
		'name': 'neoaves',
		'rank': 'clade',
		'parent': 'aves',
		'range': 'ww',
	},
	{
		'name': 'nephropidae',
		'rank': 'family',
		'parent': 'decapoda',
		'range': 'ww',
		'desc': 'Lobster',
	},
	// O
	{
		'name': 'ochrophyta',
		'rank': 'phylum',
		'parent': 'chromista',
		'range': 'ww',
	},
	{
		'name': 'ocimum',
		'rank': 'genus',
		'parent': 'lamiaceae',
		'range': 'ww',
	},
	{
		'name': 'ocimum basilicum',
		'rank': 'species',
		'parent': 'ocimum',
		'range': 'ow',
		'desc': 'Basil',
	},
	{
		'name': 'opisthokonta',
		'rank': 'clade',
		'parent': 'eukaryota',
		'range': 'ww',
		'age': 1010,
		'desc': 'In opisthokonts, flagellate cells propel themselves with a single posterior flagellum.',
	},
	{
		'name': 'orchidaceae',
		'rank': 'family',
		'parent': 'asparagales',
		'range': 'ww',
	},
	{
		'name': 'origanum',
		'rank': 'genus',
		'parent': 'lamiaceae',
		'range': 'ow',
	},
	{
		'name': 'origanum vulgare',
		'rank': 'species',
		'parent': 'origanum',
		'range': 'ea',
		'desc': 'Oregano',
	},
	{
		'name': 'ornithischia',
		'rank': 'order',
		'parent': 'archosauria',
		'extinct': true,
		'range': 'ww',
	},
	{
		'name': 'oryza',
		'rank': 'genus',
		'parent': 'bop clade',
		'range': 'ww',
	},
	{
		'name': 'oryza sativa',
		'rank': 'species',
		'parent': 'oryza',
		'range': 'as',
		'desc': 'Asian Rice',
	},
	{
		'name': 'osteichthyes',
		'rank': 'superclass',
		'parent': 'chordata',
		'range': 'ww',
		'age': 420,
		'desc': 'Bony Fish',
	},
	{
		'name': 'ovis',
		'rank': 'genus',
		'parent': 'caprinae',
		'range': 'nh',
	},
	{
		'name': 'ovis aries',
		'rank': 'species',
		'parent': 'ovis',
		'range': 'ea',
		'desc': 'Sheep',
	},
	// P
	{
		'name': 'pacmad clade',
		'rank': 'clade',
		'range': 'ww',
		'parent': 'poaceae',
	},
	{
		'name': 'pan',
		'rank': 'genus',
		'range': 'af',
		'age': 4,
		'parent': 'hominini',
	},
	{
		'name': 'pan troglodytes',
		'rank': 'species',
		'parent': 'pan',
		'range': 'af',
		'desc': 'Chimpanzee',
	},
	{
		'name': 'pancrustacea',
		'rank': 'clade',
		'parent': 'arthropoda',
		'range': 'ww',
	},
	{
		'name': 'panicoideae',
		'rank': 'subfamily',
		'parent': 'pacmad clade',
		'range': 'ww',
	},
	{
		'name': 'panthera',
		'rank': 'genus',
		'parent': 'felidae',
		'range': 'ww',
		'age': 5.95,
	},
	{
		'name': 'panthera leo',
		'rank': 'species',
		'parent': 'panthera',
		'range': 'ow',
		'desc': 'Lion',
	},
	{
		'name': 'panthera onca',
		'rank': 'species',
		'parent': 'panthera',
		'range': 'nw',
		'desc': 'Jaguar',
	},
	{
		'name': 'panthera pardus',
		'rank': 'species',
		'parent': 'panthera',
		'range': 'ow',
		'desc': 'Leopard',
	},
	{
		'name': 'panthera tigris',
		'rank': 'species',
		'parent': 'panthera',
		'range': 'as',
		'desc': 'Tiger',
	},
	{
		'name': 'panthera uncia',
		'rank': 'species',
		'parent': 'panthera',
		'range': 'as',
		'desc': 'Snow Leopard',
	},
	{
		'name': 'paraceratherium',
		'rank': 'genus',
		'parent': 'hyracodontidae',
		'extinct': true,
		'range': 'ea',
	},
	{
		'name': 'parahoxozoa',
		'rank': 'clade',
		'parent': 'eumetazoa',
		'range': 'ww',
		'age': 605.2,
	},
	{
		'name': 'paraves',
		'rank': 'clade',
		'parent': 'theropoda',
		'range': 'ww',
	},
	{
		'name': 'paridae',
		'rank': 'family',
		'parent': 'passeriformes',
		'range': 'ww',
		'desc': 'Tit',
	},
	{
		'name': 'passeriformes',
		'rank': 'order',
		'parent': 'psittacopasserae',
		'range': 'ww',
	},
	{
		'name': 'pavo',
		'rank': 'genus',
		'parent': 'phasianinae',
		'range': 'as',
		'desc': 'Peafowl',
	},
	{
		'name': 'penicillum',
		'rank': 'genus',
		'parent': 'trichocomaceae',
		'range': 'ww',
	},
	{
		'name': 'pennatulacea',
		'rank': 'order',
		'parent': 'anthozoa',
		'range': 'ww',
		'age': 540,
		'desc': 'Sea Pen',
	},
	{
		'name': 'percomorpha',
		'rank': 'clade',
		'parent': 'acanthomorpha',
		'range': 'ww',
	},
	{
		'name': 'perissodactyla',
		'rank': 'order',
		'parent': 'ungulata',
		'range': 'ww',
	},
	{
		'name': 'petroselinum',
		'rank': 'genus',
		'parent': 'apiaceae',
		'range': 'ow',
	},
	{
		'name': 'petroselinum crispum',
		'rank': 'species',
		'parent': 'petroselinum',
		'range': 'ow',
		'desc': 'Parsley',
	},
	{
		'name': 'phaeophyceae',
		'rank': 'class',
		'parent': 'ochrophyta',
		'range': 'ww',
		'age': 150,
		'desc': 'Brown Algae',
	},
	{
		'name': 'phaseolus',
		'rank': 'genus',
		'parent': 'fabaceae',
		'range': 'nw',
	},
	{
		'name': 'phaseolus vulgaris',
		'rank': 'species',
		'parent': 'phaseolus',
		'range': 'nw',
		'desc': 'Common Bean',
	},
	{
		'name': 'phasianidae',
		'rank': 'family',
		'parent': 'galliformes',
		'range': 'ww',
	},
	{
		'name': 'phasianinae',
		'rank': 'subfamily',
		'parent': 'phasianidae',
		'range': 'ow',
	},
	{
		'name': 'pholidota',
		'rank': 'order',
		'parent': 'ferae',
		'range': 'ow',
		'desc': 'Pangolin',
	},
	{
		'name': 'phragmites',
		'rank': 'genus',
		'parent': 'pacmad clade',
		'range': 'ww',
		'desc': 'Common Reed',
	},
	{
		'name': 'physalis',
		'rank': 'genus',
		'parent': 'solanaceae',
		'range': 'ww',
	},
	{
		'name': 'physalis philadelphica',
		'rank': 'species',
		'parent': 'physalis',
		'range': 'na',
		'desc': 'Tomatillo',
	},
	{
		'name': 'picea',
		'rank': 'genus',
		'parent': 'pinaceae',
		'range': 'nh',
		'desc': 'Spruce',
	},
	{
		'name': 'pisum',
		'rank': 'genus',
		'parent': 'fabaceae',
		'range': 'ow',
	},
	{
		'name': 'pisum sativum',
		'rank': 'species',
		'parent': 'pisum',
		'range': 'ow',
		'desc': 'Pea',
	},
	{
		'name': 'pinaceae',
		'rank': 'family',
		'parent': 'pinales',
		'range': 'nh',
	},
	{
		'name': 'pinales',
		'rank': 'order',
		'parent': 'pinopsida',
		'range': 'ww',
	},
	{
		'name': 'pinophyta',
		'rank': 'division',
		'parent': 'plantae',
		'range': 'ww',
		'age': 300,
		'desc': 'Conifer',
	},
	{
		'name': 'pinopsida',
		'rank': 'class',
		'parent': 'pinophyta',
		'range': 'ww',
	},
	{
		'name': 'pinus',
		'rank': 'genus',
		'parent': 'pinaceae',
		'range': 'nh',
		'desc': 'Pine',
	},
	{
		'name': 'piper',
		'rank': 'genus',
		'parent': 'piperaceae',
		'range': 'eq',
	},
	{
		'name': 'piper nigrum',
		'rank': 'species',
		'parent': 'piper',
		'range': 'as',
		'desc': 'Black Pepper',
	},
	{
		'name': 'piperaceae',
		'rank': 'family',
		'parent': 'piperales',
		'range': 'eq',
	},
	{
		'name': 'piperales',
		'rank': 'order',
		'parent': 'magnoliids',
		'range': 'eq',
	},
	{
		'name': 'plantae',
		'rank': 'kingdom',
		'parent': 'diaphoretickes',
		'range': 'ww',
		'age': 1200,
		'desc': 'Plant',
	},
	{
		'name': 'platyhelminthes',
		'rank': 'phylum',
		'parent': 'protostomia',
		'age': 580,
		'desc': 'Flatworm',
	},
	{
		'name': 'plesiosauria',
		'rank': 'order',
		'parent': 'sauropterygia',
		'extinct': true,
		'range': 'ww',
		'desc': 'Plesiosaur',
	},
	{
		'name': 'poales',
		'rank': 'order',
		'parent': 'commelinids',
		'range': 'ww',
	},
	{
		'name': 'poaceae',
		'rank': 'family',
		'parent': 'poales',
		'range': 'ww',
		'desc': 'Grass',
	},
	{
		'name': 'pollachius',
		'rank': 'genus',
		'parent': 'gadidae',
		'range': 'al',
		'desc': 'Pollock',
	},
	{
		'name': 'pongo',
		'rank': 'genus',
		'parent': 'hominidae',
		'range': 'as',
		'age': 2,
		'desc': 'Orangutan',
	},
	{
		'name': 'porifera',
		'rank': 'phylum',
		'parent': 'animalia',
		'range': 'ww',
		'age': 580,
		'desc': 'Sponge',
	},
	{
		'name': 'primates',
		'rank': 'order',
		'parent': 'euarchontoglires',
		'range': 'eq',
		'age': 55,
		'desc': 'Primate characteristics include large brains, visual acuity, color vision, altered shoulder girdle, and dextrous hands.',
	},
	{
		'name': 'proteobacteria',
		'rank': 'phylum',
		'parent': 'gracilicutes',
		'range': 'ww',
	},
	{
		'name': 'protostomia',
		'rank': 'superphylum',
		'parent': 'bilateria',
		'range': 'ww',
		'age': 610,
	},
	{
		'name': 'prunus',
		'rank': 'genus',
		'parent': 'rosaceae',
		'range': 'ww',
	},
	{
		'name': 'subg. prunus', // alphabetically treated as if subg. weren't there
		'rank': 'subgenus',
		'parent': 'prunus',
		'range': 'as',
		'desc': 'Plum',
	},
	{
		'name': 'prunus armeniaca',
		'rank': 'species',
		'parent': 'prunus',
		'range': 'as',
		'desc': 'Apricot',
	},
	{
		'name': 'prunus dulcis',
		'rank': 'species',
		'parent': 'prunus',
		'range': 'as',
		'desc': 'Almond',
	},
	{
		'name': 'prunus persica',
		'rank': 'species',
		'parent': 'prunus',
		'range': 'as',
		'desc': 'Peach',
	},
	{
		'name': 'psittaciformes',
		'rank': 'order',
		'parent': 'psittacopasserae',
		'range': 'eq',
		'desc': 'Parrot',
	},
	{
		'name': 'psittacopasserae',
		'rank': 'clade',
		'parent': 'telluraves',
		'range': 'ww',
	},
	{
		'name': 'pterosauria',
		'rank': 'order',
		'parent': 'archosauria',
		'extinct': true,
		'range': 'ww',
		'desc': 'Pterosaur',
	},
	{
		'name': 'pyropia',
		'rank': 'genus',
		'parent': 'bangiaceae',
		'range': 'ww',
		'desc': 'Nori',
	},
	{
		'name': 'pyrus',
		'rank': 'genus',
		'parent': 'rosaceae',
		'range': 'ea',
		'desc': 'Pear',
	},
	{
		'name': 'quercus',
		'rank': 'genus',
		'parent': 'fagaceae',
		'range': 'nh',
		'desc': 'Oak',
	},
	{
		'name': 'raphanus',
		'rank': 'genus',
		'parent': 'brassicaceae',
		'range': 'ow',
	},
	{
		'name': 'raphanus sativus',
		'rank': 'species',
		'parent': 'raphanus',
		'range': 'ow',
		'desc': 'Radish',
	},
	{
		'name': 'reptilia',
		'rank': 'class',
		'parent': 'amniota',
		'range': 'ww',
		'age': 312,
	},
	{
		'name': 'rhodophyta',
		'rank': 'division',
		'parent': 'diaphoretickes',
		'range': 'ww',
		'age': 1300, // +/- 300
		'desc': 'Red Algae',
	},
	{
		'name': 'rhopalocera',
		'rank': 'suborder',
		'parent': 'lepidoptera',
		'range': 'ww',
		'desc': 'Butterfly',
	},
	{
		'name': 'rodentia',
		'rank': 'order',
		'parent': 'glires',
		'range': 'ww',
	},
	{
		'name': 'rosaceae',
		'rank': 'family',
		'parent': 'rosales',
		'range': 'ww',
	},
	{
		'name': 'rosales',
		'rank': 'order',
		'parent': 'fabids',
		'range': 'ww',
	},
	{
		'name': 'rosids',
		'rank': 'clade',
		'parent': 'eudicots',
		'range': 'ww',
	},
	{
		'name': 'rutaceae',
		'rank': 'family',
		'parent': 'sapindales',
		'range': 'ww',
	},
	// S
	{
		'name': 'saccharum',
		'rank': 'genus',
		'parent': 'panicoideae',
		'range': 'ww',
		'desc': 'Sugarcane',
	},
	{
		'name': 'salmonidae',
		'rank': 'family',
		'parent': 'salmoniformes',
		'range': 'nh',
	},
	{
		'name': 'salmoniformes',
		'rank': 'order',
		'parent': 'teleostei',
		'range': 'nh',
	},
	{
		'name': 'salmoninae',
		'rank': 'subfamily',
		'parent': 'salmonidae',
		'range': 'nh',
		'desc': 'Salmon',
	},
	{
		'name': 'sapindales',
		'rank': 'order',
		'parent': 'malvids',
		'range': 'ww',
	},
	{
		'name': 'sauria',
		'rank': 'clade',
		'parent': 'reptilia',
		'range': 'ww',
	},
	{
		'name': 'saurischia',
		'rank': 'clade',
		'parent': 'archosauria',
		'range': 'ww',
	},
	{
		'name': 'sauropterygia',
		'rank': 'superorder',
		'parent': 'sauria',
		'extinct': true,
		'range': 'ww',
	},
	{
		'name': 'sciuridae',
		'rank': 'family',
		'parent': 'rodentia',
		'range': 'ww',
		'desc': 'Squirrel',
	},
	{
		'name': 'scleractinia',
		'rank': 'order',
		'parent': 'anthozoa',
		'range': 'ww',
		'age': 240,
		'desc': 'Hard Coral',
	},
	{
		'name': 'scombridae',
		'rank': 'family',
		'parent': 'scombriformes',
		'range': 'ww',
	},
	{
		'name': 'scombriformes',
		'rank': 'order',
		'parent': 'percomorpha',
		'range': 'ww',
	},
	{
		'name': 'scyliorhinidae',
		'rank': 'order',
		'parent': 'carcharhiniformes',
		'range': 'ww',
		'desc': 'Catshark',
	},
	{
		'name': 'selachimorpha',
		'rank': 'superorder',
		'parent': 'chondrichthyes',
		'range': 'ww',
		'desc': 'Shark',
	},
	{
		'name': 'serpentes',
		'rank': 'suborder',
		'parent': 'squamata',
		'range': 'ww',
		'desc': 'Snake',
	},
	{
		'name': 'siluriformes',
		'rank': 'order',
		'parent': 'teleostei',
		'range': 'ww',
		'desc': 'Catfish',
	},
	{
		'name': 'solanaceae',
		'rank': 'family',
		'parent': 'solanales',
		'range': 'ww',
	},
	{
		'name': 'solanales',
		'rank': 'order',
		'parent': 'lamiids',
		'range': 'ww',
	},
	{
		'name': 'solanum',
		'rank': 'genus',
		'parent': 'solanaceae',
		'range': 'ww',
	},
	{
		'name': 'solanum lycopersicum',
		'rank': 'species',
		'parent': 'solanum',
		'range': 'sa',
		'desc': 'Tomato',
	},
	{
		'name': 'solanum melongena',
		'rank': 'species',
		'parent': 'solanum',
		'range': 'ow',
		'desc': 'Eggplant',
	},
	{
		'name': 'solanum tuberosum',
		'rank': 'species',
		'parent': 'solanum',
		'range': 'sa',
		'desc': 'Potato',
	},
	{
		'name': 'sphenisciformes',
		'rank': 'order',
		'parent': 'neoaves',
		'range': 'sh',
		'desc': 'Penguin',
	},
	{
		'name': 'squamata',
		'rank': 'order',
		'parent': 'sauria',
		'range': 'ww',
	},
	{
		'name': 'stegosauridae',
		'rank': 'family',
		'parent': 'ornithischia',
		'extinct': true,
		'range': 'ww',
	},
	{
		'name': 'stegosaurus',
		'rank': 'genus',
		'parent': 'stegosauridae',
		'extinct': true,
		'range': 'nh',
	},
	{
		'name': 'strigiformes',
		'rank': 'order',
		'parent': 'telluraves',
		'range': 'ww',
		'desc': 'Owl',
	},
	{
		'name': 'suidae',
		'rank': 'family',
		'parent': 'suina',
		'range': 'ow',
	},
	{
		'name': 'suina',
		'rank': 'suborder',
		'parent': 'artiofabula',
		'range': 'ww',
	},
	{
		'name': 'sus',
		'rank': 'genus',
		'parent': 'suidae',
		'range': 'ow',
		'desc': 'Pig',
	},
	// T
	{
		'name': 'teleostei',
		'rank': 'infraclass',
		'parent': 'actinopterygii',
		'range': 'ww',
	},
	{
		'name': 'telluraves',
		'rank': 'clade',
		'parent': 'neoaves',
		'range': 'ww',
	},
	{
		'name': 'terrabacteria',
		'rank': 'clade',
		'parent': 'bacteria',
		'range': 'ww',
	},
	{
		'name': 'tetraodontidae',
		'rank': 'family',
		'parent': 'tetraodontiformes',
		'range': 'eq',
		'desc': 'Pufferfish',
	},
	{
		'name': 'tetraodontiformes',
		'rank': 'order',
		'parent': 'percomorpha',
		'range': 'ww',
	},
	{
		'name': 'tetrapoda',
		'rank': 'superclass',
		'parent': 'osteichthyes',
		'range': 'ww',
		'age': 370,
		'desc': 'Tetrapods are four-limbed animals.',
	},
	{
		'name': 'theobroma',
		'rank': 'genus',
		'parent': 'malvaceae',
		'range': 'nw',
	},
	{
		'name': 'theobroma cacao',
		'rank': 'species',
		'parent': 'theobroma',
		'range': 'nw',
		'desc': 'Cocoa',
	},
	{
		'name': 'theropoda',
		'rank': 'clade',
		'parent': 'saurischia',
		'range': 'ww',
	},
	{
		'name': 'thunni',
		'rank': 'tribe',
		'parent': 'scombridae',
		'range': 'ww',
		'desc': 'Tuna',
	},
	{
		'name': 'triceratops',
		'rank': 'genus',
		'parent': 'ceratopsidae',
		'extinct': true,
		'range': 'na',
	},
	{
		'name': 'trichocomaceae',
		'rank': 'family',
		'parent': 'eurotiales',
		'range': 'ww',
	},
	{
		'name': 'trilobita',
		'rank': 'class',
		'parent': 'arthropoda',
		'extinct': true,
		'range': 'ww',
		'age': 521,
		'desc': 'Trilobite',
	},
	{
		'name': 'triticum',
		'rank': 'genus',
		'parent': 'bop clade',
		'range': 'as',
		'desc': 'Wheat',
	},
	{
		'name': 'tursiops',
		'rank': 'genus',
		'parent': 'delphinidae',
		'range': 'ww',
		'desc': 'Bottlenose Dolphin',
	},
	{
		'name': 'tylopoda',
		'rank': 'suborder',
		'parent': 'artiodactyla',
		'range': 'ww',
	},
	{
		'name': 'tyrannosauridae',
		'rank': 'family',
		'parent': 'theropoda',
		'range': 'nh',
		'extinct': true,
	},
	{
		'name': 'tyrannosaurus',
		'rank': 'genus',
		'parent': 'tyrannosauridae',
		'range': 'na',
		'extinct': true,
	},
	{
		'name': 'tyrannosaurus rex',
		'rank': 'species',
		'parent': 'tyrannosaurus',
		'range': 'na',
		'extinct': true,
	},
	{
		'name': 'ungulata',
		'rank': 'clade',
		'parent': 'laurasiatheria',
		'range': 'ww',
	},
	{
		'name': 'utahraptor',
		'rank': 'genus',
		'parent': 'dromaeosauridae',
		'extinct': true,
		'range': 'na',
	},
	{
		'name': 'vanilla',
		'rank': 'genus',
		'parent': 'orchidaceae',
		'range': 'eq',
	},
	{
		'name': 'vanilla planifolia',
		'rank': 'species',
		'parent': 'vanilla',
		'range': 'nw',
		'desc': 'Vanilla',
	},
	{
		'name': 'velociraptor',
		'rank': 'genus',
		'parent': 'dromaeosauridae',
		'extinct': true,
		'range': 'as',
	},
	{
		'name': 'vitaceae',
		'rank': 'family',
		'parent': 'vitales',
		'range': 'ww',
	},
	{
		'name': 'vitales',
		'rank': 'order',
		'parent': 'rosids',
		'range': 'ww',
	},
	{
		'name': 'vitis',
		'rank': 'genus',
		'parent': 'vitaceae',
		'range': 'ow',
		'desc': 'Grape',
	},
	{
		'name': 'vulpes',
		'rank': 'genus',
		'parent': 'canidae',
		'range': 'ww',
	},
	{
		'name': 'vulpes vulpes',
		'rank': 'species',
		'parent': 'vulpes',
		'range': 'nh',
		'desc': 'Red Fox',
	},
	{
		'name': 'zea',
		'rank': 'genus',
		'parent': 'panicoideae',
		'range': 'na',
	},
	{
		'name': 'zea mays',
		'rank': 'species',
		'parent': 'zea',
		'range': 'na',
		'desc': 'Maize',
	},
	{
		'name': 'zingiber',
		'rank': 'genus',
		'parent': 'zingiberaceae',
		'range': 'as',
	},
	{
		'name': 'zingiber officinale',
		'rank': 'species',
		'parent': 'zingiber',
		'range': 'as',
		'desc': 'Ginger',
	},
	{
		'name': 'zingiberaceae',
		'rank': 'family',
		'parent': 'zingiberales',
		'range': 'eq',
	},
	{
		'name': 'zingiberales',
		'rank': 'order',
		'parent': 'commelinids',
		'range': 'eq',
	},
];