// 'Welcome!','Bonvenon!','Bienvenue!','Salve!','Geti!','Bienvenido!','ようこそ!',
/*
				'It\' a "hash" not a "hashtag", unless it\'s followed by a tag.',
																						| Anything to the left of this line fits (71 char)
*/
var subtitles =	[
				'Math, &#x1F44F; Cities, &#x1F44F; Math &#x1F44F; \'n Cities! &#x1F44F;',
				'Gluten-free Mocha: now with real sugar!',
				'The fruitiest of all fruity-ass fruitbowls!',
				'"Gay and Fake" - NYT review',
				'The antonym of <i>Mocha</i> is <i>Lesscha</i>.',
				'The antonym of <i>subtraction</i> is <i>domdition</i>.',
				'&iexcl;Mundos Interminables, Historias Interminables!',
				'Ab <i>owo</i> usque ad <i>What\'s this???</i>',
				'Is <i>*(é)-trom</i> an instrument?',
				'The pizza doesn’t scream when you put it in the oven.',
				'Poorly-transed Japanese for <i>also tea</i>? You decide.',
				'The med curse is real',
				'contown retarded; gg maf',
				'I have created a truly marvelous conworld,<br/>which this randomly generated subtitle is too small to contain.',
				'<a href="https://en.wikipedia.org/wiki/Bet_(letter)">Bet</a>, <a href="https://en.wikipedia.org/wiki/Click_consonant">clicks</a>, and <a href="https://en.wikipedia.org/wiki/Trill_consonant">trills</a>?',
				'<b>aragoscope</b> <i>n</i>. : the act of <a href="https://en.wikipedia.org/wiki/Kingdom_of_Castile#Union_of_the_Crowns_of_Castile_and_Aragon">noscoping Aragon</a>',
				'Mocha &isin; Fags',
				'&lambda;x.x is Mocha',
				'slash-me huggu',
				'#ThingsISayBeforeSex: <i>quinque</i>',
				'Zen and the Art of Conworlding',
				'You spice?',
				'<i>Real</i> News.',
				'The Senate and Poplar of Rome',
				'Mentula Culusque Moechi',
				'Certified Elf-Kosher',
				'/mo(ch|k|hx|\\u0125)[aeiou]r?/gi',
				'Perihelion * Date of perihelion passage * 3.14',
				'...baka!',
				'/d&#658;&#618;f/ not /g&#618;f/',
				'The coneconomy, stupid!',
				'Make Namei Great Again',
				'I neither misspell nor use bad grammar;<br/>I just use a different style guide.',
				'Hey man, at least <i>my</i> conlangs don\'t use words like <i>boato</i> and <i>farmo</i>',
				'Je transforme les plan&egrave;tes en mondes.',
				'Construo ergo sum.',
				'But I would walk <abbr title="878 km, 546 mi">200 abakêum</abbr>, and I would walk 200 more!',
				'I speak no language; I just toy with words until they do what I want.',
				'First to contact me in my conlangs gets an e-cookie.',
				'"My marker was stolen!",<br/>cried the professor after condemning the passive.',
				'The passive is not used often enough.',
				'More struts and boosters than the leading brand!',
				'Looks like we got ourselves a li\'l Mike-Oscar-Charlie-Hotel-Alfa!',
				'49206a757374207761737465642061206d696e757465206f6620796f75722074696d652e203b33',
				'.... .- ...- . / -.-- --- ..- / -. --- / .-.. .. ..-. .',
				'Enkl&aacute;r\'s Stead, by Enkl&aacute;r\'s Head',
				'I did <i>not</i> have sexual relations with that map.',
				'<i>"No"</i>',
				'We can finally invade the heart of Eremor.<br/>Unfortunately for you, your adventure ends here.',
				'I can hear them breaching the defenses of my RigFives ship.',
				'Culus Invictus'
				]
function Sub() {
	var index = Math.floor(Math.random()*(subtitles.length));
	document.getElementById('subtitle').innerHTML = subtitles[index];
	console.info('C3692 6510 QT4420');
}