/* exported POLITICIANS */
/* global Gender, Party, Position */

const POLITICIANS = [
	{
		name: 'Donald Trump',
		dob: new Date(1946, 5, 14),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.NONE,
		state: 'FL',
	},
	{
		name: 'Joe Biden', // president
		dob: new Date(1942, 10, 20),
		gender: Gender.MALE,
		party: Party.DEMOCRATIC,
		position: Position.PRESIDENT,
		state: 'DE',
	},
	{
		name: 'Kamala Harris', // vice president
		dob: new Date(1964, 9, 20),
		gender: Gender.FEMALE,
		party: Party.DEMOCRATIC,
		position: Position.VICE_PRESIDENT,
		state: 'CA',
	},
	// RFK
	{
		name: 'Robert Kennedy',
		dob: new Date(1954, 0, 17),
		gender: Gender.MALE,
		party: Party.INDEPENDENT,
		position: Position.NONE,
		state: 'CA',
	},
	{
		name: 'Nicole Shanahan',
		dob: new Date(1985, 8, 26),
		gender: Gender.FEMALE,
		party: Party.INDEPENDENT,
		position: Position.NONE,
		state: 'CA',
	},
	// West
	{
		name: 'Cornel West',
		dob: new Date(1953, 5, 2),
		gender: Gender.MALE,
		party: Party.JFA,
		position: Position.NONE,
		state: 'CA',
	},
	{
		name: 'Melina Abdullah',
		dob: new Date(1972, 0),
		gender: Gender.FEMALE,
		party: Party.JFA,
		position: Position.NONE,
		state: 'CA',
	},
	// Green
	{
		name: 'Jill Stein',
		dob: new Date(1950, 4, 14),
		gender: Gender.FEMALE,
		party: Party.GREEN,
		position: Position.NONE,
		state: 'MA',
	},
	{
		name: 'Jasmine Sherman',
		dob: new Date(1985, 0), // guess
		gender: Gender.NONBINARY, // https://jasminesherman.com/about-president/
		party: Party.GREEN,
		position: Position.NONE,
		state: 'NC',
	},
	// Trump VP picks
	{
		name: 'Doug Burgum',
		dob: new Date(1956, 8, 1),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.GOVERNOR,
		state: 'ND',
	},
	{
		name: 'Tucker Carlson',
		dob: new Date(1969, 5, 16),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.NONE,
		state: 'FL', // unsure
	},
	{
		name: 'Ben Carson',
		dob: new Date(1951, 8, 18),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.NONE,
		state: 'MI', // unsure
	},
	{
		name: 'Tom Cotton',
		dob: new Date(1977, 4, 13),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.SENATOR,
		state: 'AR',
	},
	{
		name: 'Kristi Noem',
		dob: new Date(1971, 10, 30),
		gender: Gender.FEMALE,
		party: Party.REPUBLICAN,
		position: Position.GOVERNOR,
		state: 'SD',
	},
	{
		name: 'Vivek Ramaswamy',
		dob: new Date(1985, 7, 9),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.NONE,
		state: 'OH',
	},
	{
		name: 'Marco Rubio',
		dob: new Date(1971, 4, 28),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.SENATOR,
		state: 'FL',
	},
	{
		name: 'Tim Scott',
		dob: new Date(1965, 8, 19),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.SENATOR,
		state: 'SC',
	},
	{
		name: 'James Vance',
		dob: new Date(1984, 7, 2),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.SENATOR,
		state: 'OH',
	},
	// republican reps
	{
		name: 'Byron Donalds',
		dob: new Date(1978, 9, 28),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.REPRESENTATIVE,
		state: 'FL',
	},
	{
		name: 'Mike Johnson',
		dob: new Date(1972, 0, 30),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.REPRESENTATIVE,
		state: 'LA',
	},
	{
		name: 'Kevin McCarthy',
		dob: new Date(1965, 1, 26),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.REPRESENTATIVE,
		state: 'CA',
	},
	{
		name: 'Patrick McHenry',
		dob: new Date(1975, 10, 22),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.REPRESENTATIVE,
		state: 'NC',
	},
	{
		name: 'Steve Scalise',
		dob: new Date(1965, 9, 6),
		gender: Gender.MALE,
		party: Party.REPUBLICAN,
		position: Position.REPRESENTATIVE,
		state: 'LA',
	},
	{
		name: 'Elise Stefanik',
		dob: new Date(1984, 6, 2),
		gender: Gender.FEMALE,
		party: Party.REPUBLICAN,
		position: Position.REPRESENTATIVE,
		state: 'NY',
	},
	// backup dem pols
	{
		name: 'Hillary Clinton',
		dob: new Date(1947, 9, 26),
		gender: Gender.FEMALE,
		party: Party.DEMOCRATIC,
		position: Position.NONE,
		state: 'NY',
	},
	{
		name: 'Amy Klobuchar',
		dob: new Date(1960, 4, 25),
		gender: Gender.FEMALE,
		party: Party.DEMOCRATIC,
		position: Position.SENATOR,
		state: 'MN',
	},
	{
		name: 'Elizabeth Warren',
		dob: new Date(1949, 5, 22),
		gender: Gender.FEMALE,
		party: Party.DEMOCRATIC,
		position: Position.SENATOR,
		state: 'MA',
	},
	// minor backups
	{
		name: 'Tulsi Gabbard',
		dob: new Date(1981, 3, 12),
		gender: Gender.FEMALE,
		party: Party.INDEPENDENT,
		position: Position.NONE,
		state: 'HI',
	},
	{
		name: 'Peter Daou',
		dob: new Date(1965, 0),
		gender: Gender.MALE,
		party: Party.JFA,
		position: Position.NONE,
		state: 'NY',
	},
	{
		name: 'Tanda Blubear',
		dob: new Date(1980, 0), // guess
		gender: Gender.FEMALE,
		party: Party.GREEN,
		position: Position.NONE,
		state: 'CA',
	},
];