/* exported chardata, raindata */
const raindata = [
	{
		url: 'https://rain.thecomicseries.com/comics/first/#content-start',
		src: 'https://img.comicfury.com/comics/dfebc8f8d333973fadb59e1e6552ebbd454448621.png',
		title: 'RAIN',
		chapter: 'Unchaptered',
		chars: ['rain'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/2#content-start',
		src: 'https://img.comicfury.com/comics/c3dbf56cfb1eb1124bbe71902242e86a406900338.png',
		title: 'Prologue 1',
		chapter: 'Ch 1: The New Girl ',
		chars: ['mom', 'aiken', 'kellen', 'rain'],
		setting: ['old_home'],
		tags: ['flashback'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/3#content-start',
		src: 'https://img.comicfury.com/comics/3714ae7b21d6a4f3e73d74088cbf6de61332828526.png',
		title: 'Prologue 2',
		chapter: 'Ch 1: The New Girl ',
		chars: ['mom', 'rain', 'aiken', 'kellen'],
		setting: ['old_home'],
		tags: ['flashback'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/4#content-start',
		src: 'https://img.comicfury.com/comics/c2b8141e64b94ce5031968192e44ef0b1125474994.png',
		title: 'Prologue 3',
		chapter: 'Ch 1: The New Girl ',
		chars: ['rain'],
		setting: ['old_home'],
		tags: ['flashback'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/5#content-start',
		src: 'https://img.comicfury.com/comics/08b927540b54cb4adf7e20ff9e061298435475647.png',
		title: 'Morning Routine',
		chapter: 'Ch 1: The New Girl ',
		chars: ['rain'],
		setting: ['home'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/6#content-start',
		src: 'https://img.comicfury.com/comics/c8f813e19a0aae0f2a0b57a6b36ceec52058036413.png',
		title: 'Chapter 1 - The New Girl',
		chapter: 'Ch 1: The New Girl ',
		chars: ['gavin', 'maria', 'rain', 'rudy'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/7#content-start',
		src: 'https://img.comicfury.com/comics/cf541c67c5957d77f230fbe67bebece3756619423.png',
		title: 'Aunt Fara',
		chapter: 'Ch 1: The New Girl ',
		chars: ['rain', 'fara'],
		setting: ['home'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/8#content-start',
		src: 'https://img.comicfury.com/comics/c8aa144daf7689584a4dac0fe8ccc8e2992769914.png',
		title: 'Tact',
		chapter: 'Ch 1: The New Girl ',
		chars: ['rain', 'fara'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/9#content-start',
		src: 'https://img.comicfury.com/comics/6d068bc0d41489595a11058cb9ceb824575229024.png',
		title: 'Blending In',
		chapter: 'Ch 1: The New Girl ',
		chars: ['rain', 'fara', 'maria', 'gavin'],
		setting: ['school'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/10/#content-start',
		src: 'https://img.comicfury.com/comics/57643b9e8b359e784c4f7a4d3de6d688632612367.png',
		title: 'The Bet',
		chapter: 'Ch 1: The New Girl ',
		chars: ['maria', 'gavin', 'rain'],
		setting: ['school'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/11/#content-start',
		src: 'https://img.comicfury.com/comics/f86e5e3abaf377373d981726c841559a1335208423.png',
		title: 'Squeak',
		chapter: 'Ch 1: The New Girl ',
		chars: ['arthur', 'emily', 'maria', 'gavin', 'rain'],
		setting: ['school'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/12/#content-start',
		src: 'https://img.comicfury.com/comics/b2eb13bbd9645c22e31c3c463eacea1a2135437039.png',
		title: 'High School in a Nutshell',
		chapter: 'Ch 1: The New Girl ',
		chars: ['devon', 'rain', 'drew', 'robert', 'holly', 'emily', 'debbie', 'maria', 'gavin'],
		setting: ['school'],
	},
	{
		url: 'https://rain.thecomicseries.com/comics/13/#content-start',
		src: 'https://img.comicfury.com/comics/4697dcd9d750f2479302cdfd6aa377f71767843488.png',
		title: 'Oh, the Irony...',
		chapter: 'Ch 1: The New Girl ',
		chars: ['maria', 'gavin'],
		setting: ['school'],
	},
];

const chardata = [
	{
		'id': 'rain',
		'name': 'Rain Flaherty',
		'age': 17,
		'gender': 'f',
		'sexuality': 'unknown',
	},
	{
		'id': 'fara',
		'name': 'Fara Bryer',
		'age': 36,
		'gender': 'f',
		'sexuality': 'bisexual',
	},
	{
		'id': 'aiken',
		'name': 'Aiken Flaherty',
		'age': 26,
		'gender': 'm',
		'sexuality': 'straight',
	},
	{
		'id': 'kellen',
		'name': 'Kellen Flaherty',
		'age': 26,
		'gender': 'f',
		'sexuality': 'straight',
	},
	{ // DO NOT SPOIL HIS IDENTITY
		'id': 'mom',
		'name': 'Liriel Flaherty',
		'age': 46,
		'gender': 'f',
		'sexuality': 'straight',
	},
	{
		'id': 'gavin',
		'name': 'Gavin Kurz',
		'age': 17,
		'gender': 'm',
		'sexuality': 'straight',
	},
	{
		'id': 'maria',
		'name': 'Maria Strongwell',
		'age': 17,
		'gender': 'f',
		'sexuality': 'lesbian',
	},
	{
		'id': 'rudy',
		'name': 'Rudy Strongwell',
		'age': 15,
		'gender': 'm',
		'sexuality': 'gay',
	},
	{
		'id': 'arthur',
		'name': 'Brother Arthur Feltman',
		'age': 45,
		'gender': 'm',
		'sexuality': 'asexual',
	},
	{
		'id': 'emily',
		'name': 'Emily Caston',
		'age': 17,
		'gender': 'f',
		'sexuality': 'straight',
	},
	{
		'id': 'devon',
		'name': 'Devon Givens',
		'age': 17,
		'gender': 'm',
		'sexuality': 'straight',
	},
	{
		'id': 'drew',
		'name': 'Drew Borelli',
		'age': 17,
		'gender': 'm',
		'sexuality': 'straight',
	},
	{
		'id': 'robert',
		'name': 'Robert Roberts',
		'age': 17,
		'gender': 'm',
		'sexuality': 'straight',
	},
	{
		'id': 'holly',
		'name': 'Holly O\'Neill',
		'age': 17,
		'gender': 'f',
		'sexuality': 'straight',
	},
	{
		'id': 'debbie',
		'name': 'Debbie Gero',
		'age': 17,
		'gender': 'f',
		'sexuality': 'straight',
	},
];