/* exported etymData, etymLangData */

// shortcuts
const EDS = {
	english: 'English',
	german: 'German',
	greek: 'Ancient Greek',
	italian: 'Italian',
	latin: 'Latin',
	mocha: '(mochanoises)',
	spanish: 'Spanish',
};

const etymData = [
	// make these alphabetical
	// ENGLISH
	{
		head: '-er',
		lang: EDS.english,
		gloss: '(agent)',
		forms: ['er'],
	},
	{
		head: '-ery',
		lang: EDS.english,
		gloss: '(N)',
		forms: ['e?ries$', 'e?ry$'],
	},
	{
		head: '-ish',
		lang: EDS.english,
		gloss: '(ADJ)',
		forms: ['ish$'],
	},
	{
		head: '-ly',
		lang: EDS.english,
		gloss: '(ADV)',
		forms: ['ly$'],
	},
	{
		head: '-ness',
		lang: EDS.english,
		gloss: '(N)',
		forms: ['ness'],
	},
	{
		head: '-odd',
		lang: EDS.english,
		gloss: '(infrafamily of animal)',
		forms: ['odd$'],
	},
	{
		head: '-ol',
		lang: EDS.latin,
		gloss: '(used to form names of alcohols)',
		forms: ['ol$'],
	},
	{
		head: '-s',
		lang: EDS.english,
		gloss: '(PL)',
		forms: ['s$', 'es$'],
	},
	{
		head: '-y',
		lang: EDS.english,
		gloss: '(N) or (ADJ)',
		forms: ['y$', 'ie(?=s$)'],
	},
	{
		head: 'ribo-',
		lang: EDS.english,
		gloss: 'ribose', // the word ribose is an alteration of arabinose, which comes from arabi-
		forms: ['ribo'],
	},
	{
		head: 'rna',
		lang: EDS.english,
		gloss: 'RNA',
		forms: ['rna'],
	},
	{
		head: 'thucholite',
		lang: EDS.english,
		gloss: 'thucholite',
		forms: ['thucho'],
	},
	// GERMAN
	{
		head: 'ur-',
		lang: EDS.german,
		gloss: 'primitive',
		forms: ['ur'],
	},
	// ITALIAN
	{
		head: '-ino',
		lang: EDS.italian,
		gloss: '(DIM)',
		forms: ['ino'],
	},
	{
		head: '-one',
		lang: EDS.italian,
		gloss: '(AUG)',
		forms: ['one?'],
	},
	// SPANISH
	{
		head: 'pico',
		lang: EDS.spanish,
		gloss: 'speck',
		forms: ['pico'],
	},
	// LATIN
	{
		head: '-a',
		lang: EDS.latin,
		gloss: '(N)',
		forms: ['a$', 'ae$'],
	},
	{
		head: '-acea',
		lang: EDS.latin,
		gloss: '(suborder of animal or superfamily of non-animal)',
		forms: ['acea$'],
	},
	{
		head: '-aceae',
		lang: EDS.latin,
		gloss: '(family of non-animal)',
		forms: ['aceae$'],
	},
	{
		head: '-alis',
		lang: EDS.latin,
		gloss: '(ADJ)',
		forms: ['alis$', 'a?les$', 'alia$', 'al$'],
	},
	{
		head: '-anae',
		lang: EDS.latin,
		gloss: '(superorder of non-animal)',
		forms: ['ales$'],
	},
	{
		head: '-ans',
		lang: EDS.latin,
		gloss: '-ing',
		forms: ['ans$', 'ant'],
	},
	{
		head: '-anus',
		lang: EDS.latin,
		gloss: '(ADJ)',
		forms: ['ane$', 'an'],
	},
	{
		head: '-ara',
		lang: EDS.latin,
		gloss: '(nothogenus)',
		forms: ['ara$'],
	},
	{
		head: '-aria',
		lang: EDS.latin,
		gloss: '(taxon)',
		forms: ['aria$'],
	},
	{
		head: '-aris',
		lang: EDS.latin,
		gloss: '(ADJ)',
		forms: ['ar$'],
	},
	{
		head: '-arius',
		lang: EDS.latin,
		gloss: '(ADJ)',
		forms: ['ary$'],
	},
	{
		head: '-atus',
		lang: EDS.latin,
		gloss: '(PP)',
		forms: ['ate$', 'ato', 'at'], // eg. choano-flagell-at-ea
	},
	{
		head: '-ea',
		lang: EDS.latin,
		gloss: '(taxon)',
		forms: ['ea$'],
	},
	{
		head: '-eae',
		lang: EDS.latin,
		gloss: '(tribe of non-animal)',
		forms: ['eae$'],
	},
	{
		head: '-ell-',
		lang: EDS.latin,
		gloss: '(DIM)',
		forms: ['ell', 'el'],
	},
	{
		head: '-ens',
		lang: EDS.latin,
		gloss: '-ing',
		forms: ['ens$', 'ent'],
	},
	{
		head: '-es',
		lang: EDS.latin,
		gloss: '(taxon)',
		forms: ['es$'],
	},
	{
		head: '-fer',
		lang: EDS.latin,
		gloss: 'bearing',
		forms: ['ifer', 'fer'], // loric-ifera
	},
	{
		head: '-ia',
		lang: EDS.latin,
		gloss: '(taxon)',
		forms: ['ia$'],
	},
	{
		head: '-icus',
		lang: EDS.latin,
		gloss: '(ADJ)',
		forms: ['ic'],
	},
	{
		head: '-ida',
		lang: EDS.latin,
		gloss: '(order of animal)',
		forms: ['ida$', 'oda$', 'da$'],
	},
	{
		head: '-idae',
		lang: EDS.latin,
		gloss: '(family of animal or subclass of plant)',
		forms: ['idae$'],
	},
	{
		head: '-iformes',
		lang: EDS.latin,
		gloss: '(order of animal)',
		forms: ['iformes$'],
	},
	{
		head: '-ilis',
		lang: EDS.latin,
		gloss: '-ile',
		forms: ['ile$', 'il'],
	},
	{
		head: '-ina',
		lang: EDS.latin,
		gloss: '(subtribe or superorder of animal)',
		forms: ['ina$'],
	},
	{
		head: '-inae',
		lang: EDS.latin,
		gloss: '(superfamily of animal or subtribe of non-animal)',
		forms: ['inae$'],
	},
	{
		head: '-ineae',
		lang: EDS.latin,
		gloss: '(suborder of non-animal)',
		forms: ['ineae$'],
	},
	{
		head: '-ini',
		lang: EDS.latin,
		gloss: '(tribe of animal)',
		forms: ['ini$'],
	},
	{
		head: '-ista',
		lang: EDS.latin,
		gloss: '-ist',
		forms: ['ista$', 'ist$'],
	},
	{
		head: '-itas',
		lang: EDS.latin,
		gloss: '(N)',
		forms: ['ity$', 'itie(?=s$)'],
	},
	{
		head: '-ites',
		lang: EDS.latin,
		gloss: '(taxon)',
		forms: ['ites$'],
	},
	{
		head: '-ium',
		lang: EDS.latin,
		gloss: '(used to form names of elements)',
		forms: ['ium$'],
	},
	{
		head: '-ius',
		lang: EDS.latin,
		gloss: '(N)',
		forms: ['ius$', 'ii$'],
	},
	{
		head: '-ivus',
		lang: EDS.latin,
		gloss: '-ive',
		forms: ['ive$', 'ivus$', 'iva$', 'ivum$'],
	},
	{
		head: '-nus',
		lang: EDS.latin,
		gloss: '(ADJ)',
		forms: ['(i?a)?n$'],
	},
	{
		head: '-oidae',
		lang: EDS.latin,
		gloss: '(epifamily of animal)',
		forms: ['oidae$'],
	},
	{
		head: '-oidea',
		lang: EDS.latin,
		gloss: '(superfamily of animal)',
		forms: ['oidea$'],
	},
	{
		head: '-odes',
		lang: EDS.latin,
		gloss: '(taxon)',
		forms: ['odes$'],
	},
	{
		head: '-olus',
		lang: EDS.latin,
		gloss: '(DIM)',
		forms: ['ol'],
	},
	{
		head: '-osus',
		lang: EDS.latin,
		gloss: '-ose, -ous',
		forms: ['oses$', 'osus$', 'osa$', 'osum$'],
	},
	{
		head: '-tus',
		lang: EDS.latin,
		gloss: '-ed',
		forms: ['tus$', 'ta$', 'tum$'],
	},
	{
		head: '-um',
		lang: EDS.latin,
		gloss: '(N)',
		forms: ['um$'],
	},
	{
		head: '-ulus',
		lang: EDS.latin,
		gloss: '(DIM)',
		forms: ['ul'],
	},
	{
		head: '-us',
		lang: EDS.latin,
		gloss: '(N)',
		forms: ['us$', 'i$'],
	},
	{
		head: 'abies',
		lang: EDS.latin,
		gloss: 'silver fir',
		forms: ['abiet', 'abies$'],
	},
	{
		head: 'acetabulum',
		lang: EDS.latin,
		gloss: 'saucer',
		forms: ['acetabul'],
	},
	{
		head: 'Aegyptus',
		lang: EDS.latin,
		gloss: 'Egypt',
		forms: ['a?egypto?'],
	},
	{
		head: 'Afer',
		lang: EDS.latin,
		gloss: 'African',
		forms: ['afro'],
	},
	{
		head: 'Africa',
		lang: EDS.latin,
		gloss: 'Africa',
		forms: ['africa', 'africo'],
	},
	{
		head: 'alveus',
		lang: EDS.latin,
		gloss: 'pit',
		forms: ['alve'],
	},
	{
		head: 'anellus',
		lang: EDS.latin,
		gloss: 'little ring',
		forms: ['ann?ell?'],
	},
	{
		head: 'avis',
		lang: EDS.latin,
		gloss: 'bird',
		forms: ['av'],
	},
	{
		head: 'centrum',
		lang: EDS.latin,
		gloss: 'center',
		forms: ['centr'],
	},
	{
		head: 'citrus',
		lang: EDS.latin,
		gloss: 'citrus',
		forms: ['citr'],
	},
	{
		head: 'colo',
		lang: EDS.latin,
		gloss: 'strain',
		forms: ['colo', 'col'],
	},
	{
		head: 'conus',
		lang: EDS.latin,
		gloss: 'cone',
		forms: ['con'],
	},
	{
		head: 'fistula',
		lang: EDS.latin,
		gloss: 'pipe',
		forms: ['fistul'],
	},
	{
		head: 'flagellum',
		lang: EDS.latin,
		gloss: 'whip',
		forms: ['flagell'],
	},
	{
		head: 'fulgeo',
		lang: EDS.latin,
		gloss: 'blaze',
		forms: ['fulg'],
	},
	{
		head: 'fungus',
		lang: EDS.latin,
		gloss: 'fungus',
		forms: ['fung'],
	},
	{
		head: 'gradior',
		lang: EDS.latin,
		gloss: 'step',
		forms: ['grad'],
	},
	{
		head: 'iuba',
		lang: EDS.latin,
		gloss: 'mane',
		forms: ['iuba', 'juba'],
	},
	{
		head: 'lorica',
		lang: EDS.latin,
		gloss: 'breastplate',
		forms: ['loric'],
	},
	{
		head: 'luna',
		lang: EDS.latin,
		gloss: 'moon',
		forms: ['luna', 'lune$'],
	},
	{
		head: 'malva',
		lang: EDS.latin,
		gloss: 'mallow',
		forms: ['malva'],
	},
	{
		head: 'mamma',
		lang: EDS.latin,
		gloss: 'breast',
		forms: ['mamm'],
	},
	{
		head: 'mille',
		lang: EDS.latin,
		gloss: 'thousand',
		forms: ['mill[ei]?'],
	},
	{
		head: 'mollusca',
		lang: EDS.latin,
		gloss: 'a kind of soft nut with a thin shell',
		forms: ['mollusc'],
	},
	{
		head: 'musca',
		lang: EDS.latin,
		gloss: 'fly',
		forms: ['musc'],
	},
	{
		head: 'neuter',
		lang: EDS.latin,
		gloss: 'neither',
		forms: ['neuter', 'neutr'],
	},
	{
		head: 'per',
		lang: EDS.latin,
		gloss: 'through',
		forms: ['per'],
	},
	{
		head: 'planta',
		lang: EDS.latin,
		gloss: 'sprout',
		forms: ['plant'],
	},
	{
		head: 'porus',
		lang: EDS.latin,
		gloss: 'pore',
		forms: ['por'],
	},
	{
		head: 'pro',
		lang: EDS.latin,
		gloss: 'for',
		forms: ['pro'],
	},
	{
		head: 'repo',
		lang: EDS.latin,
		gloss: 'creep',
		forms: ['rept'],
	},
	{
		head: 'ros',
		lang: EDS.latin,
		gloss: 'rose',
		forms: ['ros'],
	},
	{
		head: 'rota',
		lang: EDS.latin,
		gloss: 'wheel',
		forms: ['rot'],
	},
	{
		head: 'sero',
		lang: EDS.latin,
		gloss: 'sow',
		forms: ['sat'],
	},
	{
		head: 'tardus',
		lang: EDS.latin,
		gloss: 'slow',
		forms: ['tardi', 'tard'],
	},
	{
		head: 'verus',
		lang: EDS.latin,
		gloss: 'true',
		forms: ['ver', 'vera$', 'verus$', 'verum$'],
	},
	{
		head: 'viridis',
		lang: EDS.latin,
		gloss: 'green',
		forms: ['viridi'],
	},
	{
		head: 'virus',
		lang: EDS.latin,
		gloss: 'poison',
		forms: ['vir'],
	},
	// ANCIENT GREEK
	{
		head: '-a',
		lang: EDS.greek,
		gloss: '(N)',
		forms: ['a$'],
	},
	{
		head: '-árkhēs',
		lang: EDS.greek,
		gloss: 'leader',
		forms: ['arche', 'arch'],
	},
	{
		head: '-eidḗs',
		lang: EDS.greek,
		gloss: '(ADJ)',
		forms: ['o?id'],
	},
	{
		head: '-ikós',
		lang: EDS.greek,
		gloss: '(ADJ)',
		forms: ['ic'],
	},
	{
		head: '-íon',
		lang: EDS.greek,
		gloss: '(N)',
		forms: ['ion$'],
	},
	{
		head: '-ismós',
		lang: EDS.greek,
		gloss: '(N)',
		forms: ['ism'],
	},
	{
		head: '-istḗs',
		lang: EDS.greek,
		gloss: '-ist',
		forms: ['ist'],
	},
	{
		head: '-îtis',
		lang: EDS.greek,
		gloss: '(disease)',
		forms: ['itis$'],
	},
	{
		head: '-nos',
		lang: EDS.greek,
		gloss: '(ADJ)',
		forms: ['a?n$'],
	},
	{
		head: '-on',
		lang: EDS.greek,
		gloss: '(N)',
		forms: ['on'],
	},
	{
		head: '-tos',
		lang: EDS.greek,
		gloss: '(ADJ)',
		forms: ['th'], // eg. amaranth
	},
	{
		head: '-ōsis',
		lang: EDS.greek,
		gloss: '(state)',
		forms: ['osis$', 'sis$'],
	},
	{
		head: '-ṓtēs',
		lang: EDS.greek,
		gloss: '(N)',
		forms: ['ota$', 'ta$'],
	},
	{
		head: '-phóros',
		lang: EDS.greek,
		gloss: 'bearing',
		forms: ['phor'],
	},
	{
		head: 'ắkănthă',
		lang: EDS.greek,
		gloss: 'thorn',
		forms: ['acantho?'],
	},
	{
		head: 'aktís',
		lang: EDS.greek,
		gloss: 'ray',
		forms: ['actino'],
	},
	{
		head: 'a-',
		lang: EDS.greek,
		gloss: 'un-',
		forms: ['a'],
	},
	{
		head: 'ácholos',
		lang: EDS.greek,
		gloss: 'not choleric',
		forms: ['achole'], // https://en.wikipedia.org/wiki/Acholeplasmataceae ?
	},
	{
		head: 'agărĭkón',
		lang: EDS.greek,
		gloss: 'Phellinus pomaceus',
		forms: ['agarico?'],
	},
	{
		head: 'agăthĭ́s',
		lang: EDS.greek,
		gloss: 'ball of thread',
		forms: ['agathis$', 'agath'],
	},
	{
		head: 'aílouros',
		lang: EDS.greek,
		gloss: 'cat',
		forms: ['ailuro'],
	},
	{
		head: 'aithḗr',
		lang: EDS.greek,
		gloss: 'sky, ether',
		forms: ['ether', 'eth'],
	},
	{
		head: 'álpha',
		lang: EDS.greek,
		gloss: 'alpha',
		forms: ['alpha'],
	},
	{
		head: 'amānī́tēs',
		lang: EDS.greek,
		gloss: 'mushroom',
		forms: ['amanita$', 'amanit'],
	},
	{
		head: 'ămoibḗ',
		lang: EDS.greek,
		gloss: 'change',
		forms: ['amoebo?'],
	},
	{
		head: 'amníon',
		lang: EDS.greek,
		gloss: 'bowl',
		forms: ['amnio'],
	},
	{
		head: 'amphí',
		lang: EDS.greek,
		gloss: 'both',
		forms: ['amphi'],
	},
	{
		head: 'an-',
		lang: EDS.greek,
		gloss: 'un-',
		forms: ['an(?=[aehiou])'], // "any-" impossible since no greek word starts y-, it's always hy-
	},
	{
		head: 'aná',
		lang: EDS.greek,
		gloss: 'up',
		forms: ['ana'],
	},
	{
		head: 'anḗr',
		lang: EDS.greek,
		gloss: 'man',
		forms: ['andro'],
	},
	{
		head: 'angeîon',
		lang: EDS.greek,
		gloss: 'receptacle',
		forms: ['angio'],
	},
	{
		head: 'ánthos',
		lang: EDS.greek,
		gloss: 'flower',
		forms: ['antho'],
	},
	{
		head: 'ánthrōpos',
		lang: EDS.greek,
		gloss: 'human',
		forms: ['anthropo', 'anthrope$'],
	},
	{
		head: 'arkhaîos',
		lang: EDS.greek,
		gloss: 'ancient',
		forms: ['archaeo', 'archae'],
	},
	{
		head: 'árthron',
		lang: EDS.greek,
		gloss: 'joint',
		forms: ['arthro', 'arthr'],
	},
	{
		head: 'autós',
		lang: EDS.greek,
		gloss: 'self',
		forms: ['auto'],
	},
	{
		head: 'baktēríā',
		lang: EDS.greek,
		gloss: 'rod',
		forms: ['bacteri'],
	},
	{
		head: 'bíos',
		lang: EDS.greek,
		gloss: 'life',
		forms: ['bio', 'bi'],
	},
	{
		head: 'Boréās',
		lang: EDS.greek,
		gloss: 'north',
		forms: ['boreo'],
	},
	{
		head: 'botánē',
		lang: EDS.greek,
		gloss: 'herb',
		forms: ['botan'],
	},
	{
		head: 'bradús',
		lang: EDS.greek,
		gloss: 'slow',
		forms: ['brady'],
	},
	{
		head: 'brakhíōn',
		lang: EDS.greek,
		gloss: 'arm',
		forms: ['brachio'],
	},
	{
		head: 'brômă',
		lang: EDS.greek,
		gloss: 'food',
		forms: ['broma'],
	},
	{
		head: 'brúon',
		lang: EDS.greek,
		gloss: 'moss',
		forms: ['bryo'],
	},
	{
		head: 'dáktulos',
		lang: EDS.greek,
		gloss: 'finger',
		forms: ['dactyl'],
	},
	{
		head: 'deinós',
		lang: EDS.greek,
		gloss: 'terrible',
		forms: ['deino', 'dino'], // dinosaur was coined very early and uses an older romanization
	},
	{
		head: 'dérma',
		lang: EDS.greek,
		gloss: 'skin',
		forms: ['derm'],
	},
	{
		head: 'deúteros',
		lang: EDS.greek,
		gloss: 'second',
		forms: ['deutero'],
	},
	{
		head: 'dís',
		lang: EDS.greek,
		gloss: 'twice',
		forms: ['di'],
	},
	{
		head: 'drósos',
		lang: EDS.greek,
		gloss: 'dew',
		forms: ['droso'],
	},
	{
		head: 'ekhînos',
		lang: EDS.greek,
		gloss: 'hedgehog',
		forms: ['echino'],
	},
	{
		head: 'éktasis',
		lang: EDS.greek,
		gloss: 'extension',
		forms: ['ectas'],
	},
	{
		head: 'ḗlektron',
		lang: EDS.greek,
		gloss: 'amber',
		forms: ['electron', 'electro', 'electr'],
	},
	{
		head: 'en',
		lang: EDS.greek,
		gloss: 'in',
		forms: ['en'],
	},
	{
		head: 'entós',
		lang: EDS.greek,
		gloss: 'within',
		forms: ['endo', 'ento'],
	},
	{
		head: 'ēṓs',
		lang: EDS.greek,
		gloss: 'dawn',
		forms: ['eo'],
	},
	{
		head: 'epí',
		lang: EDS.greek,
		gloss: 'on',
		forms: ['epi', 'ep'],
	},
	{
		head: 'étumon',
		lang: EDS.greek,
		gloss: 'true meaning',
		forms: ['etymo'],
	},
	{
		head: 'eǘs',
		lang: EDS.greek,
		gloss: 'good',
		forms: ['eu'],
	},
	{
		head: 'gastḗr',
		lang: EDS.greek,
		gloss: 'belly',
		forms: ['gastro'],
	},
	{
		head: 'gê',
		lang: EDS.greek,
		gloss: 'earth',
		forms: ['geo'],
	},
	{
		head: 'geneá',
		lang: EDS.greek,
		gloss: 'birth',
		forms: ['genea'],
	},
	{
		head: 'génesis',
		lang: EDS.greek,
		gloss: 'birth',
		forms: ['genesis$', 'genet'],
	},
	{
		head: 'génos',
		lang: EDS.greek,
		gloss: 'birth',
		forms: ['gen'],
	},
	{
		head: 'glḗnē',
		lang: EDS.greek,
		gloss: 'eye',
		forms: ['gleno'],
	},
	{
		head: 'gnáthos',
		lang: EDS.greek,
		gloss: 'jaw',
		forms: ['gnatho', 'gnath'],
	},
	{
		head: 'grámma',
		lang: EDS.greek,
		gloss: 'letter',
		forms: ['gram$'],
	},
	{
		head: 'graphḗ',
		lang: EDS.greek,
		gloss: 'writing',
		forms: ['graph'],
	},
	{
		head: 'gunḗ',
		lang: EDS.greek,
		gloss: 'woman',
		forms: ['gyneco', 'gyn'],
	},
	{
		head: 'Hāídēs',
		lang: EDS.greek,
		gloss: 'Hades',
		forms: ['hade'],
	},
	{
		head: 'haplóos',
		lang: EDS.greek,
		gloss: 'single',
		forms: ['haplo'],
	},
	{
		head: 'háptō',
		lang: EDS.greek,
		gloss: 'touch',
		forms: ['hapto', 'hapt'],
	},
	{
		head: 'hēdonḗ',
		lang: EDS.greek,
		gloss: 'pleasure',
		forms: ['hedon'],
	},
	{
		head: 'hḗlĭos',
		lang: EDS.greek,
		gloss: 'sun',
		forms: ['helio?'],
	},
	{
		head: 'hélmins',
		lang: EDS.greek,
		gloss: 'parasitic worm',
		forms: ['helminth'],
	},
	{
		head: 'hḗmisus',
		lang: EDS.greek,
		gloss: 'half',
		forms: ['hemi'],
	},
	{
		head: 'hólos',
		lang: EDS.greek,
		gloss: 'whole',
		forms: ['holo'],
	},
	{
		head: 'húdōr',
		lang: EDS.greek,
		gloss: 'water',
		forms: ['hydro'],
	},
	{
		head: 'hū́lē',
		lang: EDS.greek,
		gloss: 'wood',
		forms: ['yl'], // eg. methyl
	},
	{
		head: 'hupér',
		lang: EDS.greek,
		gloss: 'over',
		forms: ['hyper'],
	},
	{
		head: 'hupó',
		lang: EDS.greek,
		gloss: 'under',
		forms: ['hypo'],
	},
	{
		head: 'ikhthū́s',
		lang: EDS.greek,
		gloss: 'fish',
		forms: ['ichthy'],
	},
	{
		head: 'ísos',
		lang: EDS.greek,
		gloss: 'equal',
		forms: ['iso'],
	},
	{
		head: 'kálymma',
		lang: EDS.greek,
		gloss: 'cover',
		forms: ['calymm'],
	},
	{
		head: 'kardía',
		lang: EDS.greek,
		gloss: 'heart',
		forms: ['cardio', 'cardia'],
	},
	{
		head: 'káruon',
		lang: EDS.greek,
		gloss: 'nut',
		forms: ['kary'],
	},
	{
		head: 'katá',
		lang: EDS.greek,
		gloss: 'down',
		forms: ['cata'],
	},
	{
		head: 'kephalḗ',
		lang: EDS.greek,
		gloss: 'head',
		forms: ['cephalo'],
	},
	{
		head: 'kéras',
		lang: EDS.greek,
		gloss: 'horn',
		forms: ['ceroto', 'ceros$'],
	},
	{
		head: 'khaítē',
		lang: EDS.greek,
		gloss: 'flowing hair',
		forms: ['chaeto'],
	},
	{
		head: 'khlōrós',
		lang: EDS.greek,
		gloss: 'pale green',
		forms: ['chloro'],
	},
	{
		head: 'khoánē',
		lang: EDS.greek,
		gloss: 'funnel',
		forms: ['choano'],
	},
	{
		head: 'khóndros',
		lang: EDS.greek,
		gloss: 'grain',
		forms: ['chondr'],
	},
	{
		head: 'khordḗ',
		lang: EDS.greek,
		gloss: 'guts',
		forms: ['chord'],
	},
	{
		head: 'khŭmeíā',
		lang: EDS.greek,
		gloss: 'alchemy',
		forms: ['chem'],
	},
	{
		head: 'knídē',
		lang: EDS.greek,
		gloss: 'nettle',
		forms: ['cnid'],
	},
	{
		head: 'kontós',
		lang: EDS.greek,
		gloss: 'pole',
		forms: ['kont'],
	},
	{
		head: 'kotulēdṓn',
		lang: EDS.greek,
		gloss: 'cup-shaped cavity',
		forms: ['cotyledon'],
	},
	{
		head: 'khrôma',
		lang: EDS.greek,
		gloss: 'color',
		forms: ['chromo', 'chrome$', 'chrom'], // chromosome
	},
	{
		head: 'kinéō',
		lang: EDS.greek,
		gloss: 'move',
		forms: ['kino', 'cin'], // cin in CINema aCINonyx
	},
	{
		head: 'koîlos',
		lang: EDS.greek,
		gloss: 'hollow',
		forms: ['coelo'],
	},
	{
		head: 'krúos',
		lang: EDS.greek,
		gloss: 'cold',
		forms: ['cryo'],
	},
	{
		head: 'kruptós',
		lang: EDS.greek,
		gloss: 'hidden',
		forms: ['crypto', 'crypt'],
	},
	{
		head: 'kteís',
		lang: EDS.greek,
		gloss: 'comb',
		forms: ['cteno'],
	},
	{
		head: 'kŭ́ănos',
		lang: EDS.greek,
		gloss: 'dark blue',
		forms: ['cyano?'],
	},
	{
		head: 'kúklos',
		lang: EDS.greek,
		gloss: 'circle',
		forms: ['cyclio'], // cycliophora
	},
	{
		head: 'leukós',
		lang: EDS.greek,
		gloss: 'bright, white',
		forms: ['leuco?', 'leuko?'],
	},
	{
		head: 'lípos',
		lang: EDS.greek,
		gloss: 'fat',
		forms: ['lipo'],
	},
	{
		head: 'lĭ́thos',
		lang: EDS.greek,
		gloss: 'stone',
		forms: ['lite$', 'litho?'],
	},
	{
		head: 'lógos',
		lang: EDS.greek,
		gloss: 'word',
		forms: ['logue$', 'logo', 'log'],
	},
	{
		head: 'lúkos',
		lang: EDS.greek,
		gloss: 'wolf',
		forms: ['lyco', 'lyc'],
	},
	{
		head: 'lúsis',
		lang: EDS.greek,
		gloss: 'loosening',
		forms: ['lysis', 'lyso', 'lys'],
	},
	{
		head: 'măraínō',
		lang: EDS.greek,
		gloss: 'quench',
		forms: ['maran'],
	},
	{
		head: 'mástix',
		lang: EDS.greek,
		gloss: 'whip',
		forms: ['mastigo'],
	},
	{
		head: 'mēkhanḗ',
		lang: EDS.greek,
		gloss: 'machine',
		forms: ['mechan'],
	},
	{
		head: 'meíōn',
		lang: EDS.greek,
		gloss: 'less',
		forms: ['meio'],
	},
	{
		head: 'mélās',
		lang: EDS.greek,
		gloss: 'black',
		forms: ['melano?'],
	},
	{
		head: 'méthŭ',
		lang: EDS.greek,
		gloss: 'wine',
		forms: ['meth'],
	},
	{
		head: 'métron',
		lang: EDS.greek,
		gloss: 'measure',
		forms: ['meter', 'metr'],
	},
	{
		head: 'méros',
		lang: EDS.greek,
		gloss: 'part',
		forms: ['mere', 'mero'], // telomere, meronym
	},
	{
		head: 'mésos',
		lang: EDS.greek,
		gloss: 'middle',
		forms: ['meso'],
	},
	{
		head: 'metá',
		lang: EDS.greek,
		gloss: 'amid',
		forms: ['meta'],
	},
	{
		head: 'mikrós',
		lang: EDS.greek,
		gloss: 'small',
		forms: ['micro'],
	},
	{
		head: 'mítos',
		lang: EDS.greek,
		gloss: 'thread',
		forms: ['mito'],
	},
	{
		head: 'mítra',
		lang: EDS.greek,
		gloss: 'girdle',
		forms: ['mitri'], // Haplomitriopsida
	},
	{
		head: 'mónos',
		lang: EDS.greek,
		gloss: 'single',
		forms: ['monad', 'mono'],
	},
	{
		head: 'mōrós',
		lang: EDS.greek,
		gloss: 'slow',
		forms: ['moron', 'more$'],
	},
	{
		head: 'morphḗ',
		lang: EDS.greek,
		gloss: 'shape',
		forms: ['morph'],
	},
	{
		head: 'múkēs',
		lang: EDS.greek,
		gloss: 'fungus',
		forms: ['mycetes$', 'mycet', 'myces', 'myco'],
	},
	{
		head: 'nânos',
		lang: EDS.greek,
		gloss: 'dwarf',
		forms: ['nano'],
	},
	{
		head: 'nêma',
		lang: EDS.greek,
		gloss: 'thread',
		forms: ['nemato'],
	},
	{
		head: 'Nēmertḗs',
		lang: EDS.greek,
		gloss: 'Nemertes',
		forms: ['nemert'],
	},
	{
		head: 'néō',
		lang: EDS.greek,
		gloss: 'swim',
		forms: ['nect'],
	},
	{
		head: 'néos',
		lang: EDS.greek,
		gloss: 'new',
		forms: ['neo'],
	},
	{
		head: 'nephrós',
		lang: EDS.greek,
		gloss: 'kidney',
		forms: ['nephro'],
	},
	{
		head: 'nítron',
		lang: EDS.greek,
		gloss: 'washing soda',
		forms: ['nitro'],
	},
	{
		head: 'odṓn',
		lang: EDS.greek,
		gloss: 'tooth',
		forms: ['odont', 'odon'],
	},
	{
		head: 'oîstros',
		lang: EDS.greek,
		gloss: 'madness',
		forms: ['oestro', 'estro'],
	},
	{
		head: 'ónŭx',
		lang: EDS.greek,
		gloss: 'claw',
		forms: ['onycho?', 'onyx'],
	},
	{
		head: 'opísthios',
		lang: EDS.greek,
		gloss: 'rear',
		forms: ['opistho'],
	},
	{
		head: 'ópsis',
		lang: EDS.greek,
		gloss: 'appearance',
		forms: ['o?psida$', 'ops$'],
	},
	{
		head: 'oroseirá',
		lang: EDS.greek,
		gloss: 'mountain range',
		forms: ['orosir'],
	},
	{
		head: 'orthós',
		lang: EDS.greek,
		gloss: 'straight',
		forms: ['ortho'],
	},
	{
		head: 'ostéon',
		lang: EDS.greek,
		gloss: 'bone',
		forms: ['osteo', 'oste', 'ost'], // osteoarthritis, osteichthyes, teleost
	},
	{
		head: 'oxús',
		lang: EDS.greek,
		gloss: 'sharp',
		forms: ['oxy'],
	},
	{
		head: 'palaiós',
		lang: EDS.greek,
		gloss: 'old',
		forms: ['paleo'],
	},
	{
		head: 'pará',
		lang: EDS.greek,
		gloss: 'beside',
		forms: ['para'],
	},
	{
		head: 'perí',
		lang: EDS.greek,
		gloss: 'around',
		forms: ['peri'],
	},
	{
		head: 'phílos',
		lang: EDS.greek,
		gloss: 'loving',
		forms: ['phile$', 'philo', 'phil'],
	},
	{
		head: 'phóbos',
		lang: EDS.greek,
		gloss: 'fear',
		forms: ['phobe$', 'phob'],
	},
	{
		head: 'Phorōnís',
		lang: EDS.greek,
		gloss: 'Phoronis',
		forms: ['phoron'],
	},
	{
		head: 'phôs',
		lang: EDS.greek,
		gloss: 'light',
		forms: ['photo', 'phos'],
	},
	{
		head: 'phûkos',
		lang: EDS.greek,
		gloss: 'seaweed',
		forms: ['phyco', 'phyc'],
	},
	{
		head: 'phûlon',
		lang: EDS.greek,
		gloss: 'tribe',
		forms: ['phylo'],
	},
	{
		head: 'phutón',
		lang: EDS.greek,
		gloss: 'plant',
		forms: ['phyta$', 'phyte$', 'phyto', 'phyt'],
	},
	{
		head: 'pĭ́thēkos',
		lang: EDS.greek,
		gloss: 'ape',
		forms: ['pithecus$', 'pithec'],
	},
	{
		head: 'plắsmă',
		lang: EDS.greek,
		gloss: 'figure, image',
		forms: ['plasmat?'],
	},
	{
		head: 'platús',
		lang: EDS.greek,
		gloss: 'flat',
		forms: ['platy'],
	},
	{
		head: 'pláx',
		lang: EDS.greek,
		gloss: 'plate',
		forms: ['placo'],
	},
	{
		head: 'Ploútōn',
		lang: EDS.greek,
		gloss: 'Hades',
		forms: ['pluton?'],
	},
	{
		head: 'pnoḗ',
		lang: EDS.greek,
		gloss: 'breath',
		forms: ['pno'],
	},
	{
		head: 'póa',
		lang: EDS.greek,
		gloss: 'fodder',
		forms: ['po'],
	},
	{
		head: 'poús',
		lang: EDS.greek,
		gloss: 'foot',
		forms: ['pode?', 'pus'],
	},
	{
		head: 'pólis',
		lang: EDS.greek,
		gloss: 'city',
		forms: ['polis$', 'polit'],
	},
	{
		head: 'polús',
		lang: EDS.greek,
		gloss: 'many',
		forms: ['poly'],
	},
	{
		head: 'poús',
		lang: EDS.greek,
		gloss: 'foot',
		forms: ['podio', 'podo', 'puso', 'pod'], // eg. polypodiophyta, isopod, apusozoa
	},
	{
		head: 'Príapos',
		lang: EDS.greek,
		gloss: 'Priapus',
		forms: ['priap'],
	},
	{
		head: 'prōktós',
		lang: EDS.greek,
		gloss: 'anus',
		forms: ['proct'],
	},
	{
		head: 'próteros',
		lang: EDS.greek,
		gloss: 'anterior',
		forms: ['protero'],
	},
	{
		head: 'Prōteús',
		lang: EDS.greek,
		gloss: 'Proteus',
		forms: ['proteo?'],
	},
	{
		head: 'prôtos',
		lang: EDS.greek,
		gloss: 'first',
		forms: ['proto'],
	},
	{
		head: 'psukhḗ',
		lang: EDS.greek,
		gloss: 'soul',
		forms: ['psycho'],
	},
	{
		head: 'ptéris',
		lang: EDS.greek,
		gloss: 'male fern',
		forms: ['pterido?'],
	},
	{
		head: 'pterón',
		lang: EDS.greek,
		gloss: 'feather',
		forms: ['ptero', 'ptera'],
	},
	{
		head: 'ptérux',
		lang: EDS.greek,
		gloss: 'wing',
		forms: ['pteryg'],
	},
	{
		head: 'ptússō',
		lang: EDS.greek,
		gloss: 'fold',
		forms: ['ptyxis$'],
	},
	{
		head: 'rhipídion',
		lang: EDS.greek,
		gloss: 'bellows',
		forms: ['rhipid'],
	},
	{
		head: 'rhī́s',
		lang: EDS.greek,
		gloss: 'nose',
		forms: ['rhino'],
	},
	{
		head: 'rhómbos',
		lang: EDS.greek,
		gloss: 'rhombus',
		forms: ['rhombo'],
	},
	{
		head: 'rhúax',
		lang: EDS.greek,
		gloss: 'lava flow',
		forms: ['rhyac'],
	},
	{
		head: 'rhúnkhos',
		lang: EDS.greek,
		gloss: 'snout',
		forms: ['rhynch'],
	},
	{
		head: 'sárx',
		lang: EDS.greek,
		gloss: 'flesh',
		forms: ['sarco'],
	},
	{
		head: 'saûros',
		lang: EDS.greek,
		gloss: 'lizard',
		forms: ['saur'],
	},
	{
		head: 'sídēros',
		lang: EDS.greek,
		gloss: 'iron',
		forms: ['sider'],
	},
	{
		head: 'skótos',
		lang: EDS.greek,
		gloss: 'darkness',
		forms: ['scoto'],
	},
	{
		head: 'skopéō',
		lang: EDS.greek,
		gloss: 'examine',
		forms: ['scope$', 'scop'],
	},
	{
		head: 'sôma',
		lang: EDS.greek,
		gloss: 'body',
		forms: ['somat', 'some$', 'som'], // somatic chromosome
	},
	{
		head: 'sophía',
		lang: EDS.greek,
		gloss: 'wisdom',
		forms: ['sopho', 'soph'], // philoSOPHY, SOPHOmore, philoSOPHic
	},
	{
		head: 'spérma',
		lang: EDS.greek,
		gloss: 'seed',
		forms: ['sperm'],
	},
	{
		head: 'sphágnos',
		lang: EDS.greek,
		gloss: 'kind of moss',
		forms: ['sphagn'],
	},
	{
		head: 'sphaîra',
		lang: EDS.greek,
		gloss: 'ball',
		forms: ['sphere?'],
	},
	{
		head: 'sporā́',
		lang: EDS.greek,
		gloss: 'seed',
		forms: ['spore$', 'spor'],
	},
	{
		head: 'statherós',
		lang: EDS.greek,
		gloss: 'stable',
		forms: ['stather'],
	},
	{
		head: 'stegănós',
		lang: EDS.greek,
		gloss: 'watertight',
		forms: ['stegano?'],
	},
	{
		head: 'stégos',
		lang: EDS.greek,
		gloss: 'roof',
		forms: ['stego?'],
	},
	{
		head: 'stenós',
		lang: EDS.greek,
		gloss: 'narrow',
		forms: ['steno?'],
	},
	{
		head: 'stoikheîon',
		lang: EDS.greek,
		gloss: 'element',
		forms: ['stoichio'],
	},
	{
		head: 'stóma',
		lang: EDS.greek,
		gloss: 'mouth',
		forms: ['stom'],
	},
	{
		head: 'sún',
		lang: EDS.greek,
		gloss: 'with',
		forms: ['syn', 'sym'],
	},
	{
		head: 'takhús',
		lang: EDS.greek,
		gloss: 'fast',
		forms: ['tachy'],
	},
	{
		head: 'tainíā',
		lang: EDS.greek,
		gloss: 'band',
		forms: ['ten'], // synteny
	},
	{
		head: 'téleios',
		lang: EDS.greek,
		gloss: 'complete',
		forms: ['tele'], // teleost
	},
	{
		head: 'télos',
		lang: EDS.greek,
		gloss: 'end',
		forms: ['telo'],
	},
	{
		head: 'Tēthū́s',
		lang: EDS.greek,
		gloss: 'Tethys',
		forms: ['tethys?'],
	},
	{
		head: 'tetra-',
		lang: EDS.greek,
		gloss: 'four',
		forms: ['tetra'],
	},
	{
		head: 'títhēmi',
		lang: EDS.greek,
		gloss: 'put',
		forms: ['thesis$', 'thet'],
	},
	{
		head: 'theós',
		lang: EDS.greek,
		gloss: 'god',
		forms: ['theos?'],
	},
	{
		head: 'thḗr',
		lang: EDS.greek,
		gloss: 'beast',
		forms: ['thero?'],
	},
	{
		head: 'thēríon',
		lang: EDS.greek,
		gloss: 'beast',
		forms: ['theria'],
	},
	{
		head: 'thermós',
		lang: EDS.greek,
		gloss: 'hot',
		forms: ['thermo?'],
	},
	{
		head: 'thríx',
		lang: EDS.greek,
		gloss: 'hair',
		forms: ['thrich', 'trich'], // gastrotrica drops the h for some reason
	},
	{
		head: 'thŭreós',
		lang: EDS.greek,
		gloss: 'shield',
		forms: ['thyreo', 'thyro'],
	},
	{
		head: 'tónos',
		lang: EDS.greek,
		gloss: 'stretch',
		forms: ['ton'],
	},
	{
		head: 'tópos',
		lang: EDS.greek,
		gloss: 'place',
		forms: ['topo', 'top'],
	},
	{
		head: 'xénos',
		lang: EDS.greek,
		gloss: 'alien',
		forms: ['xeno', 'xen'],
	},
	{
		head: 'zôion',
		lang: EDS.greek,
		gloss: 'animal',
		forms: ['zoo', 'zoa', 'zo'],
	},
	/*
	{
		head: '(mochanoise)',
		lang: EDS.mocha,
		gloss: 'gay',
		forms: ['kippi', 'boi', 'snueg'],
	},
	*/
];

// compile langs automatically

const etymLangData = [];
etymData.forEach(o => {
	if (etymLangData.includes(o.lang))
		return;
	etymLangData.push(o.lang);
});