/* exported jpData */

const jpData = [
	// GENKI I ch 1
	{
		name: 'Genki I ch 1',
		lemmas: [
			{
				lemma: 'あの',
				gloss: 'um',
				cat: 'interj',
			},
			{
				lemma: '今',
				reading: 'いま',
				gloss: 'now',
				cat: 'adv',
			},
			{
				lemma: '英語',
				reading: 'えいご',
				gloss: 'English language',
				cat: 'n',
			},
			{
				lemma: 'ええ',
				gloss: 'yes',
				cat: 'interj',
			},
			{
				lemma: '学生',
				reading: 'がくせい',
				gloss: 'student',
				cat: 'n',
			},
			{
				lemma: '-語',
				reading: '-ご',
				gloss: '(language suff.)',
				cat: 'suff',
			},
			{
				lemma: '午後',
				reading: 'ごご',
				gloss: 'PM',
				cat: 'n',
			},
			{
				lemma: '午前',
				reading: 'ごぜん',
				gloss: 'AM',
				cat: 'n',
			},
			{
				lemma: '-さい',
				gloss: '(years old suff.)',
				cat: 'suff',
			},
			{
				lemma: '-さん',
				gloss: '(Mr/Ms suff.)',
				cat: 'suff',
			},
			{
				lemma: '時',
				reading: 'じ',
				gloss: 'hour',
				cat: 'n',
			},
			{
				lemma: '-人',
				reading: '-じん',
				gloss: '(people suff.)',
				cat: 'suff',
			},
			{
				lemma: '選考',
				reading: 'せんこう',
				gloss: 'major',
				cat: 'n',
			},
			{
				lemma: '洗生',
				reading: 'せんせい',
				gloss: 'teacher',
				cat: 'n',
			},
			{
				lemma: 'そうです',
				gloss: 'that\'s right',
				cat: 'n',
			},
			{
				lemma: 'そうですか',
				gloss: 'is that so',
				cat: 'n',
			},
			{
				lemma: '大学',
				reading: 'だいがく',
				gloss: 'university',
				cat: 'n',
			},
			{
				lemma: '電話',
				reading: 'でんわ',
				gloss: 'phone',
				cat: 'n',
			},
			{
				lemma: '友達',
				reading: 'ともだち',
				gloss: 'friend',
				cat: 'n',
			},
			{
				lemma: '名前',
				reading: 'なまえ',
				gloss: 'name',
				cat: 'n',
			},
			{
				lemma: '何',
				reading: 'なに',
				gloss: 'what',
				cat: 'n',
			},
			{
				lemma: '日本',
				reading: 'にほん',
				gloss: 'Japan',
				cat: 'n',
			},
			{
				lemma: '-年生',
				reading: '-ねんせい',
				gloss: '(year student suff.)',
				cat: 'suff',
			},
			{
				lemma: 'はい',
				gloss: 'yes',
				cat: 'interj',
			},
			{
				lemma: '半',
				reading: 'はん',
				gloss: 'half',
				cat: 'n',
			},
			{
				lemma: '番号',
				reading: 'ばんごう',
				gloss: 'number',
				cat: 'suff',
			},
			{
				lemma: '留学生',
				reading: 'りゅうがくせい',
				gloss: 'international student',
				cat: 'n',
			},
			{
				lemma: '私',
				reading: 'わたし',
				gloss: 'I; me',
				cat: 'n',
			},
			{
				lemma: 'アメリカ',
				gloss: 'US',
				cat: 'n',
			},
			{
				lemma: 'イギリス',
				gloss: 'UK',
				cat: 'n',
			},
			{
				lemma: 'オーストラリア',
				gloss: 'Australia',
				cat: 'n',
			},
			{
				lemma: '韓国',
				reading: 'かんこく',
				gloss: 'Korea',
				cat: 'n',
			},
			{
				lemma: 'スウェーデン',
				gloss: 'Sweden',
				cat: 'n',
			},
			{
				lemma: '中国',
				reading: 'ちゅうごく',
				gloss: 'China',
				cat: 'n',
			},
			{
				lemma: '科学',
				reading: 'かがく',
				gloss: 'science',
				cat: 'n',
			},
			{
				lemma: 'アジア研究',
				reading: 'アジアけんきゅう',
				gloss: 'asian studies',
				cat: 'n',
			},
			{
				lemma: '経済',
				reading: 'けいざい',
				gloss: 'economics',
				cat: 'n',
			},
			{
				lemma: '国際関係',
				reading: 'こくさいかんけい',
				gloss: 'international relations',
				cat: 'n',
			},
			{
				lemma: 'コンピューター',
				gloss: 'computer',
				cat: 'n',
			},
			{
				lemma: '人類学',
				reading: 'じんるいがく',
				gloss: 'anthropology',
				cat: 'n',
			},
			{
				lemma: '政治',
				reading: 'せいじ',
				gloss: 'politics',
				cat: 'n',
			},
			{
				lemma: 'ビジネス',
				gloss: 'business',
				cat: 'n',
			},
			{
				lemma: '文学',
				reading: 'ぶんがく',
				gloss: 'literature',
				cat: 'n',
			},
			{
				lemma: '歴史',
				reading: 'れきし',
				gloss: 'history',
				cat: 'n',
			},
			{
				lemma: '仕事',
				reading: 'しごと',
				gloss: 'work',
				cat: 'n',
			},
			{
				lemma: '医者',
				reading: 'いしゃ',
				gloss: 'doctor',
				cat: 'n',
			},
			{
				lemma: '会社員',
				reading: 'かいしゃいん',
				gloss: 'office worker',
				cat: 'n',
			},
			{
				lemma: '高校生',
				reading: 'こうこうせい',
				gloss: 'highschooler',
				cat: 'n',
			},
			{
				lemma: '主婦',
				reading: 'しゅふ',
				gloss: 'housewife',
				cat: 'n',
			},
			{
				lemma: '大学院生',
				reading: 'だいがくいんせい',
				gloss: 'graduate student',
				cat: 'n',
			},
			{
				lemma: '大学生',
				reading: 'だいがくせい',
				gloss: 'university student',
				cat: 'n',
			},
			{
				lemma: '弁護士',
				reading: 'べんごし',
				gloss: 'lawyer',
				cat: 'n',
			},
			{
				lemma: 'お母さん',
				reading: 'おかあさん',
				gloss: 'mother',
				cat: 'n',
			},
			{
				lemma: 'お父さん',
				reading: 'おとうさん',
				gloss: 'father',
				cat: 'n',
			},
			{
				lemma: 'お姉さん',
				reading: 'おねえさん',
				gloss: 'older sister',
				cat: 'n',
			},
			{
				lemma: 'お兄さん',
				reading: 'おにいさん',
				gloss: 'older brother',
				cat: 'n',
			},
			{
				lemma: '妹',
				reading: 'いもうと',
				gloss: 'younger sister',
				cat: 'n',
			},
			{
				lemma: '弟',
				reading: 'おとうと',
				gloss: 'younger brother',
				cat: 'n',
			},
		],
	},
	// GENKI I ch 2
	{
		name: 'Genki I ch 2',
		lemmas: [
			{
				lemma: 'これ',
				gloss: 'this',
				cat: 'name',
			},
		],
	},
];