/* exported NUTRITION_LOADED, nutrition_main, SCATTER_CONTROL */
/* global elementData, toURL */
const DEBUG = document.URL[0].toLowerCase() === 'f'; // file:// vs. http(s)://

const MOLAR_MASS = {
	H: 1.008,
	B: 10.81,
	C: 12.011,
	N: 14.007,
	O: 15.999,
	F: 18.998403162,
	Na: 22.99,
	Mg: 24.305,
	P: 30.974,
	S: 32.06,
	Cl: 35.45,
	K: 39.098,
	Ca: 40.078,
	V: 50.9415,
	Cr: 51.9961,
	Mn: 54.938,
	Fe: 55.845,
	Ni: 58.6934,
	Co: 58.933194,
	Cu: 63.546,
	Zn: 65.38,
	Se: 78.971,
	Mo: 95.95,
	I: 126.9,
};

const CAVEATS = {
	general: 'This nutrition label was programmatically generated by Luna&rsquo;s <i>nutrition.js</i> and may not be wholly accurate.',
	unofficial: '<div class="nutritionLine">* - DV not established by the FDA; I&rsquo;m just basing this off health studies, or other health agencies, or pulling the values straight out of my ass. Don&rsquo;t actually include this on real food packaging.</div>',
};

/** @param {string} symbol */
function getElemColor(symbol){
	return elementData.find(datum => datum.symbol === symbol).properties.modelColor;
}

function fancyList(header = '', items = [], headerLevel = 3, listType = 'ul'){
	const container = document.createElement('div');
	container.classList.add('fancyList');
	// header
	const h = document.createElement('h' + headerLevel);
	h.innerHTML = header;
	container.appendChild(h);
	// list
	const l = document.createElement(listType);
	container.appendChild(l);
	items.forEach(item => {
		const li = document.createElement('li');
		li.appendChild(typeof item === 'string' ? document.createTextNode(item) : item);
		l.appendChild(li);
	});
	return container;
}

/**
 * @param {Nutrient} nutrient_x
 * @param {Nutrient} nutrient_y
 */
function showScatter(nutrient_x, nutrient_y){
	const composition = this.composition;
	const pairs = [];
	for (const elem in composition){
		pairs.push([elem, composition[elem], getElemColor(elem)]);
	}
	const [x, y, text] = [
		Food.foods.map(food => food.nutrient(nutrient_x)),
		Food.foods.map(food => food.nutrient(nutrient_y)),
		Food.foods.map(food => food.name),
	];
	const scatterURL = 'chart.html?data=' + toURL({
		type: 'scatter',
		x,
		y,
		text,
		fill: 'green',
		labels: true,
		logx: true,
		logy: true,
	});
	document.getElementById('scatter').src = scatterURL;
}

function nutrition_main(){
	// foods
	Food.foods.sort((a, b) => a.name < b.name ? -1 : 1);
	const foodContainer = document.getElementById('food');
	foodContainer.innerHTML = '';
	foodContainer.appendChild(fancyList('Foods',
		Food.foods.map(food => food.linkShowPie)
	));
	// nutrients
	const nutrientContainer = document.getElementById('nutrient');
	nutrientContainer.innerHTML = '';
	nutrientContainer.appendChild(fancyList('Nutrients',
		Nutrient.nutrients.map(nutrient => nutrient.linkShowBar)
	));
	// list of todo
	const todoContainer = document.getElementById('todo');
	todoContainer.innerHTML = '';
	todoContainer.appendChild(fancyList('Missing Densities',
		Nutrient.nutrients
			.filter(nutrient => nutrient.density === 1)
			.map(nutrient => nutrient.a)
	));
	// scatter
	SCATTER_CONTROL.init();
	// ternary
	SCATTER_CONTROL.ternary();
	SCATTER_CONTROL.ternary2();
	// defaults...
	Food.OnionYellow.show();
	Nutrient.POTASSIUM.showBar();
	// checks...
	const urls = [];
	Food.foods.forEach(f => {
		// source check
		if (urls.includes(f.source))
			console.warn(`${f.name} has duplicate source: ${f.source}`);
		else
			urls.push(f.source);
		// sugar + sodium check
		if (!f.ignoreNutrientWarning){
			if (!f.nutrient(Nutrient.SODIUM))
				console.warn(`${f.name} lacks sodium info (${f.source})`);
			if (!f.nutrient(NutrientGroup.SUGARS))
				console.warn(`${f.name} lacks sugar info (${f.source})`);
		}
	});
	// done
	console.info('nutrition.js ran successfully');
}

/**
 * @param {Nutrient} nutrient
 * @param {number} value
 */
function fdaround(nutrient, value){
	// https://www.fda.gov/files/food/published/Food-Labeling-Guide-%28PDF%29.pdf
	let interval = 0.1; // nearest integer; 0.5 = "nearest half"
	switch (nutrient){
		// p. 129 (Appendix H)
		case NutrientGroup.CALORIES:
			interval = 50 < value ? 10 : 5;
			break;
		case NutrientGroup.FATS:
			interval = value < 0.5 ? 1 : value < 5 ? 0.5 : 1;
			break;
		case Nutrient.CHOLESTEROL:
			interval = value < 2 ? 4 : value < 5 ? 1 : 5;
			break;
		case Nutrient.SODIUM:
		case Nutrient.POTASSIUM:
			interval = value < 5 ? 10 : value < 140 ? 5 : 10;
			break;
		case NutrientGroup.CARBOHYDRATES:
		case Nutrient.FIBER:
		case NutrientGroup.SUGARS:
		case Nutrient.ALCOHOL:
		case NutrientGroup.PROTEINS:
			interval = 1;
	}
	return Math.round(value / interval) * interval;
}

const SCATTER_CONTROL = {
	elem: {
		/** @returns {HTMLSelectElement} */
		get x(){
			return document.getElementById('nutrientX');
		},
		/** @returns {HTMLSelectElement} */
		get y(){
			return document.getElementById('nutrientY');
		},
	},
	/** @type {Nutrient} */
	x: undefined,
	/** @type {Nutrient} */
	y: undefined,
	init(){
		// add nutrients to selectors...
		Nutrient.nutrients.forEach(nutrient => {
			[this.elem.x, this.elem.y].forEach((selector, i) => {
				const option = document.createElement('option');
				option.innerHTML = option.value = nutrient.name;
				option.id = `SELECTOR_${i}_${nutrient.name}`;
				selector.appendChild(option);
			});
		});
		document.getElementById('SELECTOR_0_Sodium').selected = 'selected';
		document.getElementById('SELECTOR_1_Sugars').selected = 'selected';
		this.reread();
	},
	reread(){
		// reread x
		this.x = Nutrient.fromString(this.elem.x.value);
		this.y = Nutrient.fromString(this.elem.y.value);
		// reread y
		this.update();
	},
	ternary(){
		const URL = 'chart.html?data=' + toURL({
			type: 'ternary',
			x: Food.foods.map(f => f.nutrient(NutrientGroup.PROTEINS) * 4),
			y: Food.foods.map(f => f.nutrient(NutrientGroup.FATS) * 9),
			z: Food.foods.map(f => f.nutrient(NutrientGroup.CALORIES_FROM_CARBOHYDRATES)),
			text: Food.foods.map(f => f.name),
			labels: true,
			axes: {x: 'Protein', y: 'Fat', z: 'Carbs'},
		});
		document.getElementById('ternary').src = URL;
	},
	ternary2(){
		const C_AXIS1 = Math.max(...Food.foods.map(f => f.nutrient(Nutrient.SODIUM)));
		const C_AXIS2 = Math.max(...Food.foods.map(f => f.nutrient(NutrientGroup.SUGARS)));
		// const MAX_AC = Math.max(...Food.foods.map(f => f.nutrient(NutrientGroup.ACIDITY)));
		const C_AXIS3 = Math.max(...Food.foods.map(f => PROTEINS.estimate_glutamic_acid(f))); // f.nutrient(Nutrient.GLUTAMIC_ACID))or NutrientGroup.PROTEINS
		const URL = 'chart.html?data=' + toURL({
			type: 'ternary',
			x: Food.foods.map(f => f.nutrient(Nutrient.SODIUM) / C_AXIS1),
			y: Food.foods.map(f => f.nutrient(NutrientGroup.SUGARS) / C_AXIS2),
			z: Food.foods.map(f => PROTEINS.estimate_glutamic_acid(f) / C_AXIS3),
			text: Food.foods.map(f => f.name),
			labels: true,
			axes: {x: 'Salty', y: 'Sweet', z: 'Savory'},
		});
		document.getElementById('ternary2').src = URL;
	},
	update(){
		showScatter(this.x, this.y);
	},
};


class SourcedObject {
	/**
	 * @param {string} name
	 * @param {string?} source URL
	 */
	constructor(name, source){
		this.name = name;
		this.source = source || `https://en.wikipedia.org/wiki/${name}`;
	}
	get a(){
		const elem = document.createElement('a');
		elem.innerHTML = this.name;
		elem.href = this.source;
		return elem;
	}
}


class FoodGroup extends SourcedObject {
	constructor(name){
		super(name);
		FoodGroup.groups.push(this);
	}
	/** @returns {FoodGroupAverage} */
	get median(){
		// todo
		return;
	}
}
/** @type {FoodGroup[]} */
FoodGroup.groups = [];
FoodGroup.OTHER = new FoodGroup('Other');
FoodGroup.DAIRY = new FoodGroup('Dairy');
FoodGroup.FRUIT = new FoodGroup('Fruit');
FoodGroup.GRAIN = new FoodGroup('Grain');
FoodGroup.MEAT = new FoodGroup('Meat');
FoodGroup.SWEETS = new FoodGroup('Sweets');
FoodGroup.VEG = new FoodGroup('Vegetables');


class Nutrient extends SourcedObject {
	/**
	 * @param {string} name
	 * @param {{string: number}} composition
	 * @param {number} DV - p. 167 https://www.fda.gov/files/food/published/Food-Labeling-Guide-%28PDF%29.pdf
	 * @param {number} density g/cm^3 - as close to 37C @ 1 atm as I can find...
	 * @param {string?} source URL
	 * @param {boolean?} unofficialDV
	 */
	constructor(name, composition, DV = 0, density = 1, source = undefined, unofficialDV = false){
		super(name, source);
		this.DV = DV;
		this.compositionAmt = composition;
		/** @type {number} g/cm^3 */
		this.density = density;
		this.unofficialDV = unofficialDV;
		Nutrient.nutrients.push(this);
	}
	get composition(){
		const MM = this.molarMass;
		const mass = {};
		for (const elem in this.compositionAmt)
			mass[elem] = this.compositionAmt[elem] * MOLAR_MASS[elem] / MM;
		return mass;
	}
	get molarMass(){
		let s = 0;
		for (const elem in this.compositionAmt)
			s += this.compositionAmt[elem] * MOLAR_MASS[elem];
		return s;
	}
	// HTML crap
	get linkShowBar(){
		const elem = document.createElement('span');
		elem.classList.add('button');
		elem.innerHTML = this.name;
		elem.onclick = () => this.showBar();
		return elem;
	}
	// methods
	showBar(){
		const x = [], y = [];
		Food.foods.forEach(food => {
			const fy = food.nutrient(this);
			// console.debug(food.name, fy, this.name);
			if (fy){
				x.push(food.name);
				y.push(fy);
			}
		});
		const data = {
			pruneY: Number.MIN_VALUE,
			reverse: true,
			sort: true,
			type: 'bar',
			x,
			y,
			maxBars: 20,
		};
		const barURL = 'chart.html?data=' + toURL(data);
		document.getElementById('bar').src = barURL;
		console.info(`nutrition.js displaying foods rich in ${this.name}`);
	}
	// static
	/** @param {string} s */
	static fromString(s){
		return Nutrient.nutrients.find(nutrient => nutrient.name === s);
	}
}
/** @type {Nutrient[]} */
Nutrient.nutrients = [];


class NutrientGroup extends Nutrient {
	/** Eg. "Calories", "Carbohydrates"
	 * @param {string} name
	 * @param {number} DV
	 * @param {NutrientAmount[]} nutrientWeights [Nutrient, Weight]
	 * @param {boolean} unofficialDV - for some nutrients, the FDA hasn't established guidelines; the figures provided are based on health studies.
	 */
	constructor(name, DV = 0, nutrientWeights = [], unofficialDV = false){
		super(name, {}, DV, undefined, undefined, unofficialDV);
		this.nutrientWeights = nutrientWeights;
		NutrientGroup.groups.push(this);
	}
	/**
	 * @param {Food} food
	 * @returns {number}
	 */
	value(food, useUnitMass = false){
		return this.nutrientWeights
			.map(na => food.nutrient(na.nutrient, useUnitMass) * na.amount)
			.reduce((a, b) => a+b);
	}
}
/** @type {NutrientGroup[]} */
NutrientGroup.groups = [];


class NutrientAmount {
	/**
	 * @param {Nutrient} nutrient
	 * @param {number} amount
	 */
	constructor(nutrient, amount){
		this.nutrient = nutrient;
		this.amount = amount;
	}
}


class Food extends SourcedObject {
	/**
	 * @param {string} name
	 * @param {*} properties incl. composition := Nutrient[], group := FoodGroup
	 * @param {string?} source URL
	 */
	constructor(name, properties, source){
		super(name, source);
		this.properties = properties;
		Food.foods.push(this);
	}
	get composition(){
		const c = {};
		this.nutrients.forEach(nutrientAmount => {
			const [nutrient, amount] = [nutrientAmount.nutrient, nutrientAmount.amount];
			for (const elem in nutrient.composition){
				const delta = nutrient.composition[elem] * amount / this.unitMass;
				if (c[elem])
					c[elem] += delta;
				else
					c[elem] = delta;
			}
		});
		return c;
	}
	get compositionUnit(){
		const COMPOSITION = this.composition;
		const c = {};
		for (const nutrient in COMPOSITION)
			c[nutrient] = COMPOSITION[nutrient] * this.measures.unit;
		return c;
	}
	get densityEstimate(){
		return this.nutrients
			.map(na => na.nutrient.density * na.amount / this.unitMass)
			.reduce((a, b) => a+b, 0);
	}
	/** @returns {FoodGroup} */
	get group(){
		return this.properties.group || FoodGroup.OTHER;
	}
	/** @returns {boolean} */
	get ignoreNutrientWarning(){
		return this.properties.ignoreNutrientWarning || false;
	}
	get measures(){
		return this.properties.measures || {};
	}
	nutritionLabel(useUnitMass = false){
		// https://upload.wikimedia.org/wikipedia/commons/7/75/US_Nutritional_Fact_Label_2.svg
		// https://www.fda.gov/files/food/published/Food-Labeling-Guide-%28PDF%29.pdf
		function appendHR(){
			elem.appendChild(document.createElement('hr'));
		}
		const elem = document.createElement('div');
		const title = document.createElement('h3');
		title.innerHTML = 'Nutrition Facts';
		elem.appendChild(title);
		// measures
		/*
		const measureContainer = document.createElement('div');
		elem.appendChild(measureContainer);
		for (const measure in this.measures){
			const measureElem = document.createElement('div');
			measureElem.innerHTML = `${measure}: ${this.measures[measure]} g`;
			measureContainer.appendChild(measureElem);
		}*/
		// eslint-disable-next-line max-len
		elem.innerHTML += `<div class="DVheader">&nbsp;<div class="dv">Amount per ${useUnitMass ? 'unit (' + this.unitMass + 'g)' : '100g'}</div></div>`;
		// calories
		appendHR();
		const calories = document.createElement('div');
		calories.classList.add('calories');
		// eslint-disable-next-line max-len
		calories.innerHTML = `<b>Calories</b> ${fdaround(NutrientGroup.CALORIES, this.nutrient(NutrientGroup.CALORIES, useUnitMass))}`;
		// eslint-disable-next-line max-len
		const CFF = fdaround(NutrientGroup.CALORIES, 9*this.nutrient(NutrientGroup.FATS, useUnitMass));
		if (CFF)
			calories.innerHTML += `<br>Calories from Fat ${CFF}`;
		elem.appendChild(calories);
		// central sector
		appendHR();
		const DVHEADER = '<div class="DVheader">&nbsp;<div class="dv">% Daily Value</div></div>';
		elem.innerHTML += DVHEADER;
		const MAIN_NUTRIENTS = [
			[NutrientGroup.FATS, true],
			[Nutrient.CHOLESTEROL, true, true],
			[Nutrient.SODIUM, true, true],
			[Nutrient.POTASSIUM, true, true],
			[NutrientGroup.CARBOHYDRATES, true],
			[Nutrient.FIBER, false],
			[NutrientGroup.SUGARS, false],
			[Nutrient.ALCOHOL, true],
			[NutrientGroup.PROTEINS, true],
		];
		let ADD_CAVEAT = false;
		MAIN_NUTRIENTS.forEach(datum => {
			/** @type {[Nutrient, boolean, boolean]} */
			const [nutrient, bold, usemg] = datum;
			const trueValue = this.nutrient(nutrient, useUnitMass);
			const value = fdaround(nutrient, trueValue * (usemg ? 1e3 : 1));
			if (!value)
				return;
			const lineItem = document.createElement('div');
			lineItem.classList.add('nutritionLine');
			if (bold)
				lineItem.innerHTML = `<b>${nutrient.a.outerHTML}</b>`;
			else
				lineItem.innerHTML = '&mdash; ' + nutrient.a.outerHTML;
			lineItem.innerHTML += ' ' + value + (usemg ? 'm' : '') + 'g';
			// % Daily Value
			let INNER = Math.round(100 * trueValue / nutrient.DV) + '%';
			if (nutrient.unofficialDV){
				INNER += '*';
				ADD_CAVEAT = true;
			}
			if (nutrient.DV)
				lineItem.innerHTML += ' <div class="dv"><b>' + INNER + '</b></div>';
			elem.appendChild(lineItem);
		});
		// vitamins and minerals w/ %DV
		appendHR();
		elem.innerHTML += DVHEADER;
		// eslint-disable-next-line max-len
		Nutrient.nutrients.filter(nutrient => nutrient.DV && !MAIN_NUTRIENTS.map(x => x[0]).includes(nutrient))
			.forEach(nutrient => {
				const value = Math.round(100 * this.nutrient(nutrient, useUnitMass) / nutrient.DV);
				if (!value)
					return;
				const lineItem = document.createElement('div');
				lineItem.classList.add('nutritionLine');
				lineItem.innerHTML = nutrient.a.outerHTML;
				let INNER = value + '%';
				if (nutrient.unofficialDV){
					INNER += '*';
					ADD_CAVEAT = true;
				}
				lineItem.innerHTML += '<div class="dv">' + INNER + '</div>';
				elem.appendChild(lineItem);
			});
		// caveat
		appendHR();
		const caveatElem = document.createElement('div');
		elem.appendChild(caveatElem);
		caveatElem.classList.add('nutritionNote');
		caveatElem.innerHTML = CAVEATS.general;
		if (ADD_CAVEAT)
			caveatElem.innerHTML += CAVEATS.unofficial;
		return elem;
	}
	/** @returns {NutrientAmount[]} */
	get nutrients(){
		return this.properties.nutrients;
	}
	/** @returns {number} g */
	get unitMass(){
		return this.measures.unit || 100;
	}
	// HTML crap
	get linkShowPie(){
		const elem = document.createElement('span');
		elem.classList.add('button');
		elem.innerHTML = this.name;
		elem.onclick = () => this.show();
		return elem;
	}
	// methods
	/**
	 * @param {Nutrient} n
	 * @param {boolean} useUnitMass
	 */
	nutrient(n, useUnitMass = false){
		const DIVISOR = 100 / (useUnitMass ? this.unitMass : 100);
		if (n instanceof NutrientGroup)
			return n.value(this, useUnitMass);
		// eslint-disable-next-line max-len
		return (maybe_n => maybe_n ? maybe_n.amount / DIVISOR : 0)(this.nutrients.find(na => na.nutrient === n));
	}
	show(){
		this.showNutrition();
		this.showPie();
	}
	showNutrition(){
		const container = document.getElementById('foodLabel_100g');
		container.innerHTML = '';
		container.appendChild(this.nutritionLabel(false));
		// unit
		const container_u = document.getElementById('foodLabel_unit');
		container_u.innerHTML = '';
		if (this.measures.unit)
			container_u.appendChild(this.nutritionLabel(true));
	}
	showPie(){
		const composition = this.composition;
		const pairs = [];
		for (const elem in composition){
			pairs.push([elem, composition[elem], getElemColor(elem)]);
		}
		const pieURL = 'chart.html?data=' + toURL({
			type: 'pie',
			pairs,
			labels: true,
		});
		document.getElementById('pie').src = pieURL;
		console.info(`nutrition.js displaying composition of ${this.name}`);
	}
}
/** @type {Food[]} */
Food.foods = [];

class FoodGroupAverage extends Food {
	/** @param {FoodGroup} group */
	constructor(group){
		super(`${group.name} (median)`, {
			group,
			nutrients: Nutrient.nutrients.map(nutrient => {
				const data = Food.foods
					.filter(food => food.group === group) // ONLY this group
					.map(food => food.nutrient(nutrient)) // get nutrient value
					.filter(x => x); // remove zeroes
				data.sort();
				const [i, j] = [(data.length % 2 ? Math.floor : Math.ceil)(data.length/2),
					Math.ceil(data.length/2)];
				const median = (data[i] + data[j])/2;
				return new NutrientAmount(nutrient, median);
			}).filter(x => isFinite(x.amount)), // filter out undefineds
		});
	}
}


// NUTRIENTS
// DV as of Aug 2023 https://www.fda.gov/media/135301/download?attachment
/* The following nutrients do not have established DVs, but have been shown to have positive effects when consumed in these quantities:
	Phytosterols - 2g - https://en.wikipedia.org/wiki/Phytosterol#FDA
*/
Nutrient.WATER = new Nutrient('Water', {H: 2, O: 1}, 0, 0.99336);
Nutrient.NITROGEN = new Nutrient('Nitrogen', {}); // ???
Nutrient.PROTEIN = new Nutrient('Protein (Unspecified)', {C: 6, H: 13, N: 1, O: 2}, 0, 1.5); // Leucine
Nutrient.FAT = new Nutrient('Fat (Unspecified)', {C: 18, H: 36, O: 2}, 0, 0.895); // Stearic Acid
Nutrient.ASH = new Nutrient('Ash', {}); // ???
Nutrient.FIBER = new Nutrient('Fiber', {C: 12, H: 20, O: 10}, 28, 1.5); // Cellulose
Nutrient.SUGAR = new Nutrient('Sugar (Unspecified)', {C: 6, H: 12, O: 6}, 0, 1.55);
Nutrient.SUCROSE = new Nutrient('Sucrose', {C: 12, H: 22, O: 11}, 0, 1.587);
Nutrient.GLUCOSE = new Nutrient('Glucose', {C: 6, H: 12, O: 6}, 0, 1.54);
Nutrient.FRUCTOSE = new Nutrient('Fructose', {C: 6, H: 12, O: 6}, 0, 1.694);
Nutrient.LACTOSE = new Nutrient('Lactose', {C: 12, H: 22, O: 11}, 0, 1.525);
Nutrient.MALTOSE = new Nutrient('Maltose', {C: 12, H: 22, O: 11}, 0, 1.54);
Nutrient.GALACTOSE = new Nutrient('Galactose', {C: 6, H: 12, O: 6}, 0, 1.5);
Nutrient.STARCH = new Nutrient('Starch', {C: 6, H: 10, O: 5});
// Oligosaccharides
Nutrient.RAFFINOSE = new Nutrient('Raffinose', {C: 18, H: 32, O: 16});
Nutrient.STACHYOSE = new Nutrient('Stachyose', {C: 24, H: 42, O: 21});
Nutrient.VERBASCOSE = new Nutrient('Verbascose', {C: 12, H: 22, O: 11}); // unknown composition
// Fats
// Proteins
Nutrient.GLUTAMIC_ACID = new Nutrient('Glutamic Acid', {C: 5, H: 9, N: 1, O: 4}, 0, 1.4601);
// Minerals
Nutrient.CALCIUM = new Nutrient('Calcium', {Ca: 1}, 1300e-3);
Nutrient.IRON = new Nutrient('Iron', {Fe: 1}, 18e-3);
Nutrient.MAGNESIUM = new Nutrient('Magnesium', {Mg: 1}, 420e-3);
Nutrient.PHOSPHORUS = new Nutrient('Phosphorus', {P: 1}, 1250e-3);
Nutrient.POTASSIUM = new Nutrient('Potassium', {K: 1}, 4700e-3);
Nutrient.SODIUM = new Nutrient('Sodium', {Na: 1}, 2.3);
Nutrient.ZINC = new Nutrient('Zinc', {Zn: 1}, 11e-3);
Nutrient.COPPER = new Nutrient('Copper', {Cu: 1}, 0.9e-3);
Nutrient.MANGANESE = new Nutrient('Manganese', {Mn: 1}, 2.3e-3);
Nutrient.IODINE = new Nutrient('Iodine', {I: 1}, 150e-6);
Nutrient.SELENIUM = new Nutrient('Selenium', {Se: 1}, 55e-6);
Nutrient.MOLYBDENUM = new Nutrient('Molybdenum', {Mo: 1}, 45e-6);
Nutrient.CHLORIDE = new Nutrient('Chloride', {Cl: 1}, 2300e-3);
Nutrient.CHROMIUM = new Nutrient('Chromium', {Cr: 1}, 35e-6);
Nutrient.BORON = new Nutrient('Boron', {B: 1}, 1.125e-3, undefined, undefined, true);
Nutrient.FLUORIDE = new Nutrient('Fluoride', {F: 1}, 4, undefined, undefined, true); // https://web.archive.org/web/20181113060244/http://www.nationalacademies.org/hmd/~/media/Files/Activity%20Files/Nutrition/DRI-Tables/2_%20RDA%20and%20AI%20Values_Vitamin%20and%20Elements.pdf?la=en
Nutrient.VANADIUM = new Nutrient('Vanadium', {V: 1}, 12e-6, undefined, undefined, true);
Nutrient.NICKEL = new Nutrient('Nickel', {V: 1}, 85e-6, undefined, undefined, true);
// A
Nutrient.RETINOL = new Nutrient('Retinol', {C: 20, H: 30, O: 1});
Nutrient.CAROTENE_ALPHA = new Nutrient('α-Carotene', {C: 40, H: 56});
Nutrient.CAROTENE_BETA = new Nutrient('β-Carotene', {C: 40, H: 56}, 1, 'https://en.wikipedia.org/wiki/%CE%92-Carotene');
Nutrient.CRYPTOXANTHIN_BETA = new Nutrient('β-Cryptoxanthin', {C: 40, H: 56, O: 1});
Nutrient.CRYPTOXANTHIN_ALPHA = new Nutrient('α-Cryptoxanthin', {C: 40, H: 56, O: 1}); // ???
// B
Nutrient.THIAMIN = new Nutrient('Vitamin B1 (Thiamin)', {C: 12, H: 17, N: 4, O: 1, S: 1}, 1.2e-3);
Nutrient.RIBOFLAVIN = new Nutrient('Vitamin B2 (Riboflavin)', {C: 17, H: 20, N: 4, O: 6}, 1.3e-3);
Nutrient.NIACIN = new Nutrient('Vitamin B3 (Niacin)', {C: 6, H: 5, N: 1, O: 2}, 16e-3, 1.473, 'https://en.wikipedia.org/wiki/Vitamin_B3');
Nutrient.CHOLINE = new Nutrient('Vitamin B4 (Choline)', {C: 5, H: 14, N: 1, O: 1}, 550e-3);
Nutrient.PANTOTHENIC_ACID = new Nutrient('Vitamin B5 (Pantothenic Acid)', {C: 9, H: 17, N: 1, O: 5}, 5e-3, 1.266);
Nutrient.VITAMIN_B6 = new Nutrient('Vitamin B6', {C: 8, H: 10, N: 1, O: 6, P: 1}, 1.7e-3, 1.638); // Pyridoxal Phosphate
Nutrient.BIOTIN = new Nutrient('Vitamin B7 (Biotin)', {C: 10, H: 16, N: 2, O: 3, S: 1}, 30e-6);
Nutrient.FOLATE = new Nutrient('Vitamin B9 (Folate)', {C: 19, H: 19, N: 7, O: 6}, 400e-6, 1.6, 'https://en.wikipedia.org/wiki/Folate');
Nutrient.VITAMIN_B12 = new Nutrient('Vitamin B12 (Cobalamin)', {C: 63, H: 88, Co: 1, N: 14, O: 14, P: 1}, 2.4e-6);
// C
Nutrient.VITAMIN_C = new Nutrient('Vitamin C', {C: 6, H: 8, O: 6}, 90e-3, 1.694);
// D
Nutrient.VITAMIN_D2 = new Nutrient('Vitamin D2 (Ergocalciferol)', {C: 28, H: 44, O: 1});
Nutrient.VITAMIN_D3 = new Nutrient('Vitamin D3 (Cholecalciferol)', {C: 27, H: 44, O: 1});
Nutrient._25_HYDROXYCHOLECALCIFEROL = new Nutrient('Calcifediol', {C: 27, H: 44, O: 2});
// E
Nutrient.TOCOPHEROL_ALPHA = new Nutrient('α-Tocopherol', {C: 29, H: 50, O: 2}, 0, 0.95, 'https://en.wikipedia.org/wiki/%CE%91-Tocopherol');
Nutrient.TOCOPHEROL_BETA = new Nutrient('β-Tocopherol', {C: 28, H: 48, O: 2});
Nutrient.TOCOPHEROL_GAMMA = new Nutrient('γ-Tocopherol', {C: 28, H: 48, O: 2});
Nutrient.TOCOPHEROL_DELTA = new Nutrient('δ-Tocopherol', {C: 27, H: 46, O: 2});
Nutrient.TOCOTRIENOL_ALPHA = new Nutrient('α-Tocotrienol', {C: 29, H: 44, O: 2});
Nutrient.TOCOTRIENOL_GAMMA = new Nutrient('γ-Tocotrienol', {C: 28, H: 42, O: 2});
// K
Nutrient.PHYLLOQUINONE = new Nutrient('Phytomenadione', {C: 31, H: 46, O: 2}); // Phytomenadione
Nutrient.DIHYDROPHYLLOQUINONE = new Nutrient('Dihydrophylloquinone', {C: 31, H: 50, O: 4}); // ???
Nutrient.MENAQUINONE_4 = new Nutrient('Menatetrenone', {C: 31, H: 40, O: 2});
// Cholesterol and Phytosterols
Nutrient.CHOLESTEROL = new Nutrient('Cholesterol', {C: 27, H: 46, O: 1}, 300e-3, 1.052, 'https://en.wikipedia.org/wiki/Cholesterol');
Nutrient.CAMPESTEROL = new Nutrient('Campesterol', {C: 28, H: 48, O: 1});
Nutrient.SITOSTEROL_BETA = new Nutrient('β-Sitosterol', {C: 29, H: 50, O: 1});
Nutrient.STIGMASTEROL = new Nutrient('Stigmasterol', {C: 29, H: 48, O: 1});
Nutrient.ERGOSTEROL = new Nutrient('Ergosterol', {C: 28, H: 44, O: 1});
Nutrient.ERGOSTA_7_ENOL = new Nutrient('Ergosta-7-enol', Nutrient.ERGOSTEROL.compositionAmt);
Nutrient.ERGOSTA_5_7_DIENOL = new Nutrient('Ergosta-5,7-dienol', Nutrient.ERGOSTEROL.compositionAmt);
Nutrient.ERGOSTA_7_22_DIENOL = new Nutrient('Ergosta-7,22-dienol', Nutrient.ERGOSTEROL.compositionAmt);
// misc Carotenoids
Nutrient.CIS_LUTEIN = new Nutrient('Cis-Lutein', {C: 40, H: 56, O: 2}); // ???
Nutrient.LUTEIN = new Nutrient('Lutein', {C: 40, H: 56, O: 2});
Nutrient.LYCOPENE = new Nutrient('Lycopene', {C: 40, H: 56});
Nutrient.ZEAXANTHIN = new Nutrient('Zeaxanthin', {C: 40, H: 56, O: 2});
// Isoflavones
Nutrient.DAIDZEIN = new Nutrient('Daidzein', {C: 15, H: 10, O: 4});
Nutrient.GENISTEIN = new Nutrient('Genistein', {C: 15, H: 10, O: 5});
Nutrient.DAIDZIN = new Nutrient('Daidzin', {C: 21, H: 20, O: 9});
Nutrient.GENISTIN = new Nutrient('Genistin', {C: 21, H: 20, O: 10});
Nutrient.GLYCITIN = new Nutrient('Glycitin', {C: 22, H: 22, O: 10});
// misc Xenoestrogens
Nutrient.COUMESTROL = new Nutrient('Coumestrol', {C: 15, H: 8, O: 5});
Nutrient.QUERCETIN = new Nutrient('Quercetin', {C: 15, H: 10, O: 7}, 0, 1.799, 'https://en.wikipedia.org/wiki/Quercetin'); // https://www.ars.usda.gov/ARSUserFiles/80400525/Data/Flav/Flav_R03.pdf
Nutrient.RESVERATROL = new Nutrient('Resveratrol', {C: 14, H: 12, O: 3});
// ?????
Nutrient.ALCOHOL = new Nutrient('Alcohol', {C: 2, H: 6, O: 1}, 0, 0.78945, 'https://en.wikipedia.org/wiki/Ethanol'); // Ethanol
Nutrient.BETAINE = new Nutrient('Betaine', {C: 5, H: 11, N: 1, O: 2}); // Trimethylglycine
Nutrient.CAFFEINE = new Nutrient('Caffeine', {C: 8, H: 10, N: 4, O: 2});
Nutrient.THEOBROMINE = new Nutrient('Theobromine', {C: 7, H: 8, N: 4, O: 2});
/*
const FATS = {
	formula: {
		mufa(n = 12){
			n -= 4;
			return {C: 4+n, H: 6+2*n, O: 2};
		},
		sfa(n = 3){
			n -= 2;
			return {C: 2+n, H: 4+2*n, O: 2};
		},
	},
};
FATS.SFA = Array.from(Array(25).keys())
	.map(n => new Nutrient(`SFA ${n}:0`, FATS.formula.sfa(n), 0, 0.85));
FATS.MUFA = Array.from(Array(25).keys())
	.map(n => new Nutrient(`MUFA ${n}:0`, FATS.formula.mufa(n), 0, 0.85));

NutrientGroup.FAT_SATURATED = new NutrientGroup('Saturated Fat', 0, FATS.SFA.map(x => new NutrientAmount(x, 1)));

NutrientGroup.FAT_MONOUNSATURATED = new NutrientGroup('Monounsaturated Fat', 0, [
	// new NutrientAmount(Nutrient.FAT, 1),
]);

NutrientGroup.FAT_POLYUNSATURATED = new NutrientGroup('Polyunsaturated Fat', 0, [
	// new NutrientAmount(Nutrient.FAT, 1),
]);

NutrientGroup.FAT_TRANS = new NutrientGroup('Trans Fat', 0, [
	// new NutrientAmount(Nutrient.FAT, 1),
]);
*/

const PROTEINS = {
	// average fraction of total protein which is glutamic acid
	get C(){
		function mean(arr){
			return arr.reduce((a, b) => a+b) / arr.length;
		}
		return this.C_ || (this.C_ = mean(Food.foods.filter(f => f.nutrient(Nutrient.GLUTAMIC_ACID))
			.map(f => f.nutrient(Nutrient.GLUTAMIC_ACID) / f.nutrient(NutrientGroup.PROTEINS))));
	},
	C_: 0,
	/** @param {Food} food */
	estimate_glutamic_acid(food){
		return food.nutrient(Nutrient.GLUTAMIC_ACID)
			|| food.nutrient(NutrientGroup.PROTEINS) * this.C;
	},
};

NutrientGroup.FATS = new NutrientGroup('Fat', 78, [
	new NutrientAmount(Nutrient.FAT, 1), // unspecified fat
	// new NutrientAmount(NutrientGroup.FAT_SATURATED, 1),
	// new NutrientAmount(NutrientGroup.FAT_MONOUNSATURATED, 1),
	// new NutrientAmount(NutrientGroup.FAT_POLYUNSATURATED, 1),
	// new NutrientAmount(NutrientGroup.FAT_TRANS, 1),
]);

NutrientGroup.PROTEINS = new NutrientGroup('Protein', 50, [
	new NutrientAmount(Nutrient.PROTEIN, 1),
	new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0), // duplicate
]);

NutrientGroup.SUGARS = new NutrientGroup('Sugars', 195, [
	new NutrientAmount(Nutrient.SUCROSE, 1),
	new NutrientAmount(Nutrient.GLUCOSE, 1),
	new NutrientAmount(Nutrient.FRUCTOSE, 1),
	new NutrientAmount(Nutrient.LACTOSE, 1),
	new NutrientAmount(Nutrient.MALTOSE, 1),
	new NutrientAmount(Nutrient.GALACTOSE, 1),
	new NutrientAmount(Nutrient.SUGAR, 1),
], true);

NutrientGroup.OLIGOSACCHARIDES = new NutrientGroup('Oligosaccharides', 0, [
	new NutrientAmount(Nutrient.RAFFINOSE, 1),
	new NutrientAmount(Nutrient.STACHYOSE, 1),
	new NutrientAmount(Nutrient.VERBASCOSE, 1),
]);

NutrientGroup.CALORIES_FROM_SUGAR = new NutrientGroup('Calories from Sugar', 0, [
	// Monosaccharides
	new NutrientAmount(Nutrient.FRUCTOSE, 3.75),
	new NutrientAmount(Nutrient.GALACTOSE, 3.7), // unknown
	new NutrientAmount(Nutrient.GLUCOSE, 3.719),
	// Disaccharides
	new NutrientAmount(Nutrient.LACTOSE, 3.94),
	new NutrientAmount(Nutrient.MALTOSE, 3.94), // unknown
	new NutrientAmount(Nutrient.SUCROSE, 3.943),
	// Oligosaccharides / Other
	new NutrientAmount(NutrientGroup.OLIGOSACCHARIDES, 3.94), // unknown
	new NutrientAmount(Nutrient.SUGAR, 3.8),
]);

NutrientGroup.CALORIES_FROM_CARBOHYDRATES = new NutrientGroup('Calories from Carbohydrates', 0, [
	new NutrientAmount(NutrientGroup.CALORIES_FROM_SUGAR, 1),
	new NutrientAmount(Nutrient.FIBER, 2),
	new NutrientAmount(Nutrient.STARCH, 4.1788), // heat of combustion
]);

NutrientGroup.CALORIES = new NutrientGroup('Calories', 0, [
	new NutrientAmount(NutrientGroup.CALORIES_FROM_CARBOHYDRATES, 1),
	new NutrientAmount(NutrientGroup.FATS, 9),
	new NutrientAmount(NutrientGroup.PROTEINS, 4),
	new NutrientAmount(Nutrient.ALCOHOL, 7.112), // ditto
]);

NutrientGroup.CARBOHYDRATES = new NutrientGroup('Carbohydrates', 275, [
	new NutrientAmount(NutrientGroup.SUGARS, 1),
	new NutrientAmount(NutrientGroup.OLIGOSACCHARIDES, 1),
	new NutrientAmount(Nutrient.FIBER, 1),
	new NutrientAmount(Nutrient.STARCH, 1),
]);

NutrientGroup.VITAMIN_A = new NutrientGroup('Vitamin A (μg RAE)', 900, [
	new NutrientAmount(Nutrient.RETINOL, 1),
	new NutrientAmount(Nutrient.CAROTENE_BETA, 1/12),
	new NutrientAmount(Nutrient.CAROTENE_ALPHA, 1/24),
	// new NutrientAmount(Nutrient.CAROTENE_GAMMA, 1/24),
	new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 1/24),
	new NutrientAmount(Nutrient.CRYPTOXANTHIN_ALPHA, 1/24), // ???
]);

NutrientGroup.VITAMIN_B = new NutrientGroup('Vitamin B (total)', 0, [
	new NutrientAmount(Nutrient.THIAMIN, 1),
	new NutrientAmount(Nutrient.RIBOFLAVIN, 1),
	new NutrientAmount(Nutrient.NIACIN, 1),
	new NutrientAmount(Nutrient.CHOLINE, 1),
	new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 1),
	new NutrientAmount(Nutrient.VITAMIN_B6, 1),
	new NutrientAmount(Nutrient.BIOTIN, 1),
	new NutrientAmount(Nutrient.FOLATE, 1),
	new NutrientAmount(Nutrient.VITAMIN_B12, 1),
]);

NutrientGroup.VITAMIN_D = new NutrientGroup('Vitamin D', 20e-6, [
	// new NutrientAmount(Nutrient.VITAMIN_D1, 1),
	new NutrientAmount(Nutrient.VITAMIN_D2, 1),
	new NutrientAmount(Nutrient.VITAMIN_D3, 1),
	// new NutrientAmount(Nutrient.VITAMIN_D4, 1),
	// new NutrientAmount(Nutrient.VITAMIN_D5, 1),
	new NutrientAmount(Nutrient._25_HYDROXYCHOLECALCIFEROL, 1),
]);

NutrientGroup.VITAMIN_E = new NutrientGroup('Vitamin E', 15e-3, [
	new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 1),
	new NutrientAmount(Nutrient.TOCOPHEROL_BETA, 1),
	new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 1),
	new NutrientAmount(Nutrient.TOCOPHEROL_DELTA, 1),
	new NutrientAmount(Nutrient.TOCOTRIENOL_ALPHA, 1),
	new NutrientAmount(Nutrient.TOCOTRIENOL_GAMMA, 1),
]);

NutrientGroup.VITAMIN_K = new NutrientGroup('Vitamin K', 120e-6, [
	new NutrientAmount(Nutrient.PHYLLOQUINONE, 1),
	new NutrientAmount(Nutrient.DIHYDROPHYLLOQUINONE, 1),
	new NutrientAmount(Nutrient.MENAQUINONE_4, 1),
]);

NutrientGroup.PHYTOSTEROLS = new NutrientGroup('Phytosterols', 2, [
	new NutrientAmount(Nutrient.CAMPESTEROL, 1),
	new NutrientAmount(Nutrient.SITOSTEROL_BETA, 1),
	new NutrientAmount(Nutrient.STIGMASTEROL, 1),
], true);

NutrientGroup.MYCOSTEROLS = new NutrientGroup('Mycosterols', 0, [
	new NutrientAmount(Nutrient.ERGOSTA_5_7_DIENOL, 1),
	new NutrientAmount(Nutrient.ERGOSTA_7_22_DIENOL, 1),
	new NutrientAmount(Nutrient.ERGOSTA_7_ENOL, 1),
	new NutrientAmount(Nutrient.ERGOSTEROL, 1),
], true);

NutrientGroup.STEROLS = new NutrientGroup('Sterols', 0, [
	new NutrientAmount(NutrientGroup.CHOLESTEROL, 1),
	new NutrientAmount(NutrientGroup.PHYTOSTEROLS, 1),
	new NutrientAmount(NutrientGroup.MYCOSTEROLS, 1),
]);

NutrientGroup.XANTHOPHYLLS = new NutrientGroup('Xanthophylls', 0, [
	new NutrientAmount(Nutrient.CIS_LUTEIN, 1),
	new NutrientAmount(Nutrient.LUTEIN, 1),
	new NutrientAmount(Nutrient.ZEAXANTHIN, 1),
]);

NutrientGroup.CAROTENOIDS = new NutrientGroup('Carotenoids', 0, [
	new NutrientAmount(NutrientGroup.XANTHOPHYLLS, 1),
	new NutrientAmount(Nutrient.CAROTENE_ALPHA, 1),
	new NutrientAmount(Nutrient.CAROTENE_BETA, 1),
	new NutrientAmount(Nutrient.LYCOPENE, 1),
]);

NutrientGroup.ISOFLAVONES = new NutrientGroup('Isoflavones', 0, [
	new NutrientAmount(Nutrient.DAIDZEIN, 1),
	new NutrientAmount(Nutrient.GENISTEIN, 1),
	new NutrientAmount(Nutrient.DAIDZIN, 1),
	new NutrientAmount(Nutrient.GENISTIN, 1),
	new NutrientAmount(Nutrient.GLYCITIN, 1),
]);

NutrientGroup.PHYTOESTROGENS = new NutrientGroup('Phytoestrogens', 0, [
	new NutrientAmount(NutrientGroup.ISOFLAVONES, 1),
	new NutrientAmount(Nutrient.QUERCETIN, 1),
	new NutrientAmount(Nutrient.RESVERATROL, 1),
	new NutrientAmount(Nutrient.SITOSTEROL_BETA, 1),
]);

NutrientGroup.XENOESTROGENS = new NutrientGroup('Xenoestrogens', 0, [
	new NutrientAmount(NutrientGroup.PHYTOESTROGENS, 1),
]);

// https://en.wikipedia.org/wiki/Template:Affinities_of_estrogen_receptor_ligands_for_the_ER%CE%B1_and_ER%CE%B2
NutrientGroup.XENOESTROGEN_ACTIVITY_A = new NutrientGroup('Xenoestrogens (Estradiol RBA ERα)', 5e-3, [
	new NutrientAmount(Nutrient.COUMESTROL, 0.09225),
	new NutrientAmount(Nutrient.DAIDZEIN, 0.0007),
	new NutrientAmount(Nutrient.GENISTEIN, 0.00445),
	new NutrientAmount(Nutrient.QUERCETIN, 0.0001), // max
	new NutrientAmount(Nutrient.RESVERATROL, 0.000032), // max
	new NutrientAmount(Nutrient.SITOSTEROL_BETA, 0.000875), // max
], true);
NutrientGroup.XENOESTROGEN_ACTIVITY_B = new NutrientGroup('Xenoestrogens (Estradiol RBA ERβ)', 5e-3, [
	new NutrientAmount(Nutrient.COUMESTROL, 0.64125),
	new NutrientAmount(Nutrient.DAIDZEIN, 0.7865),
	new NutrientAmount(Nutrient.GENISTEIN, 0.3342),
	new NutrientAmount(Nutrient.QUERCETIN, 0.0004), // max
	new NutrientAmount(Nutrient.SITOSTEROL_BETA, 0.00016), // max
], true);

NutrientGroup.METALS_TRANSITION = new NutrientGroup('Transition Metals (total)', 0, [
	new NutrientAmount(Nutrient.IRON, 1),
	new NutrientAmount(Nutrient.COPPER, 1),
	new NutrientAmount(Nutrient.MANGANESE, 1),
	new NutrientAmount(Nutrient.MOLYBDENUM, 1),
	new NutrientAmount(Nutrient.CHROMIUM, 1),
	new NutrientAmount(Nutrient.VANADIUM, 1),
	new NutrientAmount(Nutrient.NICKEL, 1),
	new NutrientAmount(Nutrient.VITAMIN_B12, 0.04433), // Cobalt
]);

NutrientGroup.METALS = new NutrientGroup('Metals (total)', 0, [
	new NutrientAmount(NutrientGroup.METALS_TRANSITION, 1),
	new NutrientAmount(Nutrient.CALCIUM, 1),
	new NutrientAmount(Nutrient.MAGNESIUM, 1),
	new NutrientAmount(Nutrient.POTASSIUM, 1),
	new NutrientAmount(Nutrient.SODIUM, 1),
	new NutrientAmount(Nutrient.ZINC, 1),
]);

NutrientGroup.MINERALS = new NutrientGroup('Minerals (total)', 0, [
	new NutrientAmount(NutrientGroup.METALS, 1),
	new NutrientAmount(Nutrient.PHOSPHORUS, 1),
	new NutrientAmount(Nutrient.IODINE, 1),
	new NutrientAmount(Nutrient.SELENIUM, 1),
	new NutrientAmount(Nutrient.CHLORIDE, 1),
	new NutrientAmount(Nutrient.BORON, 1),
	new NutrientAmount(Nutrient.FLUORIDE, 1),
]);

NutrientGroup.VITAMINS = new NutrientGroup('Vitamins (total)', 0, [
	new NutrientAmount(NutrientGroup.VITAMIN_A, 1),
	new NutrientAmount(NutrientGroup.VITAMIN_B, 1),
	new NutrientAmount(Nutrient.VITAMIN_C, 1),
	new NutrientAmount(NutrientGroup.VITAMIN_D, 1),
	new NutrientAmount(NutrientGroup.VITAMIN_E, 1),
	new NutrientAmount(NutrientGroup.VITAMIN_K, 1),
]);

NutrientGroup.VITAMINS_AND_MINERALS = new NutrientGroup('Vitamins & Minerals (total)', 0, [
	new NutrientAmount(NutrientGroup.VITAMINS, 1),
	new NutrientAmount(NutrientGroup.MINERALS, 1),
	new NutrientAmount(Nutrient.VITAMIN_B12, -0.04433), // Cobalt is counted twice
]);
/*
NutrientGroup.ACIDITY = new NutrientGroup('Acidity (Crude Est.)', 0, [
	new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 7-4.41), // appx
	new NutrientAmount(Nutrient.FOLATE, 7-4.41), // wild guess
	new NutrientAmount(Nutrient.VITAMIN_C, 7-4.1), // appx
	new NutrientAmount(Nutrient.GLUTAMIC_ACID, 7-4.1), // appx
]);*/

NutrientGroup.ANTIOXIDANTS = new NutrientGroup('Antioxidants', 0, [
	// https://en.wikipedia.org/wiki/List_of_antioxidants_in_food
	// vitamins
	new NutrientAmount(Nutrient.RETINOL, 1),
	new NutrientAmount(Nutrient.VITAMIN_C, 1),
	new NutrientAmount(NutrientGroup.VITAMIN_E, 1),
	// minerals
	new NutrientAmount(NutrientGroup.MANGANESE, 1),
	new NutrientAmount(NutrientGroup.IODINE, 1),
	new NutrientAmount(Nutrient.SELENIUM, 1),
	// misc
	new NutrientAmount(NutrientGroup.CAROTENOIDS, 1),
	new NutrientAmount(NutrientGroup.ISOFLAVONES, 1),
	new NutrientAmount(Nutrient.RESVERATROL, 1),
]);

// FOODS
Food.OnionYellow = new Food('Yellow Onion', {
	group: FoodGroup.VEG,
	measures: {
		unit: 143,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 90.1),
		new NutrientAmount(Nutrient.PROTEIN, 0.83),
		new NutrientAmount(Nutrient.FAT, 0.05),
		new NutrientAmount(Nutrient.ASH, 0.41),
		new NutrientAmount(Nutrient.FIBER, 2.71),
		new NutrientAmount(Nutrient.SUCROSE, 1.6),
		new NutrientAmount(Nutrient.GLUCOSE, 2.31),
		new NutrientAmount(Nutrient.FRUCTOSE, 1.91),
		new NutrientAmount(Nutrient.CALCIUM, 15e-3),
		new NutrientAmount(Nutrient.IRON, 0.28e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 9e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 34e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 182e-3),
		new NutrientAmount(Nutrient.SODIUM, 1e-3),
		new NutrientAmount(Nutrient.ZINC, 0.2e-3),
		new NutrientAmount(Nutrient.COPPER, 0.035e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.144e-3),
		new NutrientAmount(Nutrient.VITAMIN_C, 8.2e-3),
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 32e-3), // RED onions https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/790646/nutrients');
Food.PotatoSweet = new Food('Sweet Potato', {
	group: FoodGroup.VEG,
	measures: {
		cup: 133,
		unit: 130,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 77.3),
		new NutrientAmount(Nutrient.PROTEIN, 1.57),
		new NutrientAmount(Nutrient.FAT, 0.05),
		new NutrientAmount(Nutrient.ASH, 0.99),
		new NutrientAmount(Nutrient.FIBER, 3),
		new NutrientAmount(Nutrient.SUCROSE, 2.52),
		new NutrientAmount(Nutrient.GLUCOSE, 0.96),
		new NutrientAmount(Nutrient.FRUCTOSE, 0.7),
		new NutrientAmount(Nutrient.STARCH, 12.6),
		new NutrientAmount(Nutrient.CALCIUM, 30e-3),
		new NutrientAmount(Nutrient.IRON, 0.61e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 25e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 47e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 337e-3),
		new NutrientAmount(Nutrient.SODIUM, 55e-3),
		new NutrientAmount(Nutrient.ZINC, 0.3e-3),
		new NutrientAmount(Nutrient.COPPER, 0.151e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.258e-3),
		new NutrientAmount(Nutrient.VITAMIN_C, 2.4e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.078e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.061e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.557e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.8e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.209e-3),
		new NutrientAmount(Nutrient.FOLATE, 11e-6),
		new NutrientAmount(Nutrient.CHOLINE, 12.3e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 8510e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 7e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.26e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_BETA, 0.01e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_ALPHA, 0.01e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 1.8e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.155),
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 0.01e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/168482/nutrients');
Food.Carrot = new Food('Carrot', {
	group: FoodGroup.VEG,
	measures: {
		unit: 61, // https://www.liveeatlearn.com/how-many-carrots-in-a-pound/
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 88.3),
		new NutrientAmount(Nutrient.PROTEIN, 0.93),
		new NutrientAmount(Nutrient.FAT, 0.24),
		new NutrientAmount(Nutrient.ASH, 0.97),
		new NutrientAmount(Nutrient.FIBER, 2.8),
		new NutrientAmount(Nutrient.SUCROSE, 3.59),
		new NutrientAmount(Nutrient.GLUCOSE, 0.59),
		new NutrientAmount(Nutrient.FRUCTOSE, 0.55),
		new NutrientAmount(Nutrient.STARCH, 1.43),
		new NutrientAmount(Nutrient.CALCIUM, 33e-3),
		new NutrientAmount(Nutrient.IRON, 0.3e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 12e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 35e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 320e-3),
		new NutrientAmount(Nutrient.SODIUM, 69e-3),
		new NutrientAmount(Nutrient.ZINC, 0.24e-3),
		new NutrientAmount(Nutrient.COPPER, 0.045e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.143e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.1e-6),
		new NutrientAmount(Nutrient.FLUORIDE, 3.2e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 5.9e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.066e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.058e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.983e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.273e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.138e-3),
		new NutrientAmount(Nutrient.BIOTIN, 2.22e-6), // 2258586
		new NutrientAmount(Nutrient.FOLATE, 19e-6),
		new NutrientAmount(Nutrient.CHOLINE, 8.8e-3),
		new NutrientAmount(Nutrient.BETAINE, 0.4e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 8280e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 3480e-6),
		new NutrientAmount(Nutrient.LYCOPENE, 1e-6),
		new NutrientAmount(Nutrient.LUTEIN, 256e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.66e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_BETA, 0.01e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_ALPHA, 0.01e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 13.2e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.366),
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 0.21e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/170393/nutrients');
Food.Peanut = new Food('Peanut', {
	group: FoodGroup.GRAIN,
	measures: {
		unit: 0.8, // https://weighschool.com/peanut-weights-calories-including-calculator-charts/
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 6.5),
		new NutrientAmount(Nutrient.PROTEIN, 25.8),
		new NutrientAmount(Nutrient.FAT, 49.2),
		new NutrientAmount(Nutrient.ASH, 2.33),
		new NutrientAmount(Nutrient.FIBER, 8.5),
		new NutrientAmount(Nutrient.SUGAR, 4.72),
		new NutrientAmount(Nutrient.CALCIUM, 92e-3),
		new NutrientAmount(Nutrient.IRON, 4.58e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 168e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 376e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 705e-3),
		new NutrientAmount(Nutrient.SODIUM, 18e-3),
		new NutrientAmount(Nutrient.ZINC, 3.27e-3),
		new NutrientAmount(Nutrient.COPPER, 1.14e-3),
		new NutrientAmount(Nutrient.MANGANESE, 1.93e-3),
		new NutrientAmount(Nutrient.SELENIUM, 7.2e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.64e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.135e-3),
		new NutrientAmount(Nutrient.NIACIN, 12.1e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 1.77e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.348e-3),
		new NutrientAmount(Nutrient.FOLATE, 240e-6),
		new NutrientAmount(Nutrient.CHOLINE, 52.5e-3),
		new NutrientAmount(Nutrient.BETAINE, 0.6e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 8.33e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 5.39),
		// other sources...
		new NutrientAmount(Nutrient.RESVERATROL, (0.01 + 0.26)*1e-3/2 /1.46), // https://en.wikipedia.org/wiki/Resveratrol#Foods
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/172430/nutrients');
Food.Lime = new Food('Lime', {
	group: FoodGroup.FRUIT,
	measures: {
		unit: 65,
		slice: 8,
		cup: 200,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 88.3),
		new NutrientAmount(Nutrient.PROTEIN, 0.7),
		new NutrientAmount(Nutrient.FAT, 0.2),
		new NutrientAmount(Nutrient.FIBER, 2.8),
		new NutrientAmount(Nutrient.SUGAR, 1.69),
		new NutrientAmount(Nutrient.CALCIUM, 33e-3),
		new NutrientAmount(Nutrient.IRON, 0.6e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 6e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 18e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 102e-3),
		new NutrientAmount(Nutrient.SODIUM, 2e-3),
		new NutrientAmount(Nutrient.ZINC, 0.11e-3),
		new NutrientAmount(Nutrient.COPPER, 0.065e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.4e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 29.1e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.03e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.02e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.2e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.043e-3),
		new NutrientAmount(Nutrient.FOLATE, 8e-6),
		new NutrientAmount(Nutrient.CHOLINE, 5.1e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 30e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.22e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 0.6e-6),
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 0.4e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/2344664/nutrients');
Food.RiceWhite = new Food('White Rice', {
	group: FoodGroup.GRAIN,
	ignoreNutrientWarning: true,
	measures: {
		cup: 185,
		grain: 0.03,
		unit: 0.03, // https://www.quora.com/How-much-does-a-single-grain-of-rice-weigh
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 10.5),
		new NutrientAmount(Nutrient.PROTEIN, 6.81),
		new NutrientAmount(Nutrient.FAT, 0.55),
		new NutrientAmount(Nutrient.ASH, 0.49),
		new NutrientAmount(Nutrient.FIBER, 2.8),
		new NutrientAmount(Nutrient.STARCH, 81.7-2.8),
		new NutrientAmount(Nutrient.CALCIUM, 11e-3),
		new NutrientAmount(Nutrient.IRON, 1.6e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 23e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 71e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 77e-3),
		new NutrientAmount(Nutrient.SODIUM, 7e-3),
		new NutrientAmount(Nutrient.ZINC, 1.2e-3),
		new NutrientAmount(Nutrient.COPPER, 0.171e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.974e-3),
		new NutrientAmount(Nutrient.SELENIUM, 15.1e-6),
		new NutrientAmount(Nutrient.MOLYBDENUM, 64.2e-6), // 2512381
		new NutrientAmount(Nutrient.THIAMIN, 0.18e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.055e-3),
		new NutrientAmount(Nutrient.NIACIN, 2.14e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.824e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.107e-3),
		new NutrientAmount(Nutrient.FOLATE, 7e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 1.33),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/168883/nutrients');
Food.Egg = new Food('Egg', {
	group: FoodGroup.MEAT,
	measures: {
		egg: 50.3,
		unit: 50.3,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 75.8),
		new NutrientAmount(Nutrient.NITROGEN, 1.99),
		new NutrientAmount(Nutrient.PROTEIN, 12.4),
		new NutrientAmount(Nutrient.FAT, 9.96),
		new NutrientAmount(Nutrient.ASH, 0.85),
		new NutrientAmount(Nutrient.GLUCOSE, 0.2),
		new NutrientAmount(Nutrient.CALCIUM, 48e-3),
		new NutrientAmount(Nutrient.IRON, 1.67e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 11.4e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 184e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 132e-3),
		new NutrientAmount(Nutrient.SODIUM, 129e-3),
		new NutrientAmount(Nutrient.ZINC, 1.24e-3),
		new NutrientAmount(Nutrient.IODINE, 49.1e-6),
		new NutrientAmount(Nutrient.SELENIUM, 31.1e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.077e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.419e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.063e-3),
		new NutrientAmount(Nutrient.FOLATE, 71e-6),
		new NutrientAmount(Nutrient.CHOLINE, 335e-3),
		new NutrientAmount(Nutrient.BETAINE, 0.3e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 1.02e-6),
		new NutrientAmount(Nutrient.RETINOL, 179e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 13e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_ALPHA, 13e-6),
		new NutrientAmount(Nutrient.CIS_LUTEIN, 57e-6),
		new NutrientAmount(Nutrient.LUTEIN, 230e-6),
		new NutrientAmount(Nutrient.ZEAXANTHIN, 229e-6),
		new NutrientAmount(Nutrient.VITAMIN_D3, 2.46e-6),
		new NutrientAmount(Nutrient._25_HYDROXYCHOLECALCIFEROL, 0.56e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 411e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 1.63),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/748967/nutrients');
Food.Bacon = new Food('Bacon', {
	group: FoodGroup.MEAT,
	measures: {
		package: 442,
		slice: 28,
		unit: 28,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 46.7),
		new NutrientAmount(Nutrient.PROTEIN, 13.7),
		new NutrientAmount(Nutrient.FAT, 37.1),
		new NutrientAmount(Nutrient.ASH, 2.59),
		new NutrientAmount(Nutrient.GLUCOSE, 0.35),
		new NutrientAmount(Nutrient.CALCIUM, 6e-3),
		new NutrientAmount(Nutrient.IRON, 0.38e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 13e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 166e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 201e-3),
		new NutrientAmount(Nutrient.SODIUM, 751e-3),
		new NutrientAmount(Nutrient.ZINC, 1.14e-3),
		new NutrientAmount(Nutrient.COPPER, 0.046e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.012e-3),
		new NutrientAmount(Nutrient.SELENIUM, 20.1e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.276e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.081e-3),
		new NutrientAmount(Nutrient.NIACIN, 4.02e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.555e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.266e-3),
		new NutrientAmount(Nutrient.CHOLINE, 47.8e-3),
		new NutrientAmount(Nutrient.BETAINE, 3.7e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 0.5e-6),
		new NutrientAmount(Nutrient.RETINOL, 11e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.43e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_BETA, 1.01e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 0.65e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_DELTA, 0.01e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_ALPHA, 0.03e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_BETA, 0.02e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_GAMMA, 0.05e-3),
		new NutrientAmount(Nutrient.VITAMIN_D3, 0.4e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 66e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 5.26 * 13.7/35.7), // est'd from 167914
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/168277/nutrients');
Food.BreadRye = new Food('Rye Bread', {
	group: FoodGroup.GRAIN,
	measures: {
		slice: 32,
		unit: 32,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 37.3),
		new NutrientAmount(Nutrient.PROTEIN, 8.5),
		new NutrientAmount(Nutrient.FAT, 3.3),
		new NutrientAmount(Nutrient.ASH, 2.5),
		new NutrientAmount(Nutrient.FIBER, 5.8),
		new NutrientAmount(Nutrient.SUGAR, 3.85),
		new NutrientAmount(Nutrient.CALCIUM, 73e-3),
		new NutrientAmount(Nutrient.IRON, 2.83e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 40e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 125e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 166e-3),
		new NutrientAmount(Nutrient.SODIUM, 603e-3),
		new NutrientAmount(Nutrient.ZINC, 1.14e-3),
		new NutrientAmount(Nutrient.COPPER, 0.186e-3),
		new NutrientAmount(Nutrient.SELENIUM, 30.9e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 0.4e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.434e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.335e-3),
		new NutrientAmount(Nutrient.NIACIN, 3.8e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.075e-3),
		new NutrientAmount(Nutrient.FOLATE, 110e-6),
		new NutrientAmount(Nutrient.CHOLINE, 14.6e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 4e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 1e-6),
		new NutrientAmount(Nutrient.LUTEIN, 54e-6),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 1.2e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 2.6),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/172684/nutrients');
Food.ChocolateDark = new Food('Dark Chocolate (70-85%)', {
	group: FoodGroup.SWEETS,
	measures: {
		bar: 101,
		unit: 101,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 1.37),
		new NutrientAmount(Nutrient.PROTEIN, 7.79),
		new NutrientAmount(Nutrient.FAT, 42.6),
		new NutrientAmount(Nutrient.ASH, 2.32),
		new NutrientAmount(Nutrient.FIBER, 10.9),
		new NutrientAmount(Nutrient.SUCROSE, 24),
		new NutrientAmount(Nutrient.CALCIUM, 73e-3),
		new NutrientAmount(Nutrient.IRON, 11.9e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 228e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 308e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 715e-3),
		new NutrientAmount(Nutrient.SODIUM, 20e-3),
		new NutrientAmount(Nutrient.ZINC, 3.31e-3),
		new NutrientAmount(Nutrient.COPPER, 1.77e-3),
		new NutrientAmount(Nutrient.MANGANESE, 1.95e-3),
		new NutrientAmount(Nutrient.SELENIUM, 6.8e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.034e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.078e-3),
		new NutrientAmount(Nutrient.NIACIN, 1.05e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.418e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.038e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 0.28e-6),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 19e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 7e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 1e-6),
		new NutrientAmount(Nutrient.LUTEIN, 27e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.59e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_BETA, 0.01e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 9.19e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_DELTA, 0.29e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_GAMMA, 0.14e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 7.3e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 3e-3),
		new NutrientAmount(Nutrient.STIGMASTEROL, 31e-3),
		new NutrientAmount(Nutrient.CAMPESTEROL, 12e-3),
		new NutrientAmount(Nutrient.SITOSTEROL_BETA, 86e-3),
		new NutrientAmount(Nutrient.CAFFEINE, 80e-3),
		new NutrientAmount(Nutrient.THEOBROMINE, 802e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 2.95 * 7.79/19.6), // est'd from 169593
		// other sources...
		new NutrientAmount(Nutrient.RESVERATROL, (0.28 + 0.46)*1e-3/2 /2 * 0.5), // assuming 50% cocoa powder; https://en.wikipedia.org/wiki/Resveratrol#Foods
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/170273/nutrients');
Food.MilkSoy = new Food('Soy Milk', {
	group: FoodGroup.DAIRY,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 92.4),
		new NutrientAmount(Nutrient.NITROGEN, 0.57),
		new NutrientAmount(Nutrient.PROTEIN, 3.55),
		new NutrientAmount(Nutrient.FAT, 2.12),
		new NutrientAmount(Nutrient.ASH, 0.64),
		new NutrientAmount(Nutrient.SUCROSE, 0.56),
		new NutrientAmount(Nutrient.RAFFINOSE, 0.07),
		new NutrientAmount(Nutrient.STACHYOSE, 0.43),
		new NutrientAmount(Nutrient.VERBASCOSE, 0.03),
		new NutrientAmount(Nutrient.CALCIUM, 101e-3),
		new NutrientAmount(Nutrient.IRON, 0.54e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 21.5e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 69e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 158e-3),
		new NutrientAmount(Nutrient.SODIUM, 34e-3),
		new NutrientAmount(Nutrient.ZINC, 0.31e-3),
		new NutrientAmount(Nutrient.COPPER, 0.108e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.208e-3),
		new NutrientAmount(Nutrient.SELENIUM, 1.9e-6),
		new NutrientAmount(Nutrient.MOLYBDENUM, 58.4e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.063e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.084e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.236e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.055e-3),
		new NutrientAmount(Nutrient.BIOTIN, 3.34e-6),
		new NutrientAmount(Nutrient.VITAMIN_B12, 0.39e-6),
		new NutrientAmount(Nutrient.RETINOL, 58e-6),
		new NutrientAmount(Nutrient.LUTEIN, 8e-6),
		new NutrientAmount(Nutrient.CIS_LUTEIN, 1e-6),
		new NutrientAmount(Nutrient.ZEAXANTHIN, 7e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.16e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 1.42e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_DELTA, 0.87e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_GAMMA, 0.14e-3),
		new NutrientAmount(Nutrient.VITAMIN_D2, 0.68e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.619),
		new NutrientAmount(Nutrient.DAIDZEIN, 0.46e-3),
		new NutrientAmount(Nutrient.GENISTEIN, 0.38e-3),
		new NutrientAmount(Nutrient.DAIDZIN, 12.9e-3),
		new NutrientAmount(Nutrient.GENISTIN, 18.81e-3),
		new NutrientAmount(Nutrient.GLYCITIN, 1.36e-3),
		// other sources...
		new NutrientAmount(Nutrient.COUMESTROL, 0.81e-3), // https://en.wikipedia.org/wiki/Coumestrol
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/1999630/nutrients');
Food.Tofu = new Food('Tofu', {
	group: FoodGroup.DAIRY,
	measures: {
		cup: 248,
		piece: 120,
		cu_in: 17.6,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 87.3),
		new NutrientAmount(Nutrient.PROTEIN, 7.17),
		new NutrientAmount(Nutrient.FAT, 3.69),
		new NutrientAmount(Nutrient.FIBER, 0.2),
		new NutrientAmount(Nutrient.SUGAR, 0.7),
		new NutrientAmount(Nutrient.CALCIUM, 111e-3),
		new NutrientAmount(Nutrient.IRON, 1.11e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 27e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 92e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 120e-3),
		new NutrientAmount(Nutrient.SODIUM, 8e-3),
		new NutrientAmount(Nutrient.ZINC, 0.64e-3),
		new NutrientAmount(Nutrient.COPPER, 0.157e-3),
		new NutrientAmount(Nutrient.SELENIUM, 8.9e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 0.2e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.047e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.037e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.535e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.052e-3),
		new NutrientAmount(Nutrient.FOLATE, 44e-6),
		new NutrientAmount(Nutrient.CHOLINE, 27.4e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 4e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.01e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 2e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 1.18 * 7.17/6.9), // est'd from 172461
		// other sources...
		new NutrientAmount(Nutrient.COUMESTROL, 0.12e-3), // https://en.wikipedia.org/wiki/Coumestrol
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/2342910/nutrients');
Food.Garlic = new Food('Garlic', {
	group: FoodGroup.VEG,
	measures: { // guesses
		bulb: 50,
		clove: 5,
		unit: 50,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 58.58),
		new NutrientAmount(Nutrient.PROTEIN, 6.36),
		new NutrientAmount(Nutrient.FAT, 0.5),
		new NutrientAmount(Nutrient.FIBER, 2.1),
		new NutrientAmount(Nutrient.SUGAR, 1),
		new NutrientAmount(Nutrient.CALCIUM, 181e-3),
		new NutrientAmount(Nutrient.IRON, 1.7e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 25e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 153e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 401e-3),
		new NutrientAmount(Nutrient.SODIUM, 17e-3),
		new NutrientAmount(Nutrient.ZINC, 1.16e-3),
		new NutrientAmount(Nutrient.COPPER, 0.299e-3),
		new NutrientAmount(Nutrient.SELENIUM, 14.2e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 31.2e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.2e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.11e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.7e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 1.235e-3),
		new NutrientAmount(Nutrient.FOLATE, 3e-6),
		new NutrientAmount(Nutrient.CHOLINE, 23.2e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 5e-6),
		new NutrientAmount(Nutrient.LUTEIN, 16e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.08e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 1.7e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.805), // est'd from 169230
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 1.74e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/1103354/nutrients');
Food.Seaweed = new Food('Seaweed', {
	group: FoodGroup.VEG,
	measures: {
		cup: 15,
		strip: 0.5,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 6.68),
		new NutrientAmount(Nutrient.PROTEIN, 31.8),
		new NutrientAmount(Nutrient.FAT, 4.01),
		new NutrientAmount(Nutrient.FIBER, 5.6),
		new NutrientAmount(Nutrient.SUGAR, 3.04),
		new NutrientAmount(Nutrient.CALCIUM, 372e-3),
		new NutrientAmount(Nutrient.IRON, 25e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 482e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 85e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 1240e-3),
		new NutrientAmount(Nutrient.SODIUM, 575e-3),
		new NutrientAmount(Nutrient.ZINC, 3.9e-3),
		new NutrientAmount(Nutrient.COPPER, 3.36e-3),
		new NutrientAmount(Nutrient.SELENIUM, 7.3e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 5e-3),
		new NutrientAmount(Nutrient.THIAMIN, 1.2e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 1.95e-3),
		new NutrientAmount(Nutrient.NIACIN, 6.51e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.334e-3),
		new NutrientAmount(Nutrient.FOLATE, 337e-6),
		new NutrientAmount(Nutrient.CHOLINE, 64.6e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 171e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 5e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 25e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 2.44),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/2345512/nutrients');
Food.Sorghum = new Food('Sorghum', {
	group: FoodGroup.GRAIN,
	measures: {
		cup: 192,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 12.4),
		new NutrientAmount(Nutrient.PROTEIN, 10.6),
		new NutrientAmount(Nutrient.FAT, 3.46),
		new NutrientAmount(Nutrient.ASH, 1.43),
		new NutrientAmount(Nutrient.FIBER, 6.7),
		new NutrientAmount(Nutrient.SUGAR, 2.53),
		new NutrientAmount(Nutrient.CALCIUM, 13e-3),
		new NutrientAmount(Nutrient.IRON, 3.36e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 165e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 289e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 363e-3),
		new NutrientAmount(Nutrient.SODIUM, 2e-3),
		new NutrientAmount(Nutrient.ZINC, 1.67e-3),
		new NutrientAmount(Nutrient.COPPER, 0.284e-3),
		new NutrientAmount(Nutrient.SELENIUM, 12.2e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.332e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.096e-3),
		new NutrientAmount(Nutrient.NIACIN, 3.69e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.367e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.443e-3),
		new NutrientAmount(Nutrient.FOLATE, 20e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.5e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 2.44),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/169716/nutrients');
Food.Thyme = new Food('Thyme (dried)', {
	group: FoodGroup.VEG,
	measures: {
		tsp: 1,
		tbsp: 2.7,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 7.79),
		new NutrientAmount(Nutrient.PROTEIN, 9.11),
		new NutrientAmount(Nutrient.FAT, 7.43),
		new NutrientAmount(Nutrient.ASH, 11.7),
		new NutrientAmount(Nutrient.FIBER, 37),
		new NutrientAmount(Nutrient.SUGAR, 1.71),
		new NutrientAmount(Nutrient.CALCIUM, 1890e-3),
		new NutrientAmount(Nutrient.IRON, 124e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 220e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 201e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 814e-3),
		new NutrientAmount(Nutrient.SODIUM, 55e-3),
		new NutrientAmount(Nutrient.ZINC, 6.18e-3),
		new NutrientAmount(Nutrient.COPPER, 0.86e-3),
		new NutrientAmount(Nutrient.MANGANESE, 7.87e-3),
		new NutrientAmount(Nutrient.SELENIUM, 4.6e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 50e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.513e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.399e-3),
		new NutrientAmount(Nutrient.NIACIN, 4.94e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.55e-3),
		new NutrientAmount(Nutrient.FOLATE, 274e-6),
		new NutrientAmount(Nutrient.CHOLINE, 43.6e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 2260e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 33e-6),
		new NutrientAmount(Nutrient.LUTEIN, 1900e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 7.48e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 1710e-6),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/170938/nutrients');
Food.WineRed = new Food('Red Wine', {
	group: FoodGroup.OTHER,
	measures: {
		floz: 30,
		glass: 180,
		bottle: 750,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 86.5),
		new NutrientAmount(Nutrient.PROTEIN, 0.07),
		new NutrientAmount(Nutrient.SUGAR, 0.62),
		new NutrientAmount(Nutrient.CALCIUM, 8e-3),
		new NutrientAmount(Nutrient.IRON, 0.46e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 12e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 23e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 127e-3),
		new NutrientAmount(Nutrient.SODIUM, 4e-3),
		new NutrientAmount(Nutrient.ZINC, 0.14e-3),
		new NutrientAmount(Nutrient.COPPER, 0.011e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.2e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.005e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.031e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.224e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.057e-3),
		new NutrientAmount(Nutrient.FOLATE, 1e-6),
		new NutrientAmount(Nutrient.CHOLINE, 5.7e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 1e-6),
		new NutrientAmount(Nutrient.LUTEIN, 6e-6),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 0.4e-6),
		new NutrientAmount(Nutrient.ALCOHOL, 10.6),
		// other sources...
		new NutrientAmount(Nutrient.RESVERATROL, 270e-6), // https://en.wikipedia.org/wiki/Resveratrol#Foods
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/2346263/nutrients');
Food.PeanutButter = new Food('Peanut Butter', {
	group: FoodGroup.OTHER,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 1.1),
		new NutrientAmount(Nutrient.NITROGEN, 4.39),
		new NutrientAmount(Nutrient.PROTEIN, 24),
		new NutrientAmount(Nutrient.FAT, 49.4),
		new NutrientAmount(Nutrient.ASH, 2.77),
		new NutrientAmount(Nutrient.FIBER, 6.3),
		new NutrientAmount(Nutrient.SUGAR, 22.7-6.3),
		new NutrientAmount(Nutrient.CALCIUM, 50e-3),
		new NutrientAmount(Nutrient.IRON, 1.85e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 193e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 393e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 654e-3),
		new NutrientAmount(Nutrient.SODIUM, 221e-3),
		new NutrientAmount(Nutrient.ZINC, 3.06e-3),
		new NutrientAmount(Nutrient.COPPER, 0.54e-3),
		new NutrientAmount(Nutrient.MANGANESE, 1.68e-3),
		new NutrientAmount(Nutrient.SELENIUM, 20.2e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.121e-3),
		new NutrientAmount(Nutrient.NIACIN, 17.2e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.38e-3),
		new NutrientAmount(Nutrient.BIOTIN, 87.8e-6),
		new NutrientAmount(Nutrient.FOLATE, 97e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 5.41e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 5.82),
		new NutrientAmount(Nutrient.DAIDZEIN, 11.5e-3),
		new NutrientAmount(Nutrient.DAIDZIN, 0.649e-3),
		new NutrientAmount(Nutrient.GENISTIN, 1.932e-3),
		new NutrientAmount(Nutrient.GLYCITIN, 0.41e-3),
		// other sources...
		new NutrientAmount(Nutrient.RESVERATROL, (0.04 + 0.13)*1e-3/2 /2.58), // https://en.wikipedia.org/wiki/Resveratrol#Foods
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/2262072/nutrients');
Food.Banana = new Food('Banana', {
	group: FoodGroup.FRUIT,
	measures: {
		cup: 150,
		slice: 6,
		unit: 126,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 75.6),
		new NutrientAmount(Nutrient.PROTEIN, 0.74),
		new NutrientAmount(Nutrient.FAT, 0.28),
		new NutrientAmount(Nutrient.FIBER, 1.7),
		new NutrientAmount(Nutrient.SUGAR, 15.8),
		new NutrientAmount(Nutrient.CALCIUM, 5e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 28e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 22e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 326e-3),
		new NutrientAmount(Nutrient.SODIUM, 3e-3 * 3/75.6), // est'd from 173945
		new NutrientAmount(Nutrient.ZINC, 0.16e-3),
		new NutrientAmount(Nutrient.COPPER, 0.101e-3),
		new NutrientAmount(Nutrient.VITAMIN_C, 12e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.054e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.653e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.212e-3),
		new NutrientAmount(Nutrient.FOLATE, 15e-6),
		new NutrientAmount(Nutrient.CHOLINE, 9.8e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 8e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 7e-6),
		new NutrientAmount(Nutrient.LUTEIN, 22e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.1e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 0.1e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.399 * 0.74/3.89), // est'd from 173945
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 21.4e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/2344720/nutrients');
Food.MushroomWhiteButton = new Food('White Button Mushroom', {
	group: FoodGroup.VEG,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 91.8),
		new NutrientAmount(Nutrient.PROTEIN, 2.89),
		new NutrientAmount(Nutrient.FAT, 0.37),
		new NutrientAmount(Nutrient.FIBER, 1.7),
		new NutrientAmount(Nutrient.SUGAR, 4.08-1.7),
		new NutrientAmount(Nutrient.CALCIUM, 5e-3),
		new NutrientAmount(Nutrient.IRON, 0.23e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 10.2e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 93e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 373e-3),
		new NutrientAmount(Nutrient.SODIUM, 6e-3),
		new NutrientAmount(Nutrient.ZINC, 0.51e-3),
		new NutrientAmount(Nutrient.COPPER, 0.389e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.054e-3),
		new NutrientAmount(Nutrient.SELENIUM, 20e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.065e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.444e-3),
		new NutrientAmount(Nutrient.NIACIN, 3.88e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.077e-3),
		new NutrientAmount(Nutrient.BIOTIN, 9.07e-6),
		new NutrientAmount(Nutrient.FOLATE, 35e-6),
		new NutrientAmount(Nutrient.VITAMIN_D2, 0.02e-6),
		new NutrientAmount(Nutrient.ERGOSTA_7_ENOL, 1.63e-3),
		new NutrientAmount(Nutrient.ERGOSTA_5_7_DIENOL, 5.84e-3),
		new NutrientAmount(Nutrient.ERGOSTA_7_22_DIENOL, 1.54e-3),
		new NutrientAmount(Nutrient.ERGOSTEROL, 56e-3),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/1999629/nutrients');
Food.Blueberry = new Food('Blueberry', {
	group: FoodGroup.FRUIT,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 84.2),
		new NutrientAmount(Nutrient.PROTEIN, 0.74),
		new NutrientAmount(Nutrient.FAT, 0.33),
		new NutrientAmount(Nutrient.ASH, 0.24),
		new NutrientAmount(Nutrient.FIBER, 2.4),
		new NutrientAmount(Nutrient.SUCROSE, 0.11),
		new NutrientAmount(Nutrient.GLUCOSE, 4.88),
		new NutrientAmount(Nutrient.FRUCTOSE, 4.97),
		new NutrientAmount(Nutrient.STARCH, 0.03),
		new NutrientAmount(Nutrient.CALCIUM, 6e-3),
		new NutrientAmount(Nutrient.IRON, 0.28e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 6e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 12e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 77e-3),
		new NutrientAmount(Nutrient.SODIUM, 1e-3),
		new NutrientAmount(Nutrient.ZINC, 0.16e-3),
		new NutrientAmount(Nutrient.COPPER, 0.057e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.336e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.1e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 9.7e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.037e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.041e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.418e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.124e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.052e-3),
		new NutrientAmount(Nutrient.FOLATE, 6e-6),
		new NutrientAmount(Nutrient.CHOLINE, 6e-3),
		new NutrientAmount(Nutrient.BETAINE, 0.2e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 32e-6),
		new NutrientAmount(Nutrient.LUTEIN, 80e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.57e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_BETA, 0.01e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 0.36e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_DELTA, 0.03e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_GAMMA, 0.07e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 19.3e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.091),
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 7.67e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/171711/nutrients');
Food.Jalapeno = new Food('Jalapeño', {
	group: FoodGroup.VEG,
	measures: {
		cup: 90,
		unit: 14,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 91.7),
		new NutrientAmount(Nutrient.PROTEIN, 0.91),
		new NutrientAmount(Nutrient.FAT, 0.37),
		new NutrientAmount(Nutrient.ASH, 0.53),
		new NutrientAmount(Nutrient.FIBER, 2.8),
		new NutrientAmount(Nutrient.GLUCOSE, 1.48),
		new NutrientAmount(Nutrient.FRUCTOSE, 2.63),
		new NutrientAmount(Nutrient.CALCIUM, 12e-3),
		new NutrientAmount(Nutrient.IRON, 0.25e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 15e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 26e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 248e-3),
		new NutrientAmount(Nutrient.SODIUM, 3e-3),
		new NutrientAmount(Nutrient.ZINC, 0.14e-3),
		new NutrientAmount(Nutrient.COPPER, 0.046e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.097e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.4e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 119e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.04e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.07e-3),
		new NutrientAmount(Nutrient.NIACIN, 1.28e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.315e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.419e-3),
		new NutrientAmount(Nutrient.FOLATE, 27e-6),
		new NutrientAmount(Nutrient.CHOLINE, 7.5e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 561e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 67e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 105e-6),
		new NutrientAmount(Nutrient.LUTEIN, 861e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_BETA, 0.17e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 0.05e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_DELTA, 0.01e-3),
		new NutrientAmount(Nutrient.TOCOTRIENOL_ALPHA, 0.02e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 18.5e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.122 * 0.91/0.92), // est'd from 170080
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 5.07e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/168576/nutrients');
Food.Jalapeno = new Food('Guava', {
	group: FoodGroup.FRUIT,
	measures: {
		cup: 165,
		unit: 55,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 80.8),
		new NutrientAmount(Nutrient.PROTEIN, 2.55),
		new NutrientAmount(Nutrient.FAT, 0.95),
		new NutrientAmount(Nutrient.ASH, 1.39),
		new NutrientAmount(Nutrient.FIBER, 5.4),
		new NutrientAmount(Nutrient.SUGAR, 8.92),
		new NutrientAmount(Nutrient.CALCIUM, 18e-3),
		new NutrientAmount(Nutrient.IRON, 0.26e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 22e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 40e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 417e-3),
		new NutrientAmount(Nutrient.SODIUM, 2e-3),
		new NutrientAmount(Nutrient.ZINC, 0.23e-3),
		new NutrientAmount(Nutrient.COPPER, 0.23e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.15e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.6e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 228e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.067e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.04e-3),
		new NutrientAmount(Nutrient.NIACIN, 1.08e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.451e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.11e-3),
		new NutrientAmount(Nutrient.FOLATE, 49e-6),
		new NutrientAmount(Nutrient.CHOLINE, 7.6e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 374e-6),
		new NutrientAmount(Nutrient.LYCOPENE, 5200e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.73e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 2.6e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.333),
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 1.1e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/173044/nutrients');
Food.ChickenThigh = new Food('Chicken Thigh', {
	group: FoodGroup.MEAT,
	measures: {
		unit: 191,
	},
	ignoreNutrientWarning: true,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 77.2),
		new NutrientAmount(Nutrient.PROTEIN, 19.1),
		new NutrientAmount(Nutrient.FAT, 3.69),
		new NutrientAmount(Nutrient.ASH, 1.04),
		new NutrientAmount(Nutrient.CALCIUM, 8e-3),
		new NutrientAmount(Nutrient.IRON, 0.6e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 21e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 175e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 234e-3),
		new NutrientAmount(Nutrient.SODIUM, 156e-3),
		new NutrientAmount(Nutrient.ZINC, 1.53e-3),
		new NutrientAmount(Nutrient.COPPER, 0.053e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.009e-3),
		new NutrientAmount(Nutrient.SELENIUM, 20.9e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.087e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.23e-3),
		new NutrientAmount(Nutrient.NIACIN, 5.3e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 1.25e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.433e-3),
		new NutrientAmount(Nutrient.FOLATE, 3e-6),
		new NutrientAmount(Nutrient.CHOLINE, 75.1e-3),
		new NutrientAmount(Nutrient.BETAINE, 12e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 0.56e-6),
		new NutrientAmount(Nutrient.RETINOL, 6e-6),
		new NutrientAmount(Nutrient.LUTEIN, 87e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.26e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 0.09e-3),
		new NutrientAmount(Nutrient.VITAMIN_D3, 0.1e-6),
		new NutrientAmount(Nutrient.MENAQUINONE_4, 8.5e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 87e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 3.01),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/172859/nutrients');
Food.Butter = new Food('Butter', { // salted
	group: FoodGroup.DAIRY,
	measures: {
		stick: 113,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 15.8),
		new NutrientAmount(Nutrient.PROTEIN, 0.553), // reconstructed from AA table
		new NutrientAmount(Nutrient.FAT, 82.2),
		new NutrientAmount(Nutrient.LACTOSE, 0.58),
		new NutrientAmount(Nutrient.CALCIUM, 21e-3),
		new NutrientAmount(Nutrient.IRON, 0.06e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 1.6e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 22e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 23e-3),
		new NutrientAmount(Nutrient.SODIUM, 524e-3),
		new NutrientAmount(Nutrient.ZINC, 0.07e-3),
		new NutrientAmount(Nutrient.COPPER, 0.006e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.005e-3),
		new NutrientAmount(Nutrient.FOLATE, 5e-6),
		new NutrientAmount(Nutrient.RETINOL, 5e-6),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 168e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 2e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 8e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_ALPHA, 2e-6),
		new NutrientAmount(Nutrient.ZEAXANTHIN, 1e-6),
		new NutrientAmount(Nutrient.LUTEIN, 12e-6),
		new NutrientAmount(Nutrient.VITAMIN_D3, 0.4e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.08),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/790508/nutrients');
Food.BeefGround = new Food('Beef (Ground)', {
	group: FoodGroup.MEAT,
	measures: {
		serving: 85,
	},
	ignoreNutrientWarning: true,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 67.1),
		new NutrientAmount(Nutrient.PROTEIN, 19.4),
		new NutrientAmount(Nutrient.FAT, 12.7),
		new NutrientAmount(Nutrient.ASH, 1.71),
		new NutrientAmount(Nutrient.CALCIUM, 12e-3),
		new NutrientAmount(Nutrient.IRON, 1.99e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 19e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 175e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 289e-3),
		new NutrientAmount(Nutrient.SODIUM, 68e-3),
		new NutrientAmount(Nutrient.ZINC, 4.55e-3),
		new NutrientAmount(Nutrient.COPPER, 0.063e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.01e-3),
		new NutrientAmount(Nutrient.SELENIUM, 14.2e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.049e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.154e-3),
		new NutrientAmount(Nutrient.NIACIN, 4.82e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.576e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.355e-3),
		new NutrientAmount(Nutrient.FOLATE, 6e-6),
		new NutrientAmount(Nutrient.CHOLINE, 67.4e-3),
		new NutrientAmount(Nutrient.BETAINE, 8e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 1.97e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.35e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 1.1e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 62e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 3 * 19.4/20), // est'd from https://fdc.nal.usda.gov/fdc-app.html#/food-details/174030/nutrients
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/168608/nutrients');
Food.Milk = new Food('Milk', { // whole, unfortified
	group: FoodGroup.DAIRY,
	measures: {
		cup: 244,
		tbsp: 15,
		floz: 30.5,
		qt: 976,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 88.1),
		new NutrientAmount(Nutrient.PROTEIN, 3.15),
		new NutrientAmount(Nutrient.FAT, 3.27),
		new NutrientAmount(Nutrient.ASH, 0.67),
		new NutrientAmount(Nutrient.LACTOSE, 5.05),
		new NutrientAmount(Nutrient.CALCIUM, 113e-3),
		new NutrientAmount(Nutrient.IRON, 0.03e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 10e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 84e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 132e-3),
		new NutrientAmount(Nutrient.SODIUM, 43e-3),
		new NutrientAmount(Nutrient.ZINC, 0.37e-3),
		new NutrientAmount(Nutrient.COPPER, 0.025e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.004e-3),
		new NutrientAmount(Nutrient.SELENIUM, 3.7e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.046e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.169e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.089e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.373e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.036e-3),
		new NutrientAmount(Nutrient.FOLATE, 5e-6),
		new NutrientAmount(Nutrient.CHOLINE, 14.3e-3),
		new NutrientAmount(Nutrient.BETAINE, 0.6e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 0.45e-6),
		new NutrientAmount(Nutrient.RETINOL, 45e-6),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 7e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.07e-3),
		new NutrientAmount(Nutrient.VITAMIN_D3, 0.1e-6),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 0.3e-6),
		new NutrientAmount(Nutrient.MENAQUINONE_4, 1e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 10e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.708),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/172217/nutrients');
Food.BeefLiver = new Food('Beef Liver', {
	group: FoodGroup.MEAT,
	ignoreNutrientWarning: true,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 70.8),
		new NutrientAmount(Nutrient.PROTEIN, 20.4),
		new NutrientAmount(Nutrient.FAT, 3.63),
		new NutrientAmount(Nutrient.ASH, 1.31),
		new NutrientAmount(Nutrient.CALCIUM, 5e-3),
		new NutrientAmount(Nutrient.IRON, 4.9e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 18e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 387e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 313e-3),
		new NutrientAmount(Nutrient.SODIUM, 69e-3),
		new NutrientAmount(Nutrient.ZINC, 4e-3),
		new NutrientAmount(Nutrient.COPPER, 9.76e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.31e-3),
		new NutrientAmount(Nutrient.SELENIUM, 39.7e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 1.3e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.189e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 2.76e-3),
		new NutrientAmount(Nutrient.NIACIN, 13.2e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 7.17e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 1.08e-3),
		new NutrientAmount(Nutrient.FOLATE, 290e-6),
		new NutrientAmount(Nutrient.CHOLINE, 333e-3),
		new NutrientAmount(Nutrient.BETAINE, 4.4e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 59.3e-6),
		new NutrientAmount(Nutrient.RETINOL, 4950e-6),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 232e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 11e-6),
		new NutrientAmount(Nutrient.CRYPTOXANTHIN_BETA, 13e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.38e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 0.07e-3),
		new NutrientAmount(Nutrient.VITAMIN_D3, 1.2e-6),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 3.1e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 275e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 2.61),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/169451/nutrients');
Food.BeefSweetbread = new Food('Beef Sweetbread', {
	group: FoodGroup.MEAT,
	ignoreNutrientWarning: true,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 57.7),
		new NutrientAmount(Nutrient.PROTEIN, 11.5),
		new NutrientAmount(Nutrient.FAT, 28.6),
		new NutrientAmount(Nutrient.ASH, 2.36),
		new NutrientAmount(Nutrient.CALCIUM, 4e-3),
		new NutrientAmount(Nutrient.IRON, 1.15e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 15e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 331e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 318e-3),
		new NutrientAmount(Nutrient.SODIUM, 64e-3),
		new NutrientAmount(Nutrient.ZINC, 1e-3),
		new NutrientAmount(Nutrient.COPPER, 5.1e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.012e-3),
		new NutrientAmount(Nutrient.SELENIUM, 9e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.087e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.112e-3),
		new NutrientAmount(Nutrient.NIACIN, 2e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.6e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.041e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 2.1e-6),
		new NutrientAmount(Nutrient.RETINOL, 19e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.69e-3),
		new NutrientAmount(Nutrient.VITAMIN_D3, 0.6e-6),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 3.1e-6),
		new NutrientAmount(Nutrient.CHOLESTEROL, 217e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 1.6),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/173093/nutrients');
Food.LambTesticles = new Food('Lamb Testicles', {
	group: FoodGroup.MEAT,
	ignoreNutrientWarning: true,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 85),
		new NutrientAmount(Nutrient.PROTEIN, 11.4),
		new NutrientAmount(Nutrient.FAT, 2.38),
		new NutrientAmount(Nutrient.ASH, 1.08),
		new NutrientAmount(Nutrient.CALCIUM, 5e-3),
		new NutrientAmount(Nutrient.IRON, 1.14e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 11e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 179e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 265e-3),
		new NutrientAmount(Nutrient.SODIUM, 119e-3),
		new NutrientAmount(Nutrient.ZINC, 1.14e-3),
		new NutrientAmount(Nutrient.COPPER, 0.091e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.029e-3),
		new NutrientAmount(Nutrient.SELENIUM, 26.2e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.315e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.214e-3),
		new NutrientAmount(Nutrient.NIACIN, 1.74e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.872e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.033e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 9.89e-6),
		new NutrientAmount(Nutrient.RETINOL, 10e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.31e-3),
		new NutrientAmount(Nutrient.CHOLESTEROL, 393e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 1.59),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/172619/nutrients');
Food.Honey = new Food('Honey', {
	group: FoodGroup.SWEETS,
	measures: {
		cup: 339,
		tbsp: 21,
		packet: 14,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 17.1),
		new NutrientAmount(Nutrient.PROTEIN, 0.3),
		new NutrientAmount(Nutrient.ASH, 0.2),
		new NutrientAmount(Nutrient.FIBER, 0.2),
		new NutrientAmount(Nutrient.SUCROSE, 0.89),
		new NutrientAmount(Nutrient.GLUCOSE, 35.8),
		new NutrientAmount(Nutrient.FRUCTOSE, 40.9),
		new NutrientAmount(Nutrient.MALTOSE, 1.44),
		new NutrientAmount(Nutrient.GALACTOSE, 3.1),
		new NutrientAmount(Nutrient.CALCIUM, 6e-3),
		new NutrientAmount(Nutrient.IRON, 0.42e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 2e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 4e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 52e-3),
		new NutrientAmount(Nutrient.SODIUM, 4e-3),
		new NutrientAmount(Nutrient.ZINC, 0.22e-3),
		new NutrientAmount(Nutrient.COPPER, 0.036e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.08e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.8e-6),
		new NutrientAmount(Nutrient.FLUORIDE, 7e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.315e-3),
		new NutrientAmount(Nutrient.VITAMIN_C, 0.5e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.038e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.121e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.068e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.024e-3),
		new NutrientAmount(Nutrient.FOLATE, 2e-6),
		new NutrientAmount(Nutrient.CHOLINE, 2.2e-3),
		new NutrientAmount(Nutrient.BETAINE, 1.7e-3),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.018),
		// other sources...
		new NutrientAmount(Nutrient.QUERCETIN, 0.31e-3), // https://en.wikipedia.org/wiki/Quercetin#Occurrence
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/169640/nutrients');
Food.Grape = new Food('Grape', {
	group: FoodGroup.FRUIT,
	measures: {
		cup: 151,
		unit: 4.9,
	},
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 80.5),
		new NutrientAmount(Nutrient.PROTEIN, 0.72),
		new NutrientAmount(Nutrient.FAT, 0.16),
		new NutrientAmount(Nutrient.ASH, 0.48),
		new NutrientAmount(Nutrient.FIBER, 0.9),
		new NutrientAmount(Nutrient.SUCROSE, 0.15),
		new NutrientAmount(Nutrient.GLUCOSE, 7.2),
		new NutrientAmount(Nutrient.FRUCTOSE, 8.13),
		new NutrientAmount(Nutrient.CALCIUM, 10e-3),
		new NutrientAmount(Nutrient.IRON, 0.36e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 7e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 20e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 191e-3),
		new NutrientAmount(Nutrient.SODIUM, 2e-3),
		new NutrientAmount(Nutrient.ZINC, 0.07e-3),
		new NutrientAmount(Nutrient.COPPER, 0.127e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.071e-3),
		new NutrientAmount(Nutrient.SELENIUM, 0.1e-6),
		new NutrientAmount(Nutrient.FLUORIDE, 7.8e-6),
		new NutrientAmount(Nutrient.VITAMIN_C, 3.2e-3),
		new NutrientAmount(Nutrient.THIAMIN, 0.069e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.07e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.188e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.05e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.086e-3),
		new NutrientAmount(Nutrient.FOLATE, 2e-6),
		new NutrientAmount(Nutrient.CHOLINE, 5.6e-3),
		new NutrientAmount(Nutrient.BETAINE, 0.1e-3),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 39e-6),
		new NutrientAmount(Nutrient.CAROTENE_ALPHA, 1e-6),
		new NutrientAmount(Nutrient.LUTEIN, 72e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.19e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 0.07e-3),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 14.6e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 0.081),
		// other sources...
		new NutrientAmount(Nutrient.RESVERATROL, (0.24 + 1.25)*1e-3/2 /1.6), // https://en.wikipedia.org/wiki/Resveratrol#Foods
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/174683/nutrients');
Food.CheeseCheddar = new Food('Cheddar', {
	group: FoodGroup.DAIRY,
	nutrients: [
		new NutrientAmount(Nutrient.WATER, 36.2),
		new NutrientAmount(Nutrient.PROTEIN, 24.2),
		new NutrientAmount(Nutrient.FAT, 33.8),
		new NutrientAmount(Nutrient.ASH, 3.66),
		new NutrientAmount(Nutrient.LACTOSE, 0.18),
		new NutrientAmount(Nutrient.GALACTOSE, 0.08),
		new NutrientAmount(Nutrient.CALCIUM, 711e-3),
		new NutrientAmount(Nutrient.IRON, 0.16e-3),
		new NutrientAmount(Nutrient.MAGNESIUM, 27e-3),
		new NutrientAmount(Nutrient.PHOSPHORUS, 460e-3),
		new NutrientAmount(Nutrient.POTASSIUM, 76e-3),
		new NutrientAmount(Nutrient.SODIUM, 644e-3),
		new NutrientAmount(Nutrient.ZINC, 3.74e-3),
		new NutrientAmount(Nutrient.COPPER, 0.035e-3),
		new NutrientAmount(Nutrient.MANGANESE, 0.024e-3),
		new NutrientAmount(Nutrient.SELENIUM, 28.3e-6),
		new NutrientAmount(Nutrient.THIAMIN, 0.027e-3),
		new NutrientAmount(Nutrient.RIBOFLAVIN, 0.434e-3),
		new NutrientAmount(Nutrient.NIACIN, 0.039e-3),
		new NutrientAmount(Nutrient.PANTOTHENIC_ACID, 0.481e-3),
		new NutrientAmount(Nutrient.VITAMIN_B6, 0.075e-3),
		new NutrientAmount(Nutrient.FOLATE, 27e-6),
		new NutrientAmount(Nutrient.CHOLINE, 16.5e-3),
		new NutrientAmount(Nutrient.VITAMIN_B12, 0.88e-6),
		new NutrientAmount(Nutrient.RETINOL, 256e-6),
		new NutrientAmount(Nutrient.CAROTENE_BETA, 85e-6),
		new NutrientAmount(Nutrient.TOCOPHEROL_ALPHA, 0.78e-3),
		new NutrientAmount(Nutrient.TOCOPHEROL_GAMMA, 0.06e-3),
		new NutrientAmount(Nutrient.VITAMIN_D3, 1e-6),
		new NutrientAmount(Nutrient.PHYLLOQUINONE, 2.4e-6),
		new NutrientAmount(Nutrient.MENAQUINONE_4, 8.6e-6),
		new NutrientAmount(Nutrient.GLUTAMIC_ACID, 5.68),
	],
}, 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/170899/nutrients');

if (DEBUG)
	FoodGroupAverage.foodGroupAverages = FoodGroup.groups.map(fg => new FoodGroupAverage(fg));
const NUTRITION_LOADED = true;